# Generated by Django 3.2.15 on 2023-01-09 11:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0028_businessaddress_description'),
        ('Promotions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daterestrictions',
            name='business_address',
        ),
        migrations.AddField(
            model_name='daterestrictions',
            name='business_address',
            field=models.ManyToManyField(blank=True, null=True, related_name='business_address_daterestrictions', to='Business.BusinessAddress'),
        ),
        migrations.CreateModel(
            name='CategoryDiscount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('all_category', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('service_discount', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('retail_discount', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('voucher_discount', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('directorflat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directorflat_categorydiscount', to='Promotions.directorflatdiscount')),
            ],
        ),
    ]
