# Generated by Django 4.0.6 on 2023-11-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial_squashed_0074_client_is_image_uploaded_s3'),
        ('Promotions', '0001_initial_squashed_0033_alter_bundlefixed_spend_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrestricteddiscount',
            name='client',
            field=models.ManyToManyField(related_name='client_userrestricteddiscount', to='Client.client'),
        ),
    ]
