# Generated by Django 3.2.15 on 2023-01-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Promotions', '0002_auto_20230109_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorydiscount',
            old_name='all_category',
            new_name='discount',
        ),
        migrations.RemoveField(
            model_name='categorydiscount',
            name='retail_discount',
        ),
        migrations.RemoveField(
            model_name='categorydiscount',
            name='service_discount',
        ),
        migrations.RemoveField(
            model_name='categorydiscount',
            name='voucher_discount',
        ),
        migrations.AddField(
            model_name='categorydiscount',
            name='category_type',
            field=models.CharField(blank=True, choices=[('All', 'All'), ('Service', 'Service'), ('Retail', 'Retail'), ('Voucher', 'Voucher')], max_length=50, null=True),
        ),
    ]
