# Generated by Django 3.2.15 on 2023-01-10 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0041_productorderstockreport_reorder_quantity'),
        ('Service', '0024_priceservice_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Business', '0028_businessaddress_description'),
        ('Promotions', '0003_auto_20230110_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificGroupDiscount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businessgroup_specific_discount', to='Business.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_specificgroup_discount', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceGroupDiscount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('discount', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('servicegroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicegroup_specificgroupdiscount', to='Service.servicegroup')),
                ('specificgroupdiscount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicegroupdiscount_specificgroupdiscount', to='Promotions.specificgroupdiscount')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseDiscount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('select_type', models.CharField(blank=True, choices=[('Service', 'Service'), ('Product', 'Product')], default='Product', max_length=50, null=True)),
                ('purchase', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('discount_value', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_purchase_discount', to='Business.business')),
                ('discount_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discountproduct_purchase_discount', to='Product.product')),
                ('discount_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discountservice_purchase_discount', to='Service.service')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_purchase_discount', to='Product.product')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_purchase_discount', to='Service.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_purchase_discount', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
