# Generated by Django 4.0.6 on 2023-12-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TragetControl', '0001_initial_squashed_0008_alter_retailtarget_brand_target_and_more'),
        ('Client', '0001_initial_squashed_0074_client_is_image_uploaded_s3'),
        ('Product', '0001_initial_squashed_0053_brand_is_image_uploaded_s3_and_more'),
        ('Service', '0001_initial_squashed_0032_alter_service_initial_deposit_alter_service_price'),
        ('Promotions', '0003_coupon_coupondetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='brands',
            field=models.ManyToManyField(null=True, related_name='coupons_brand', to='Product.brand'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='client',
            field=models.ManyToManyField(null=True, related_name='coupons_client', to='Client.client'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_service_group',
            field=models.ManyToManyField(null=True, related_name='coupons_service_group', to='Service.servicegroup'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupons_service',
            field=models.ManyToManyField(null=True, related_name='coupons_service', to='Service.service'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='excluded_product',
            field=models.ManyToManyField(null=True, related_name='coupons_product', to='Product.product'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='store_target',
            field=models.ManyToManyField(null=True, related_name='coupons_brand', to='TragetControl.storetarget'),
        ),
    ]
