# Generated by Django 3.2.15 on 2023-01-11 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Promotions', '0004_purchasediscount_servicegroupdiscount_specificgroupdiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockdate',
            name='specificgroupdiscount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specificgroupdiscount_blockdate', to='Promotions.specificgroupdiscount'),
        ),
        migrations.AddField(
            model_name='daterestrictions',
            name='specificgroupdiscount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specificgroupdiscount_daterestrictions', to='Promotions.specificgroupdiscount'),
        ),
        migrations.AddField(
            model_name='dayrestrictions',
            name='specificgroupdiscount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specificgroupdiscount_dayrestrictions', to='Promotions.specificgroupdiscount'),
        ),
        migrations.AlterField(
            model_name='blockdate',
            name='directorflat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directorflat_blockdate', to='Promotions.directorflatdiscount'),
        ),
        migrations.AlterField(
            model_name='daterestrictions',
            name='directorflat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directorflat_daterestrictions', to='Promotions.directorflatdiscount'),
        ),
    ]
