# Generated by Django 4.0.6 on 2023-12-23 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Promotions', '0004_coupon_brands_coupon_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='client',
            new_name='clients',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='coupon_service_group',
            new_name='coupon_service_groups',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='coupons_service',
            new_name='coupons_services',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='excluded_product',
            new_name='excluded_products',
        ),
    ]
