# Generated by Django 3.2.15 on 2023-01-11 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Promotions', '0005_auto_20230111_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayrestrictions',
            name='directorflat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directorflat_dayrestrictions', to='Promotions.directorflatdiscount'),
        ),
    ]
