# Generated by Django 4.0.6 on 2023-12-23 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Promotions', '0006_coupon_coupon_type_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponBlockDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.TextField(blank=True, null=True)),
                ('coupon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_blockdays', to='Promotions.coupon')),
            ],
        ),
    ]
