# Generated by Django 3.2.15 on 2023-01-12 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0024_priceservice_currency'),
        ('Product', '0041_productorderstockreport_reorder_quantity'),
        ('Promotions', '0006_alter_dayrestrictions_directorflat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasediscount',
            name='discount_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discountproduct_purchase_discount', to='Product.product'),
        ),
        migrations.AlterField(
            model_name='purchasediscount',
            name='discount_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discountservice_purchase_discount', to='Service.service'),
        ),
        migrations.AlterField(
            model_name='purchasediscount',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_purchase_discount', to='Product.product'),
        ),
        migrations.AlterField(
            model_name='purchasediscount',
            name='select_type',
            field=models.CharField(choices=[('Service', 'Service'), ('Product', 'Product')], default='Product', max_length=50),
        ),
        migrations.AlterField(
            model_name='purchasediscount',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_purchase_discount', to='Service.service'),
        ),
    ]
