# Generated by Django 4.0.6 on 2023-12-23 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Promotions', '0007_couponblockdays'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couponblockdays',
            old_name='days',
            new_name='day',
        ),
    ]
