# Generated by Django 3.2.15 on 2023-01-12 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Promotions', '0007_auto_20230112_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockdate',
            name='purchasediscount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchasediscount_blockdate', to='Promotions.purchasediscount'),
        ),
        migrations.AddField(
            model_name='daterestrictions',
            name='purchasediscount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchasediscount_daterestrictions', to='Promotions.purchasediscount'),
        ),
        migrations.AddField(
            model_name='dayrestrictions',
            name='purchasediscount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchasediscount_dayrestrictions', to='Promotions.purchasediscount'),
        ),
    ]
