# Generated by Django 3.2.15 on 2023-01-12 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0028_businessaddress_description'),
        ('Service', '0024_priceservice_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Product', '0041_productorderstockreport_reorder_quantity'),
        ('Promotions', '0008_auto_20230112_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpendDiscount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('spend_amount', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('select_type', models.CharField(choices=[('Service', 'Service'), ('Product', 'Product')], default='Service', max_length=50)),
                ('discount_value', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_spend_discount', to='Business.business')),
                ('discount_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discountproduct_spend_discount', to='Product.product')),
                ('discount_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discountservice_spend_discount', to='Service.service')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_spend_discount', to='Service.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_spend_discount', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
