# Generated by Django 4.0.6 on 2023-12-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0002_businessaddress_privacy_policy'),
        ('Promotions', '0008_rename_days_couponblockdays_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='amount_spent',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='business',
            field=models.ManyToManyField(null=True, related_name='coupons_Business', to='Business.business'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discounted_percentage',
            field=models.TextField(null=True),
        ),
    ]
