# Generated by Django 3.2.15 on 2023-01-13 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0024_priceservice_currency'),
        ('Product', '0041_productorderstockreport_reorder_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Business', '0028_businessaddress_description'),
        ('Promotions', '0009_spenddiscount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificBrand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('discount_brand', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('discount_service_group', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_specific_brand', to='Product.brand')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_specific_brand', to='Business.business')),
                ('servicegroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicegroup_specific_brand', to='Service.servicegroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_specific_brand', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='blockdate',
            name='specificbrand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specificbrand_blockdate', to='Promotions.specificbrand'),
        ),
        migrations.AddField(
            model_name='daterestrictions',
            name='specificbrand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specificbrand_daterestrictions', to='Promotions.specificbrand'),
        ),
        migrations.AddField(
            model_name='dayrestrictions',
            name='specificbrand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specificbrand_dayrestrictions', to='Promotions.specificbrand'),
        ),
    ]
