# Generated by Django 4.0.6 on 2023-12-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Promotions', '0009_coupon_amount_spent_coupon_business_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discounted_percentage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
