# Generated by Django 4.0.6 on 2023-12-25 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial_squashed_0053_brand_is_image_uploaded_s3_and_more'),
        ('Service', '0001_initial_squashed_0032_alter_service_initial_deposit_alter_service_price'),
        ('Promotions', '0010_alter_coupon_discounted_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='amount_spent',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discounted_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='CouponServiceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_group_discount', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Promotions.coupon')),
                ('service_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service.servicegroup')),
            ],
            options={
                'unique_together': {('coupon', 'service_group')},
            },
        ),
        migrations.CreateModel(
            name='CouponBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_discount', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.brand')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Promotions.coupon')),
            ],
            options={
                'unique_together': {('coupon', 'brand')},
            },
        ),
    ]
