# Generated by Django 3.2.15 on 2023-01-16 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Promotions', '0010_auto_20230113_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockdate',
            name='spenddiscount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spenddiscount_blockdate', to='Promotions.spenddiscount'),
        ),
        migrations.AddField(
            model_name='daterestrictions',
            name='spenddiscount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spenddiscount_daterestrictions', to='Promotions.spenddiscount'),
        ),
        migrations.AddField(
            model_name='dayrestrictions',
            name='spenddiscount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spenddiscount_dayrestrictions', to='Promotions.spenddiscount'),
        ),
    ]
