# Generated by Django 4.0.6 on 2023-12-25 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Promotions', '0011_couponbrand_alter_coupon_brands_couponbrand_coupon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponbrand',
            name='brand_discount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='couponservicegroup',
            name='service_group_discount',
            field=models.FloatField(null=True),
        ),
    ]
