# Generated by Django 3.2.15 on 2023-01-17 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0024_priceservice_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Business', '0028_businessaddress_description'),
        ('Promotions', '0011_auto_20230116_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorflatdiscount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_directorflatdiscount', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SpendSomeAmount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('spend_amount', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_spendsomeamount', to='Business.business')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_spendsomeamount', to='Service.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_spendsomeamount', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='blockdate',
            name='spendsomeamount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spendsomeamount_blockdate', to='Promotions.spendsomeamount'),
        ),
        migrations.AddField(
            model_name='daterestrictions',
            name='spendsomeamount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spendsomeamount_daterestrictions', to='Promotions.spendsomeamount'),
        ),
        migrations.AddField(
            model_name='dayrestrictions',
            name='spendsomeamount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spendsomeamount_dayrestrictions', to='Promotions.spendsomeamount'),
        ),
    ]
