# Generated by Django 4.0.6 on 2023-12-25 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Promotions', '0011_alter_coupon_amount_spent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponbrand',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliable_coupon_brand', to='Promotions.coupon'),
        ),
    ]
