# Generated by Django 4.0.6 on 2023-12-25 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Promotions', '0012_alter_couponbrand_brand_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='amount_spent',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discounted_percentage',
            field=models.FloatField(null=True),
        ),
    ]
