# Generated by Django 4.0.6 on 2023-12-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0002_businessaddress_privacy_policy'),
        ('Promotions', '0013_alter_couponbrand_brand_alter_couponbrand_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='store_target',
            field=models.ManyToManyField(null=True, related_name='coupons_brand_target', to='Business.businessaddress'),
        ),
    ]
