# Generated by Django 4.0.6 on 2023-12-25 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial_squashed_0053_brand_is_image_uploaded_s3_and_more'),
        ('Promotions', '0014_remove_coupon_brands'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='brands',
            field=models.ManyToManyField(null=True, related_name='coupons_brand', to='Product.brand'),
        ),
    ]
