# Generated by Django 3.2.15 on 2023-01-18 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0024_priceservice_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Business', '0028_businessaddress_description'),
        ('Promotions', '0014_auto_20230117_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedPriceService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('spend_amount', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('duration', models.CharField(default='', max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_fixedpriceservice', to='Business.business')),
                ('service', models.ManyToManyField(blank=True, null=True, related_name='service_fixedpriceservice', to='Service.Service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_fixedpriceservice', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
