# Generated by Django 4.0.6 on 2023-12-25 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Promotions', '0014_alter_coupon_store_target'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='store_target',
            new_name='locations',
        ),
    ]
