# Generated by Django 3.2.15 on 2023-01-18 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Promotions', '0015_fixedpriceservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockdate',
            name='fixedpriceservice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixedpriceservice_blockdate', to='Promotions.fixedpriceservice'),
        ),
        migrations.AddField(
            model_name='daterestrictions',
            name='fixedpriceservice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixedpriceservice_daterestrictions', to='Promotions.fixedpriceservice'),
        ),
        migrations.AddField(
            model_name='dayrestrictions',
            name='fixedpriceservice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixedpriceservice_dayrestrictions', to='Promotions.fixedpriceservice'),
        ),
    ]
