# Generated by Django 4.0.6 on 2023-12-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Promotions', '0016_coupon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='status',
            field=models.TextField(null=True),
        ),
    ]
