# Generated by Django 4.0.6 on 2023-12-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Promotions', '0017_coupon_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='status',
            field=models.TextField(default='active'),
        ),
    ]
