# Generated by Django 4.0.6 on 2023-12-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Promotions', '0018_alter_coupon_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
