# Generated by Django 4.0.6 on 2023-12-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Promotions', '0018_alter_coupon_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='requested_status',
            field=models.BooleanField(default=True),
        ),
    ]
