# Generated by Django 3.2.15 on 2023-01-20 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Promotions', '0019_productandgetspecific_retailandgetservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockdate',
            name='retailandservice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retailandservice_blockdate', to='Promotions.retailandgetservice'),
        ),
        migrations.AddField(
            model_name='daterestrictions',
            name='retailandservice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retailandservice_daterestrictions', to='Promotions.retailandgetservice'),
        ),
        migrations.AddField(
            model_name='dayrestrictions',
            name='retailandservice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retailandservice_dayrestrictions', to='Promotions.retailandgetservice'),
        ),
    ]
