# Generated by Django 4.0.6 on 2023-12-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Promotions', '0019_coupon_requested_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
