# Generated by Django 3.2.15 on 2023-01-21 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0028_businessaddress_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Promotions', '0020_auto_20230120_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRestrictedDiscount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('corporate_type', models.CharField(choices=[('All_Service', 'All Service'), ('Retail_Product', 'Retail Product')], default='All_Service', max_length=50)),
                ('discount_percentage', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_userrestricteddiscount', to='Business.business')),
                ('user', models.ManyToManyField(related_name='user_userrestricteddiscount', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
