# Generated by Django 4.0.6 on 2023-12-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Promotions', '0020_alter_coupon_end_date_alter_coupon_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='buy_one_type',
            field=models.TextField(null=True),
        ),
    ]
