# Generated by Django 3.2.15 on 2023-01-21 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0035_alter_client_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Promotions', '0021_userrestricteddiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrestricteddiscount',
            name='client',
            field=models.ManyToManyField(related_name='client_userrestricteddiscount', to='Client.Client'),
        ),
        migrations.RemoveField(
            model_name='userrestricteddiscount',
            name='user',
        ),
        migrations.AddField(
            model_name='userrestricteddiscount',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_userrestricteddiscount', to=settings.AUTH_USER_MODEL),
        ),
    ]
