# Generated by Django 3.2.15 on 2023-01-21 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Promotions', '0022_auto_20230121_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockdate',
            name='userrestricteddiscount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userrestricteddiscount_blockdate', to='Promotions.userrestricteddiscount'),
        ),
        migrations.AddField(
            model_name='daterestrictions',
            name='userrestricteddiscount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userrestricteddiscount_daterestrictions', to='Promotions.userrestricteddiscount'),
        ),
        migrations.AddField(
            model_name='dayrestrictions',
            name='userrestricteddiscount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userrestricteddiscount_dayrestrictions', to='Promotions.userrestricteddiscount'),
        ),
    ]
