# Generated by Django 4.0.6 on 2023-12-26 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Promotions', '0023_couponbrand_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='coupons_services',
            new_name='excluded_services',
        ),
    ]
