# Generated by Django 3.2.15 on 2023-01-23 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0028_businessaddress_description'),
        ('Service', '0024_priceservice_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Promotions', '0023_auto_20230121_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountOnFreeService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('discount_percentage', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('discount_duration', models.CharField(blank=True, choices=[('Next 1 visit', 'Next 1 visit'), ('Next 2 visit', 'Next 2 visit'), ('Next 3 visit', 'Next 3 visit'), ('Next 4 visit', 'Next 4 visit'), ('Next 5 visit', 'Next 5 visit'), ('Next 6 visit', 'Next 6 visit'), ('Next 7 visit', 'Next 7 visit'), ('Next 8 visit', 'Next 8 visit'), ('Next 9 visit', 'Next 9 visit'), ('Next 10 visit', 'Next 10 visit')], default='Next 1 visit', max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('service', models.ManyToManyField(blank=True, null=True, related_name='service_discountonfreeservice', to='Service.Service')),
            ],
        ),
        migrations.CreateModel(
            name='ComplimentaryDiscount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_complimentrydiscount', to='Business.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_complimentrydiscount', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
