# Generated by Django 4.0.6 on 2023-12-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Promotions', '0024_rename_coupons_services_coupon_excluded_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='client_type',
            field=models.TextField(null=True),
        ),
    ]
