# Generated by Django 3.2.15 on 2023-01-23 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0024_priceservice_currency'),
        ('Promotions', '0024_complimentarydiscount_discountonfreeservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockdate',
            name='complimentary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complimentary_blockdate', to='Promotions.complimentarydiscount'),
        ),
        migrations.AddField(
            model_name='daterestrictions',
            name='complimentary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complimentary_daterestrictions', to='Promotions.complimentarydiscount'),
        ),
        migrations.AddField(
            model_name='dayrestrictions',
            name='complimentary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complimentary_dayrestrictions', to='Promotions.complimentarydiscount'),
        ),
        migrations.AddField(
            model_name='discountonfreeservice',
            name='complimentary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complimentary_discountonfreeservice', to='Promotions.complimentarydiscount'),
        ),
        migrations.RemoveField(
            model_name='discountonfreeservice',
            name='service',
        ),
        migrations.AddField(
            model_name='discountonfreeservice',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_discountonfreeservice', to='Service.service'),
        ),
    ]
