# Generated by Django 4.0.6 on 2023-12-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Promotions', '0025_coupon_client_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='client_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
