# Generated by Django 4.0.6 on 2023-12-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Promotions', '0026_alter_coupon_client_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='usage_limit',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='user_limit',
            field=models.FloatField(null=True),
        ),
    ]
