# Generated by Django 3.2.15 on 2023-01-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0024_priceservice_currency'),
        ('Promotions', '0026_auto_20230125_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedurationforspecifictime',
            name='service',
        ),
        migrations.AddField(
            model_name='servicedurationforspecifictime',
            name='service',
            field=models.ManyToManyField(blank=True, null=True, related_name='service_servicedurationspecifictime', to='Service.Service'),
        ),
    ]
