# Generated by Django 4.0.6 on 2023-05-02 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0045_product_product_size'),
        ('Promotions', '0027_auto_20230125_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicegroupdiscount',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_specificgroupdiscount', to='Product.brand'),
        ),
        migrations.AddField(
            model_name='servicegroupdiscount',
            name='brand_discount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
