# Generated by Django 4.0.6 on 2023-05-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Promotions', '0028_servicegroupdiscount_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productandgetspecific',
            name='promotion_type',
            field=models.CharField(choices=[('Brand', 'Brand'), ('Product', 'Product')], default='Product', max_length=20),
        ),
    ]
