# Generated by Django 4.0.6 on 2023-05-04 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0045_product_product_size'),
        ('Promotions', '0029_productandgetspecific_promotion_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productandgetspecific',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_productandgetspecific', to='Product.brand'),
        ),
    ]
