# Generated by Django 4.0.6 on 2023-05-11 12:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Promotions', '0031_bundlefixed_promotion_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionExcludedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('object_type', models.CharField(choices=[('Direct Or Flat', 'Direct Or Flat'), ('Specific Group Discount', 'Specific Group Discount'), ('Purchase Discount', 'Purchase Discount'), ('Specific Brand Discount', 'Specific Brand Discount'), ('Spend_Some_Amount', 'Spend_Some_Amount'), ('Fixed_Price_Service', 'Fixed_Price_Service'), ('Mentioned_Number_Service', 'Mentioned_Number_Service'), ('Bundle_Fixed_Service', 'Bundle_Fixed_Service'), ('Retail_and_Get_Service', 'Retail_and_Get_Service'), ('User_Restricted_discount', 'User_Restricted_discount'), ('Complimentary_Discount', 'Complimentary_Discount'), ('Packages_Discount', 'Packages_Discount')], default='', max_length=800)),
                ('object_id', models.CharField(default='', max_length=800)),
                ('excluded_type', models.CharField(choices=[('Product', 'Product'), ('Service', 'Service'), ('Voucher', 'Voucher')], default='', max_length=100)),
                ('excluded_id', models.CharField(default='', max_length=800)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
