# Generated by Django 4.0.6 on 2023-08-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Promotions', '0032_promotionexcludeditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundlefixed',
            name='spend_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='categorydiscount',
            name='discount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='discountonfreeservice',
            name='discount_percentage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fixedpriceservice',
            name='spend_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='purchasediscount',
            name='discount_value',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='purchasediscount',
            name='purchase',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='servicedurationforspecifictime',
            name='total_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='servicegroupdiscount',
            name='brand_discount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='servicegroupdiscount',
            name='discount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='specificbrand',
            name='discount_brand',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='specificbrand',
            name='discount_service_group',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='spenddiscount',
            name='discount_value',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='spenddiscount',
            name='spend_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='spendsomeamountandgetdiscount',
            name='spend_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userrestricteddiscount',
            name='discount_percentage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
