# Generated by Django 4.0.6 on 2024-02-02 12:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0003_productstock_refund_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(default='', max_length=999)),
                ('deal_type', models.CharField(choices=[('Fixed Amount Discount Deal', 'Fixed Amount Discount Deal'), ('Percentage Discount Deal', 'Percentage Discount Deal'), ('Buy one or more item get one or more free/discount', 'Buy one or more item get one or more free/discount'), ('Complimentary Voucher', 'Complimentary Voucher'), ('Custom Package', 'Custom Package'), ('Get free item when user purchase specific items in given period', 'Get free item when user purchase specific items in given period'), ('Spend some amount and get some item free', 'Spend some amount and get some item free'), ('Fixed price items deal', 'Fixed price items deal')], default='Fixed Amount Discount Deal', max_length=999)),
                ('audience', models.CharField(choices=[('Public', 'public'), ('Pre Set Customer', 'pre-set-users')], default='public', max_length=999)),
                ('codeGeneration', models.CharField(choices=[('unique', 'unique'), ('generic', 'generic')], default='unique', max_length=999)),
                ('customerType', models.CharField(choices=[('any', 'any'), ('lead', 'lead'), ('new', 'new'), ('regular', 'regular'), ('lapsed', 'lapsed')], default='any', max_length=999)),
                ('usageLimitType', models.CharField(choices=[('unlimited', 'unlimited'), ('limited', 'limited')], default='limited', max_length=999)),
                ('validityPeriodType', models.CharField(choices=[('From deal start date to end date', 'from-start-to-end-date'), ('Days from deal activation date', 'days-from-start-date'), ('Months from deal activation date', 'months-from-start-date'), ('Years from deal activation date', 'years-from-start-date')], default='from-start-to-end-date', max_length=999)),
                ('minimumSpend', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('code', models.CharField(default='', max_length=999)),
                ('status', models.CharField(default='', max_length=999)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('brand', models.ManyToManyField(to='Product.brand')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_category', to='Deal.dealcategory')),
            ],
        ),
    ]
