# Generated by Django 4.0.6 on 2024-02-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='audience',
            field=models.CharField(choices=[('public', 'public'), ('pre-set-users', 'pre-set-users')], default='public', max_length=999),
        ),
        migrations.AlterField(
            model_name='deal',
            name='endDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='validityPeriodType',
            field=models.CharField(choices=[('from-start-to-end-date', 'from-start-to-end-date'), ('days-from-start-date', 'days-from-start-date'), ('months-from-start-date', 'months-from-start-date'), ('years-from-start-date', 'years-from-start-date')], default='from-start-to-end-date', max_length=999),
        ),
    ]
