# Generated by Django 4.0.6 on 2024-02-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deal', '0002_alter_deal_audience_alter_deal_enddate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedeemableChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=999)),
            ],
        ),
        migrations.AddField(
            model_name='deal',
            name='redeemableChannels',
            field=models.ManyToManyField(to='Deal.redeemablechannel'),
        ),
    ]
