# Generated by Django 4.0.6 on 2024-02-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deal', '0003_redeemablechannel_deal_redeemablechannels'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='minimumSpendOn',
            field=models.CharField(default='all', max_length=999),
        ),
        migrations.AddField(
            model_name='deal',
            name='typeId',
            field=models.CharField(default='', max_length=999),
        ),
        migrations.AddField(
            model_name='deal',
            name='usagePerCustomer',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deal',
            name='validPeriod',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
