# Generated by Django 4.0.6 on 2024-02-06 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0008_delete_refundsetting'),
        ('Product', '0003_productstock_refund_quantity'),
        ('Service', '0003_servicegroup_image_servicegroup_is_image_uploaded_s3'),
        ('Deal', '0004_deal_minimumspendon_deal_typeid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='deal',
            name='terms',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='DealRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_dates', models.ManyToManyField(to='Deal.dealdate')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_restrictions', to='Deal.deal')),
                ('excluded_locations', models.ManyToManyField(to='Business.businessaddress')),
                ('excluded_products', models.ManyToManyField(to='Product.product')),
                ('excluded_services', models.ManyToManyField(to='Service.service')),
            ],
        ),
        migrations.CreateModel(
            name='DealMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='business/deals/images/')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_medias', to='Deal.deal')),
            ],
        ),
        migrations.CreateModel(
            name='DealDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(default='', max_length=999)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_days', to='Deal.deal')),
            ],
        ),
    ]
