# Generated by Django 4.0.6 on 2024-02-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deal', '0006_alter_dealrestriction_block_dates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(default='Draft', max_length=999),
        ),
    ]
