# Generated by Django 4.0.6 on 2023-12-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial_squashed_0074_client_is_image_uploaded_s3'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_tag',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
