# Generated by Django 3.2.15 on 2022-09-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_alter_client_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='card_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
    ]
