# Generated by Django 3.2.15 on 2022-09-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_auto_20220901_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='client/client_images/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
