# Generated by Django 4.0.6 on 2024-01-25 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_clientimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientimages',
            old_name='file_name',
            new_name='name',
        ),
    ]
