# Generated by Django 3.2.15 on 2022-09-01 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Business', '0013_auto_20220901_1433'),
        ('Client', '0004_auto_20220901_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(default='', max_length=254)),
                ('name', models.CharField(default='', max_length=300)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_client_group', to='Business.business')),
                ('client', models.ManyToManyField(related_name='group_clients', to='Client.Client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_client_group', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
