# Generated by Django 4.0.6 on 2024-01-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0006_comments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchers',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
