# Generated by Django 4.0.6 on 2024-01-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0007_vouchers_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchers',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
