# Generated by Django 4.0.6 on 2022-09-12 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0008_rewards'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rewards',
        ),
    ]
