# Generated by Django 5.0.2 on 2024-02-10 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0008_alter_vouchers_end_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
