# Generated by Django 4.0.6 on 2022-09-13 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Product', '0014_productmedia_is_cover'),
        ('Business', '0017_alter_adminnotificationsetting_sms_notify_for_daily_book_and_more'),
        ('Service', '0001_initial'),
        ('Client', '0009_delete_rewards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('reward_value', models.PositiveIntegerField(default=0)),
                ('reward_point', models.PositiveIntegerField(default=0)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_reward', to='Business.business')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_rewards', to='Product.product')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_rewards', to='Service.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reward', to=settings.AUTH_USER_MODEL, verbose_name='Creator ( User )')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('promotion_type', models.CharField(choices=[('Product', 'Product'), ('Service', 'Service')], default='Service', max_length=20)),
                ('services', models.PositiveIntegerField(default=0, verbose_name='No. of Services')),
                ('products', models.PositiveIntegerField(default=0, verbose_name='No. of Products')),
                ('discount', models.PositiveIntegerField(default=0)),
                ('duration', models.CharField(choices=[('Day', 'Day'), ('Month', 'Month')], default='Month', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_promotions', to='Business.business')),
                ('discount_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_product_promotions', to='Product.product')),
                ('discount_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_service_promotions', to='Service.service')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_promotions', to='Product.product')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_promotions', to='Service.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_promotions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('session', models.PositiveIntegerField(default=0)),
                ('valid_for', models.CharField(choices=[('Days', 'Days'), ('Months', 'Months')], default='Months', max_length=20, verbose_name='Validity for Days or Months')),
                ('days', models.PositiveIntegerField(default=0, verbose_name='No. of Days')),
                ('months', models.PositiveIntegerField(default=0, verbose_name='No. of Months')),
                ('price', models.PositiveIntegerField(default=0)),
                ('tax_rate', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(choices=[('Red', 'Red'), ('Purple', 'Purple'), ('Black', 'Black'), ('White', 'White'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Pink', 'Pink'), ('Gray', 'Gray'), ('DarkGray', 'DarkGray'), ('Blue', 'Blue'), ('Golden', 'Golden'), ('Green', 'Green'), ('Brown', 'Brown'), ('SkyBlue', 'SkyBlue'), ('DarkBlue', 'DarkBlue')], default='White', max_length=30)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_memberships', to='Business.business')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_memberships', to='Service.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
