# Generated by Django 4.0.6 on 2024-03-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0009_delete_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_installment',
            field=models.BooleanField(default=False),
        ),
    ]
