# Generated by Django 3.2.15 on 2022-09-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0010_rewards_promotion_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewards',
            name='reward_type',
            field=models.CharField(choices=[('Product', 'Product'), ('Service', 'Service')], default='Product', max_length=20),
        ),
    ]
