# Generated by Django 3.2.15 on 2022-09-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0011_rewards_reward_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='products',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='No. of Products'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='services',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='No. of Services'),
        ),
    ]
