# Generated by Django 3.2.15 on 2022-09-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0012_auto_20220913_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='days',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='No. of Days'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='months',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='No. of Months'),
        ),
    ]
