# Generated by Django 3.2.15 on 2022-09-15 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0017_alter_adminnotificationsetting_sms_notify_for_daily_book_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Product', '0014_productmedia_is_cover'),
        ('Service', '0002_alter_service_business'),
        ('Client', '0013_auto_20220913_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vouchers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('value', models.PositiveIntegerField(default=0)),
                ('valid_for', models.CharField(choices=[('Days', 'Days'), ('Months', 'Months')], default='Months', max_length=20, verbose_name='Validity for Days or Months')),
                ('days', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='No. of Days')),
                ('months', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='No. of Months')),
                ('sales', models.PositiveIntegerField(default=0)),
                ('price', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_voucher', to='Business.business')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_voucher', to='Product.product')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_voucher', to='Service.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_voucher', to=settings.AUTH_USER_MODEL, verbose_name='Creator ( User )')),
            ],
        ),
    ]
