# Generated by Django 4.0.6 on 2022-09-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0016_subscription_subscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='products_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Number of Products'),
        ),
    ]
