# Generated by Django 4.0.6 on 2022-09-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0018_auto_20220922_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='duration',
        ),
        migrations.AddField(
            model_name='promotion',
            name='valid_til',
            field=models.DateField(blank=True, null=True),
        ),
    ]
