# Generated by Django 3.2.15 on 2022-09-23 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0019_remove_promotion_duration_promotion_valid_til'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='discount_product',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='discount_service',
        ),
    ]
