# Generated by Django 3.2.15 on 2022-09-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0020_auto_20220923_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vouchers',
            name='days',
        ),
        migrations.RemoveField(
            model_name='vouchers',
            name='months',
        ),
        migrations.AddField(
            model_name='vouchers',
            name='validity',
            field=models.PositiveIntegerField(default=0, verbose_name='No of Days/Month'),
        ),
    ]
