# Generated by Django 4.0.6 on 2022-09-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0022_auto_20220927_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership',
            field=models.CharField(choices=[('Product', 'Product'), ('Service', 'Service')], default='Product', max_length=30, verbose_name='Membership_type'),
        ),
    ]
