# Generated by Django 3.2.15 on 2022-09-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0023_alter_membership_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='days',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='months',
        ),
        migrations.AddField(
            model_name='membership',
            name='validity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='No. of Validity Days/Month'),
        ),
    ]
