# Generated by Django 3.2.15 on 2022-09-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0024_auto_20220928_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='select_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
