# Generated by Django 3.2.15 on 2022-10-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0025_alter_subscription_select_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vouchers',
            name='valid_for',
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='validity',
            field=models.CharField(choices=[('Days', 'Days'), ('Months', 'Months')], default='7 Days', max_length=100, verbose_name='No of Days/Month'),
        ),
    ]
