# Generated by Django 3.2.15 on 2022-11-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0028_alter_promotion_valid_til'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='discount',
            field=models.CharField(choices=[('Unlimited', 'Unlimited'), ('Limited', 'Limited')], default='Unlimited', max_length=20, verbose_name='Discount Limit'),
        ),
        migrations.AddField(
            model_name='membership',
            name='percentage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='valid_til',
            field=models.CharField(blank=True, choices=[('7 Days', '7 Days'), ('14 Days', '14 Days'), ('1 Month', '1 Months'), ('2 Months', '2 Months'), ('3 Months', '3 Months'), ('4 Months', '4 Months'), ('6 Months', '6 Months'), ('8 Months', '8 Months'), ('1 Years', '1 Years'), ('18 Months', '18 Months'), ('2 Years', '2 Years'), ('5 Years', '5 Years')], default='7 Days', max_length=100, null=True, verbose_name='No of Days/Month'),
        ),
    ]
