# Generated by Django 3.2.15 on 2022-11-02 11:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0019_servicegroup'),
        ('Product', '0023_productstock_product_unit'),
        ('Client', '0029_auto_20221101_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='product',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='service',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='total_number',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='validity',
        ),
        migrations.AddField(
            model_name='membership',
            name='color',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='membership',
            name='term_condition',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='valid_for',
            field=models.CharField(choices=[('7 Days', '7 Days'), ('14 Days', '14 Days'), ('1 Month', '1 Months'), ('2 Months', '2 Months'), ('3 Months', '3 Months'), ('4 Months', '4 Months'), ('6 Months', '6 Months'), ('8 Months', '8 Months'), ('1 Years', '1 Years'), ('18 Months', '18 Months'), ('2 Years', '2 Years'), ('5 Years', '5 Years')], default='7 Days', max_length=20, verbose_name='Validity for Days or Months'),
        ),
        migrations.CreateModel(
            name='DiscountMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('discount', models.CharField(choices=[('7 Days', '7 Days'), ('14 Days', '14 Days'), ('1 Month', '1 Month')], default='7 Days', max_length=50, verbose_name='Duration')),
                ('percentage', models.PositiveIntegerField(default=0)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_discountmembership', to='Client.membership')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_memberships', to='Product.product')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_memberships', to='Service.service')),
            ],
        ),
    ]
