# Generated by Django 3.2.15 on 2022-11-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0030_auto_20221102_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discountmembership',
            old_name='discount',
            new_name='duration',
        ),
        migrations.AlterField(
            model_name='membership',
            name='discount',
            field=models.CharField(choices=[('Unlimited', 'Unlimited'), ('Free', 'Free')], default='Unlimited', max_length=20, verbose_name='Discount Limit'),
        ),
    ]
