# Generated by Django 3.2.15 on 2022-11-14 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Utility', '0012_auto_20221015_1633'),
        ('Client', '0031_auto_20221108_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='about_us',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Twitter', 'Twitter'), ('Whatsapp', 'Whatsapp'), ('Community', 'Community'), ('Media_Ads', 'Media Ads'), ('Friends', 'Friends')], default='Community', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='customer_note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer Note'),
        ),
        migrations.AddField(
            model_name='client',
            name='language',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='language_clients', to='Utility.language'),
        ),
        migrations.AddField(
            model_name='client',
            name='marketing',
            field=models.CharField(choices=[('opt_in', 'opt_in'), ('opt_out', 'opt_out')], default='opt_in', max_length=50),
        ),
    ]
