# Generated by Django 3.2.18 on 2023-02-27 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Service', '0024_priceservice_currency'),
        ('Business', '0028_businessaddress_description'),
        ('Promotions', '0027_auto_20230125_1328'),
        ('Client', '0035_alter_client_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPromotions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visits', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_client_promotions', to='Business.business')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_client_promotions', to='Client.client')),
                ('complimentary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complimentry_client_promotions', to='Promotions.complimentarydiscount')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_client_promotions', to='Service.service')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_client_promotions', to=settings.AUTH_USER_MODEL, verbose_name='Creator ( User )')),
            ],
        ),
    ]
