# Generated by Django 3.2.18 on 2023-03-10 05:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Utility', '0013_turnoverproductrecord'),
        ('Client', '0038_auto_20230308_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyPriceMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Utility.currency')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_currenypricemembership', to='Client.membership')),
            ],
        ),
    ]
