# Generated by Django 3.2.18 on 2023-03-10 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0039_currencypricemembership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='price',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='tax_rate',
        ),
    ]
