# Generated by Django 3.2.18 on 2023-03-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0041_remove_membership_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountmembership',
            name='duration',
            field=models.CharField(blank=True, choices=[('7 Days', '7 Days'), ('14 Days', '14 Days'), ('1 Month', '1 Month')], default='7 Days', max_length=50, null=True, verbose_name='Duration'),
        ),
    ]
