# Generated by Django 3.2.18 on 2023-03-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0042_alter_discountmembership_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='discount',
            field=models.CharField(choices=[('Limited', 'Limited'), ('Free', 'Free')], default='Unlimited', max_length=20, verbose_name='Discount Limit'),
        ),
    ]
