# Generated by Django 3.2.18 on 2023-03-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0043_alter_membership_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='valid_for',
            field=models.CharField(choices=[('7 Days', '7 Days'), ('14 Days', '14 Days'), ('1 Months', '1 Months'), ('2 Months', '2 Months'), ('3 Months', '3 Months'), ('4 Months', '4 Months'), ('6 Months', '6 Months'), ('8 Months', '8 Months'), ('1 Years', '1 Years'), ('18 Months', '18 Months'), ('2 Years', '2 Years'), ('5 Years', '5 Years')], default='7 Days', max_length=20, verbose_name='Validity for Days or Months'),
        ),
    ]
