# Generated by Django 3.2.18 on 2023-03-14 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0044_alter_membership_valid_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vouchers',
            name='value',
        ),
    ]
