# Generated by Django 4.0.6 on 2023-04-12 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0028_businessaddress_description'),
        ('Client', '0046_alter_vouchers_validity'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltypoints',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_loyaltypoints', to='Business.businessaddress'),
        ),
    ]
