# Generated by Django 4.0.6 on 2023-04-17 10:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0047_loyaltypoints_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyPointLogs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('loyalty_points', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('total_earn', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_loyaltypointlogs', to='Client.client')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_loyaltypointlogs', to='Client.loyaltypoints')),
            ],
        ),
    ]
