# Generated by Django 4.0.6 on 2023-04-18 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0028_businessaddress_description'),
        ('Client', '0049_clientloyaltypoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientloyaltypoint',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_client_loyalty_points', to='Business.businessaddress'),
        ),
        migrations.AlterField(
            model_name='loyaltypointlogs',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_loyaltypointlogs', to='Business.businessaddress'),
        ),
    ]
