# Generated by Django 4.0.6 on 2023-04-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0050_alter_clientloyaltypoint_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientloyaltypoint',
            name='customer_will_get_amount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='a customer will get (this) amount'),
        ),
        migrations.AddField(
            model_name='clientloyaltypoint',
            name='for_every_points',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='For every (this) points'),
        ),
        migrations.AddField(
            model_name='clientloyaltypoint',
            name='total_amount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Number of Total Amount (Amount to Spend)'),
        ),
        migrations.AlterField(
            model_name='clientloyaltypoint',
            name='total_earn',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Total Number Of Points'),
        ),
    ]
