# Generated by Django 4.0.6 on 2023-04-19 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0051_clientloyaltypoint_customer_will_get_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loyaltypointlogs',
            old_name='loyalty_points',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='loyaltypointlogs',
            old_name='total_earn',
            new_name='points_earned',
        ),
        migrations.AddField(
            model_name='loyaltypointlogs',
            name='client_points',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_points_logs', to='Client.clientloyaltypoint'),
        ),
        migrations.AddField(
            model_name='loyaltypointlogs',
            name='loyalty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_points_logs', to='Client.loyaltypoints'),
        ),
        migrations.AddField(
            model_name='loyaltypointlogs',
            name='points_redeemed',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
