# Generated by Django 4.0.6 on 2023-04-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0052_rename_loyalty_points_loyaltypointlogs_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientloyaltypoint',
            name='points_redeemed',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Number Of Points Redeemed'),
        ),
    ]
