# Generated by Django 4.0.6 on 2023-05-01 11:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Utility', '0013_turnoverproductrecord'),
        ('Client', '0053_clientloyaltypoint_points_redeemed'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherCurrencyPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Utility.currency')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_vouchercurrencyprice', to='Client.vouchers')),
            ],
        ),
    ]
