# Generated by Django 4.0.6 on 2023-05-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0054_vouchercurrencyprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchers',
            name='discount_percentage',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
