# Generated by Django 4.0.6 on 2023-05-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0055_vouchers_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltypointlogs',
            name='actual_sale_value_redeemed',
            field=models.FloatField(default=0),
        ),
    ]
