# Generated by Django 4.0.6 on 2023-05-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0056_loyaltypointlogs_actual_sale_value_redeemed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientloyaltypoint',
            name='points_redeemed',
            field=models.FloatField(default=0, verbose_name='Total Number Of Points Redeemed'),
        ),
    ]
