# Generated by Django 4.0.6 on 2023-05-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0057_alter_clientloyaltypoint_points_redeemed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltypointlogs',
            name='points_redeemed',
            field=models.FloatField(default=0),
        ),
    ]
