# Generated by Django 4.0.6 on 2023-05-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0058_alter_loyaltypointlogs_points_redeemed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltypoints',
            name='earn_points',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
