# Generated by Django 4.0.6 on 2023-05-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0059_alter_loyaltypoints_earn_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientloyaltypoint',
            name='total_amount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Number of Total Amount (Amount to Spend)'),
        ),
        migrations.AlterField(
            model_name='clientloyaltypoint',
            name='total_earn',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Total Number Of Points'),
        ),
    ]
