# Generated by Django 4.0.6 on 2023-05-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0060_alter_clientloyaltypoint_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltypointlogs',
            name='points_earned',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
