# Generated by Django 4.0.6 on 2023-05-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0062_alter_loyaltypointlogs_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
