# Generated by Django 4.0.6 on 2023-06-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0064_loyaltypointlogs_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltypointlogs',
            name='checkout',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
