# Generated by Django 4.0.6 on 2023-06-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0066_alter_loyaltypoints_amount_spend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientloyaltypoint',
            name='customer_will_get_amount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='a customer will get (this) amount'),
        ),
    ]
