# Generated by Django 4.0.6 on 2023-06-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0067_alter_clientloyaltypoint_customer_will_get_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltypoints',
            name='total_earn_from_points',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
