# Generated by Django 4.0.6 on 2023-06-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0068_alter_loyaltypoints_total_earn_from_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltypoints',
            name='number_points',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
