# Generated by Django 4.0.6 on 2023-07-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0070_clientloyaltypoint_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='arabic_name',
            field=models.CharField(default='', max_length=999),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='arabic_name',
            field=models.CharField(default='', max_length=999),
        ),
    ]
