# Generated by Django 4.0.6 on 2023-08-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0071_membership_arabic_name_vouchers_arabic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencypricemembership',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='vouchercurrencyprice',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
