# Generated by Django 4.0.6 on 2023-08-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0072_alter_currencypricemembership_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountmembership',
            name='percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='membership',
            name='percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='purchases',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='No. of Purchases'),
        ),
        migrations.AlterField(
            model_name='rewards',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rewards',
            name='reward_point',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rewards',
            name='reward_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rewards',
            name='total_points',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.FloatField(default=0, verbose_name='Subscription Price'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='products_count',
            field=models.FloatField(default=0, verbose_name='Total Number of Products'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='select_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='services_count',
            field=models.FloatField(default=0, verbose_name='Total Number of Services'),
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='discount_percentage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='sales',
            field=models.FloatField(default=0),
        ),
    ]
