# Generated by Django 4.0.6 on 2023-08-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0073_alter_discountmembership_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_image_uploaded_s3',
            field=models.BooleanField(default=False),
        ),
    ]
