# Generated by Django 4.0.6 on 2024-01-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0001_initial_squashed_0007_remove_saleinvoice_checkout_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='checkout_type',
            field=models.CharField(blank=True, choices=[('sale', 'Sale'), ('appointment', 'Appointment')], default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='invoice_type',
            field=models.CharField(blank=True, choices=[('refund', 'Refund'), ('order', 'Order')], default='', max_length=50, null=True),
        ),
    ]
