# Generated by Django 4.0.6 on 2023-05-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleinvoice',
            name='business_address',
            field=models.CharField(default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='member',
            field=models.CharField(default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='service',
            field=models.CharField(default='', max_length=2000, null=True),
        ),
    ]
