# Generated by Django 4.0.6 on 2024-01-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0002_saleinvoice_checkout_type_saleinvoice_invoice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleinvoice',
            name='checkout_type',
            field=models.CharField(blank=True, choices=[('sale', 'Sale'), ('appointment', 'Appointment'), ('refund', 'refund')], default='', max_length=50, null=True),
        ),
    ]
