# Generated by Django 4.0.6 on 2023-05-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0002_alter_saleinvoice_business_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleinvoice',
            name='appointment_service',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='business_address',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='client_type',
            field=models.CharField(blank=True, choices=[('Walk_in', 'Walk-in'), ('In_Saloon', 'In-Saloon')], default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='member',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Voucher', 'Voucher'), ('SplitBill', 'SplitBill'), ('MasterCard', 'MasterCard'), ('Other', 'Other')], default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='product_commission_type',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='selected_promotion_id',
            field=models.CharField(blank=True, default='', max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='selected_promotion_type',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='service',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='service_commission_type',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='voucher_commission_type',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
