# Generated by Django 4.0.6 on 2024-01-30 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0028_remove_salerecords_refunds_data'),
        ('Invoices', '0003_alter_saleinvoice_checkout_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SaleRecords.paymentmethods'),
        ),
    ]
