# Generated by Django 4.0.6 on 2023-06-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0003_alter_saleinvoice_appointment_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='checkout',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
