# Generated by Django 4.0.6 on 2023-07-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0004_saleinvoice_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='invoicesFiles/'),
        ),
    ]
