# Generated by Django 4.0.6 on 2023-09-25 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0034_alter_order_discount_price'),
        ('Invoices', '0005_saleinvoice_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='checkout_obj',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='Order.checkout'),
        ),
    ]
