# Generated by Django 4.0.6 on 2024-02-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0005_remove_saleinvoice_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='sub_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='total_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='total_tax',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='total_tips',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
