# Generated by Django 4.0.6 on 2023-09-26 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0006_saleinvoice_checkout_obj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleinvoice',
            name='checkout_obj',
        ),
    ]
