# Generated by Django 4.0.6 on 2024-02-06 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0047_giftcards_is_custom_card'),
        ('Invoices', '0006_saleinvoice_sub_total_saleinvoice_total_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleinvoice',
            old_name='gst',
            new_name='total_tip',
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='appointment_service',
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='business_address',
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='gst_price',
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='is_promotion',
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='product_commission',
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='product_commission_type',
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='selected_promotion_id',
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='selected_promotion_type',
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='service',
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='service_commission',
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='service_commission_type',
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='service_price',
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='tip',
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='total_membership_price',
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='total_product_price',
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='total_service_price',
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='total_tips',
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='total_voucher_price',
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='voucher_commission',
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='voucher_commission_type',
        ),
        
        migrations.AlterField(
            model_name='saleinvoice',
            name='sub_total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='total_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='total_tax',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
