# Generated by Django 4.0.6 on 2024-02-06 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0034_appointmentgroup_group_name'),
        ('Invoices', '0007_rename_gst_saleinvoice_total_tip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Appointment.appointment'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='appointment_service',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
