# Generated by Django 4.0.6 on 2024-02-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0008_saleinvoice_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='business_address',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='gst',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='gst_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='is_promotion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='product_commission',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='product_commission_type',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='selected_promotion_id',
            field=models.CharField(blank=True, default='', max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='selected_promotion_type',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='service',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='service_commission',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='service_commission_type',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='service_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='tip',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='total_membership_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='total_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='total_product_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='total_service_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='total_voucher_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='voucher_commission',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='voucher_commission_type',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='member',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
