# Generated by Django 4.0.6 on 2024-02-06 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0009_saleinvoice_business_address_saleinvoice_gst_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleinvoice',
            name='gst',
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='gst_price',
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='is_promotion',
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='product_commission',
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='product_commission_type',
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='selected_promotion_id',
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='selected_promotion_type',
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='service_commission',
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='service_commission_type',
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='service_price',
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='total_membership_price',
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='total_product_price',
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='total_service_price',
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='total_voucher_price',
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='voucher_commission',
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='voucher_commission_type',
        ),
    ]
