# Generated by Django 4.0.6 on 2024-02-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0011_remove_saleinvoice_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='change',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
