# Generated by Django 4.0.6 on 2023-11-01 07:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('Product', '0001_initial'), ('Product', '0002_product_tax_rate'), ('Product', '0003_alter_product_vendor'), ('Product', '0004_alter_product_vendor'), ('Product', '0005_productstock_available_quantity_and_more'), ('Product', '0006_product_image'), ('Product', '0007_remove_product_image'), ('Product', '0008_auto_20220902_1046'), ('Product', '0009_alter_brand_description'), ('Product', '0010_alter_productstock_alert_when_stock_becomes_lowest'), ('Product', '0011_alter_productstock_alert_when_stock_becomes_lowest'), ('Product', '0012_alter_product_barcode_id'), ('Product', '0013_auto_20220902_1316'), ('Product', '0014_productmedia_is_cover'), ('Product', '0015_auto_20220928_1233'), ('Product', '0016_orderstock_orderstockproduct'), ('Product', '0017_alter_orderstock_rec_quantity'), ('Product', '0018_alter_orderstock_status'), ('Product', '0019_productstock_turnover'), ('Product', '0020_remove_productstock_quantity'), ('Product', '0021_remove_productstock_turnover'), ('Product', '0022_alter_product_product_size'), ('Product', '0023_productstock_product_unit'), ('Product', '0024_product_location'), ('Product', '0025_alter_productstock_product_unit'), ('Product', '0026_productconsumption'), ('Product', '0027_productstock_location_productstock_low_stock_and_more'), ('Product', '0028_productstocktransfer'), ('Product', '0029_productconsumption_is_deleted'), ('Product', '0030_productstocktransfer_is_deleted'), ('Product', '0031_remove_orderstock_location_orderstock_from_location_and_more'), ('Product', '0032_auto_20221215_1311'), ('Product', '0033_orderstockproduct_status'), ('Product', '0034_orderstockproduct_note'), ('Product', '0035_auto_20221219_1607'), ('Product', '0036_productstocktransfer_note'), ('Product', '0037_auto_20221227_1315'), ('Product', '0038_auto_20221228_1201'), ('Product', '0039_productorderstockreport'), ('Product', '0040_alter_productorderstockreport_report_choice'), ('Product', '0041_productorderstockreport_reorder_quantity'), ('Product', '0042_productstock_order_quantity'), ('Product', '0043_remove_productstock_order_quantity'), ('Product', '0044_productstock_consumed_quantity'), ('Product', '0045_product_product_size'), ('Product', '0046_orderstockproduct_is_finished'), ('Product', '0047_productconsumption_created_at'), ('Product', '0048_product_arabic_id_product_arabic_name'), ('Product', '0049_producttranslations'), ('Product', '0050_alter_currencyretailprice_retail_price'), ('Product', '0051_alter_product_cost_price_alter_product_product_size_and_more'), ('Product', '0052_alter_productstock_amount'), ('Product', '0053_brand_is_image_uploaded_s3_and_more')]

    dependencies = [
        ('Business', '0001_initial_squashed_0038_alter_businessvendor_email'),
        ('Utility', '0001_initial_squashed_0018_state_unique_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=500)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='brand/images/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_image_uploaded_s3', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('product_type', models.CharField(choices=[('Sellable', 'Sellable'), ('Consumable', 'Consumable'), ('Both', 'Both')], default='Sellable', max_length=20)),
                ('name', models.CharField(default='', max_length=1000)),
                ('cost_price', models.FloatField(blank=True, default=0, null=True)),
                ('short_description', models.TextField(blank=True, default='', null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('barcode_id', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('sku', models.CharField(default='', max_length=500)),
                ('slug', models.CharField(default='', max_length=1000)),
                ('published', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_products', to='Product.brand')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_products', to='Business.business')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_products', to='Product.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_products', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_products', to='Business.businessvendor')),
                ('tax_rate', models.FloatField(blank=True, default=0, null=True)),
                ('location', models.ManyToManyField(related_name='location_product', to='Business.businessaddress')),
                ('product_size', models.FloatField(default=0)),
                ('arabic_id', models.CharField(default='', editable=False, max_length=999)),
                ('arabic_name', models.CharField(default='', max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('Placed', 'Placed'), ('Delivered', 'Delivered'), ('Partially_Received', 'Partially Received'), ('Received', 'Received'), ('Cancelled', 'Cancelled')], default='Placed', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_order_stock', to='Business.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_order_stock', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_order_stock', to='Business.businessvendor')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_locations_order_stock', to='Business.businessaddress')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_locations_order_stock', to='Business.businessaddress')),
            ],
        ),
        migrations.CreateModel(
            name='ProductStockTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_location_stock_transfers', to='Business.businessaddress')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_stock_transfers', to='Product.product')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_location_stock_transfers', to='Business.businessaddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_stock_tranfers', to=settings.AUTH_USER_MODEL)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrderStockReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('report_choice', models.CharField(choices=[('Purchase', 'Purchase'), ('Consumed', 'Consumed'), ('Sold', 'Sold'), ('Transfer_to', 'Transfer_to'), ('Transfer_from', 'Transfer_From')], default='Sold', max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('before_quantity', models.PositiveIntegerField(default=0)),
                ('after_quantity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('consumed_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumed_location_product_stock_report', to='Business.businessaddress')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_location_product_stock_report', to='Business.businessaddress')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_product_stock_report', to='Business.businessaddress')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stock_report', to='Product.product')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_location_product_stock_report', to='Business.businessaddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_location_product_stock_report', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_product_stock_report', to='Business.businessvendor')),
                ('reorder_quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStockProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_stock', to='Product.orderstock')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_order_stock', to='Product.product')),
                ('status', models.CharField(choices=[('Placed', 'Placed'), ('Delivered', 'Delivered'), ('Partially_Received', 'Partially Received'), ('Received', 'Received'), ('Cancelled', 'Cancelled')], default='Placed', max_length=100)),
                ('note', models.TextField(blank=True, default='', null=True)),
                ('rec_quantity', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Received Quantity')),
                ('is_finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductConsumption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumption_locations', to='Business.businessaddress')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='Product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_product_cunsumptions', to=settings.AUTH_USER_MODEL)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTranslations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=500, null=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Utility.language')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyRetailPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('retail_price', models.FloatField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_currencyretailprice', to='Business.business')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Utility.currency')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_currencyretailprice', to='Product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_currencyretailprice', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('amount', models.FloatField(blank=True, default=0, null=True, verbose_name='Usage Amount')),
                ('unit', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Usage Unit')),
                ('alert_when_stock_becomes_lowest', models.BooleanField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_product_stocks', to='Business.business')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stock', to='Product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_product_stocks', to=settings.AUTH_USER_MODEL)),
                ('available_quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('sold_quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('consumable_quantity', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Consumable Quantity')),
                ('sellable_quantity', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sellable Quantity')),
                ('product_unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Product Unit')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_product_stocks', to='Business.businessaddress')),
                ('low_stock', models.PositiveIntegerField(default=0)),
                ('reorder_quantity', models.PositiveIntegerField(default=0)),
                ('consumed_quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='business/product_images/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_product_medias', to='Business.business')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_medias', to='Product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_product_medias', to=settings.AUTH_USER_MODEL)),
                ('is_cover', models.BooleanField(default=False)),
                ('is_image_uploaded_s3', models.BooleanField(default=False)),
            ],
        ),
    ]
