# Generated by Django 4.0.6 on 2024-01-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial_squashed_0053_brand_is_image_uploaded_s3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstock',
            name='is_refunded',
            field=models.BooleanField(default=False),
        ),
    ]
