# Generated by Django 4.0.6 on 2024-01-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_productstock_is_refunded'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstock',
            name='refund_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
