# Generated by Django 3.2.15 on 2022-08-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_productstock_available_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/product_images/'),
        ),
    ]
