# Generated by Django 3.2.15 on 2022-08-30 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
