# Generated by Django 3.2.15 on 2022-09-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_remove_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
