# Generated by Django 3.2.15 on 2022-09-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_auto_20220902_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
