# Generated by Django 3.2.15 on 2022-09-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_alter_brand_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='alert_when_stock_becomes_lowest',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
