# Generated by Django 3.2.15 on 2022-09-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0010_alter_productstock_alert_when_stock_becomes_lowest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='alert_when_stock_becomes_lowest',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
