# Generated by Django 3.2.15 on 2022-09-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_alter_productstock_alert_when_stock_becomes_lowest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode_id',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
