# Generated by Django 3.2.15 on 2022-09-28 07:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0014_productmedia_is_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productstock',
            name='consumable_quantity',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Consumable Quantity'),
        ),
        migrations.AddField(
            model_name='productstock',
            name='sellable_quantity',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sellable Quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('Sellable', 'Sellable'), ('Consumable', 'Consumable'), ('Both', 'Both')], default='Sellable', max_length=20),
        ),
    ]
