# Generated by Django 3.2.15 on 2022-09-29 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0021_businessaddress_banking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Product', '0015_auto_20220928_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('Placed', 'Placed'), ('Delivered', 'Delivered'), ('Partially_Received', 'Partially Received'), ('Received', 'Received')], default='Placed', max_length=100)),
                ('rec_quantity', models.PositiveIntegerField(default=0, verbose_name='Received Quantity')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_order_stock', to='Business.business')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations_order_stock', to='Business.businessaddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_order_stock', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_order_stock', to='Business.businessvendor')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStockProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_stock', to='Product.orderstock')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_order_stock', to='Product.product')),
            ],
        ),
    ]
