# Generated by Django 3.2.15 on 2022-09-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0016_orderstock_orderstockproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstock',
            name='rec_quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Received Quantity'),
        ),
    ]
