# Generated by Django 3.2.15 on 2022-10-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0018_alter_orderstock_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstock',
            name='turnover',
            field=models.CharField(choices=[('Lowest', 'Lowest'), ('Highest', 'Highest')], default='Highest', max_length=40),
        ),
    ]
