# Generated by Django 3.2.15 on 2022-10-17 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0019_productstock_turnover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstock',
            name='quantity',
        ),
    ]
