# Generated by Django 3.2.15 on 2022-10-17 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0020_remove_productstock_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstock',
            name='turnover',
        ),
    ]
