# Generated by Django 3.2.15 on 2022-10-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0021_remove_productstock_turnover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
