# Generated by Django 3.2.15 on 2022-10-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0022_alter_product_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstock',
            name='product_unit',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Product Unit'),
        ),
    ]
