# Generated by Django 3.2.15 on 2022-11-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0024_product_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='product_unit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Product Unit'),
        ),
    ]
