# Generated by Django 4.0.6 on 2022-11-30 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Business', '0022_business_is_completed'),
        ('Product', '0025_alter_productstock_product_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductConsumption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumption_locations', to='Business.businessaddress')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='Product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_product_cunsumptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
