# Generated by Django 4.0.6 on 2022-11-30 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0022_business_is_completed'),
        ('Product', '0026_productconsumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstock',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_product_stocks', to='Business.businessaddress'),
        ),
        migrations.AddField(
            model_name='productstock',
            name='low_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productstock',
            name='reorder_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
