# Generated by Django 4.0.6 on 2022-12-01 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0022_business_is_completed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Product', '0027_productstock_location_productstock_low_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStockTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_location_stock_transfers', to='Business.businessaddress')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_stock_transfers', to='Product.product')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_location_stock_transfers', to='Business.businessaddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_stock_tranfers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
