# Generated by Django 4.0.6 on 2022-12-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0028_productstocktransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='productconsumption',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
