# Generated by Django 4.0.6 on 2022-12-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0029_productconsumption_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstocktransfer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
