# Generated by Django 4.0.6 on 2022-12-03 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0022_business_is_completed'),
        ('Product', '0030_productstocktransfer_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstock',
            name='location',
        ),
        migrations.AddField(
            model_name='orderstock',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_locations_order_stock', to='Business.businessaddress'),
        ),
        migrations.AddField(
            model_name='orderstock',
            name='to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_locations_order_stock', to='Business.businessaddress'),
        ),
    ]
