# Generated by Django 3.2.15 on 2022-12-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0031_remove_orderstock_location_orderstock_from_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstocktransfer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productstocktransfer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
