# Generated by Django 3.2.15 on 2022-12-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0033_orderstockproduct_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstockproduct',
            name='note',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
