# Generated by Django 3.2.15 on 2022-12-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0034_orderstockproduct_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstock',
            name='rec_quantity',
        ),
        migrations.AddField(
            model_name='orderstockproduct',
            name='rec_quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Received Quantity'),
        ),
    ]
