# Generated by Django 3.2.15 on 2022-12-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0035_auto_20221219_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstocktransfer',
            name='note',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
