# Generated by Django 3.2.15 on 2023-01-02 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Business', '0028_businessaddress_description'),
        ('Product', '0038_auto_20221228_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrderStockReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('report_choice', models.CharField(choices=[('Purchase', 'Purchase'), ('Consumed', 'Consumed'), ('Sold', 'Sold'), ('Transfer', 'Transfer')], default='Sold', max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('before_quantity', models.PositiveIntegerField(default=0)),
                ('after_quantity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('consumed_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumed_location_product_stock_report', to='Business.businessaddress')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_location_product_stock_report', to='Business.businessaddress')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_product_stock_report', to='Business.businessaddress')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stock_report', to='Product.product')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_location_product_stock_report', to='Business.businessaddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_location_product_stock_report', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_product_stock_report', to='Business.businessvendor')),
            ],
        ),
    ]
