# Generated by Django 3.2.15 on 2023-01-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0039_productorderstockreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorderstockreport',
            name='report_choice',
            field=models.CharField(choices=[('Purchase', 'Purchase'), ('Consumed', 'Consumed'), ('Sold', 'Sold'), ('Transfer_to', 'Transfer_to'), ('Transfer_from', 'Transfer_From')], default='Sold', max_length=100),
        ),
    ]
