# Generated by Django 3.2.15 on 2023-01-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0040_alter_productorderstockreport_report_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorderstockreport',
            name='reorder_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
