# Generated by Django 3.2.15 on 2023-02-09 05:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0041_productorderstockreport_reorder_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstock',
            name='order_quantity',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
