# Generated by Django 3.2.18 on 2023-02-21 08:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0043_remove_productstock_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstock',
            name='consumed_quantity',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
