# Generated by Django 3.2.18 on 2023-02-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0044_productstock_consumed_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
