# Generated by Django 4.0.6 on 2023-05-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0045_product_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstockproduct',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
