# Generated by Django 4.0.6 on 2023-06-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0046_orderstockproduct_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='productconsumption',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
