# Generated by Django 4.0.6 on 2023-07-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0047_productconsumption_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='arabic_id',
            field=models.UUIDField(default='', editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='arabic_name',
            field=models.CharField(default='', max_length=999),
        ),
    ]
