# Generated by Django 4.0.6 on 2023-08-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0049_producttranslations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyretailprice',
            name='retail_price',
            field=models.FloatField(default=0),
        ),
    ]
