# Generated by Django 4.0.6 on 2023-08-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0050_alter_currencyretailprice_retail_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_size',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax_rate',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
