# Generated by Django 4.0.6 on 2023-08-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0052_alter_productstock_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_image_uploaded_s3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='is_image_uploaded_s3',
            field=models.BooleanField(default=False),
        ),
    ]
