# Generated by Django 4.0.6 on 2023-11-01 07:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('Help', '0001_initial'), ('Help', '0002_comment_is_parent'), ('Help', '0003_alter_comment_parent_comment'), ('Help', '0004_rename_comment_helpcontent'), ('Help', '0005_helpcontent_image'), ('Help', '0006_helpcontent_description'), ('Help', '0007_helpcontent_is_recent'), ('Help', '0008_helpcontent_order'), ('Help', '0009_helpcontent_is_image_uploaded_s3')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Help.comment')),
                ('is_parent', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='helpcenter/images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_recent', models.BooleanField(default=False)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('is_image_uploaded_s3', models.BooleanField(default=False)),
            ],
        ),
    ]
