# Generated by Django 4.0.6 on 2023-05-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Help', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
    ]
