# Generated by Django 4.0.6 on 2023-05-30 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Help', '0003_alter_comment_parent_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='HelpContent',
        ),
    ]
