# Generated by Django 4.0.6 on 2023-07-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Help', '0004_rename_comment_helpcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpcontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='helpcenter/images/'),
        ),
    ]
