# Generated by Django 4.0.6 on 2023-07-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Help', '0005_helpcontent_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpcontent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
