# Generated by Django 4.0.6 on 2023-07-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Help', '0007_helpcontent_is_recent'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpcontent',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
