# Generated by Django 4.0.6 on 2023-11-01 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('Analytics', '0001_initial'), ('Analytics', '0002_alter_employeebookingdailyinsights_day_time_choice'), ('Analytics', '0003_alter_employeebookingdailyinsights_day_time_choice'), ('Analytics', '0004_employeebookingdailyinsights_booking_time'), ('Analytics', '0005_employeebookingdailyinsights_appointment_date_and_more'), ('Analytics', '0006_remove_employeebookingdailyinsights_appointment_date')]

    dependencies = [
        ('Business', '0001_initial_squashed_0038_alter_businessvendor_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Service', '0032_alter_service_initial_deposit_alter_service_price'),
        ('Appointment', '0055_appointmentservice_is_redeemed_and_more'),
        ('Employee', '0001_initial_squashed_0056_employee_is_image_uploaded_s3'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeBookingDailyInsights',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('day_time_choice', models.CharField(blank=True, choices=[('M', 'Morning'), ('A', 'Afternoon'), ('E', 'Evening')], max_length=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_daily_insights', to='Appointment.appointment')),
                ('appointment_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_daily_insights', to='Appointment.appointmentservice')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_daily_insights', to='Business.business')),
                ('business_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_daily_insights', to='Business.businessaddress')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_daily_insights', to='Employee.employee')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_daily_insights', to='Service.service')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_daily_insights', to=settings.AUTH_USER_MODEL)),
                ('booking_time', models.TimeField(blank=True, null=True, verbose_name='Appointment Start Time')),
            ],
        ),
    ]
