# Generated by Django 4.0.6 on 2023-08-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeebookingdailyinsights',
            name='day_time_choice',
            field=models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('E', 'Evening'), ('O', 'Other')], default=None, max_length=2),
        ),
    ]
