# Generated by Django 4.0.6 on 2023-08-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0002_alter_employeebookingdailyinsights_day_time_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeebookingdailyinsights',
            name='day_time_choice',
            field=models.CharField(blank=True, choices=[('M', 'Morning'), ('A', 'Afternoon'), ('E', 'Evening'), ('O', 'Other')], max_length=2, null=True),
        ),
    ]
