# Generated by Django 4.0.6 on 2023-08-31 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0004_employeebookingdailyinsights_booking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeebookingdailyinsights',
            name='appointment_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='employeebookingdailyinsights',
            name='day_time_choice',
            field=models.CharField(blank=True, choices=[('M', 'Morning'), ('A', 'Afternoon'), ('E', 'Evening')], max_length=2, null=True),
        ),
    ]
