# Generated by Django 4.0.6 on 2023-08-31 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0005_employeebookingdailyinsights_appointment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeebookingdailyinsights',
            name='appointment_date',
        ),
    ]
