# Generated by Django 4.0.6 on 2023-12-26 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='reason',
        ),
    ]
