# Generated by Django 4.0.6 on 2024-01-01 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundproduct',
            name='refund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunded_products', to='Finance.refund', verbose_name='Refund id'),
        ),
        migrations.AlterField(
            model_name='refundservices',
            name='refund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunded_services', to='Finance.refund', verbose_name='Refund id'),
        ),
    ]
