# Generated by Django 4.0.6 on 2024-01-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0002_alter_refundproduct_refund_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundproduct',
            name='in_stock',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
