# Generated by Django 4.0.6 on 2023-12-27 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial_squashed_0074_client_is_image_uploaded_s3'),
        ('Finance', '0002_remove_refund_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Client.client', verbose_name='Client id'),
        ),
    ]
