# Generated by Django 4.0.6 on 2023-12-27 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0001_initial_squashed_0032_alter_service_initial_deposit_alter_service_price'),
        ('Finance', '0003_alter_refund_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refunded_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='refund',
            name='refunded_services',
            field=models.ManyToManyField(through='Finance.RefundServices', to='Service.service'),
        ),
        migrations.AddField(
            model_name='refundservices',
            name='refund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.refund', verbose_name='Refund id'),
        ),
        migrations.AddField(
            model_name='refundservices',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service.service', verbose_name='Service id'),
        ),
    ]
