# Generated by Django 4.0.6 on 2024-01-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0003_alter_refundproduct_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundproduct',
            name='in_stock',
            field=models.BooleanField(default=False),
        ),
    ]
