# Generated by Django 4.0.6 on 2023-12-27 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial_squashed_0074_client_is_image_uploaded_s3'),
        ('Finance', '0004_refundservices_refund_refunded_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Client.client', verbose_name='Client id'),
        ),
    ]
