# Generated by Django 4.0.6 on 2024-01-04 20:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0012_vacation_vacation_type'),
        ('Business', '0006_alter_refundsetting_is_active'),
        ('Finance', '0004_alter_refundproduct_in_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowRefunds',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('number_of_days', models.PositiveIntegerField(default=30)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_refund_locations', to='Business.businessaddress')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AllowRefundPermissionsEmployees',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('can_refund', models.BooleanField(default=False)),
                ('allowed_refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_refund', to='Finance.allowrefunds')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='Employee.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
