# Generated by Django 4.0.6 on 2023-12-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0005_alter_refund_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
