# Generated by Django 4.0.6 on 2024-01-09 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0006_allowrefunds_sale_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowrefunds',
            name='sale_invoice',
        ),
    ]
