# Generated by Django 4.0.6 on 2024-01-22 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0007_remove_allowrefunds_sale_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundcoupon',
            name='related_refund',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_refund_coupon', to='Finance.refund'),
        ),
    ]
