# Generated by Django 4.0.6 on 2023-12-28 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial_squashed_0074_client_is_image_uploaded_s3'),
        ('Finance', '0007_alter_refund_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Client.client'),
        ),
    ]
