# Generated by Django 4.0.6 on 2024-01-25 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0003_servicegroup_image_servicegroup_is_image_uploaded_s3'),
        ('Product', '0003_productstock_refund_quantity'),
        ('Finance', '0008_alter_refundcoupon_related_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product'),
        ),
        migrations.AlterField(
            model_name='refundproduct',
            name='refund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunded_products', to='Finance.refund'),
        ),
        migrations.AlterField(
            model_name='refundservices',
            name='refund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunded_services', to='Finance.refund'),
        ),
        migrations.AlterField(
            model_name='refundservices',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service.service'),
        ),
    ]
