# Generated by Django 4.0.6 on 2023-12-28 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0008_alter_coupon_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='refunded_products',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='refunded_services',
        ),
    ]
