# Generated by Django 4.0.6 on 2024-02-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0009_alter_refundproduct_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundservices',
            name='quantity',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
