# Generated by Django 4.0.6 on 2023-12-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0010_alter_coupon_related_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundproduct',
            name='back_stock',
            field=models.BooleanField(default=False),
        ),
    ]
