# Generated by Django 4.0.6 on 2024-02-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0011_refundproduct_refundcheckouts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refundproduct',
            name='refundcheckouts',
        ),
        migrations.RemoveField(
            model_name='refundservices',
            name='refundcheckouts',
        ),
        migrations.AddField(
            model_name='refundproduct',
            name='checkouts',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='refundservices',
            name='checkouts',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
