# Generated by Django 4.0.6 on 2023-12-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0012_remove_refundproduct_back_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundproduct',
            name='in_stock',
            field=models.BooleanField(default=False),
        ),
    ]
