# Generated by Django 4.0.6 on 2024-02-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0012_remove_refundproduct_refundcheckouts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='refund_type',
            field=models.CharField(choices=[('Credit Refund', 'Credit Refund'), ('Cash Refund', 'Cash Refund')], max_length=20),
        ),
    ]
