# Generated by Django 4.0.6 on 2024-02-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0014_refundcoupon_checkout_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refundcoupon',
            name='checkout_id',
        ),
        migrations.AddField(
            model_name='refundcoupon',
            name='coupon_type',
            field=models.CharField(default='refund', max_length=20),
        ),
    ]
