# Generated by Django 4.0.6 on 2024-03-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0016_refundcoupon_checkout_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='client_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
