# Generated by Django 4.0.6 on 2022-08-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='business_id',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
