# Generated by Django 3.2.15 on 2023-01-09 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tenants', '0003_alter_domain_user_alter_tenant_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTenantAppDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('client_id', models.CharField(blank=True, default='', max_length=1000, null=True, unique=True)),
                ('is_appointment', models.BooleanField(default=False)),
                ('is_tenant_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_client', to='Tenants.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_detail_client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
