# Generated by Django 3.2.15 on 2023-01-10 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tenants', '0004_clienttenantappdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientIdUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('client_id', models.CharField(blank=True, default='', max_length=1000, null=True, unique=True)),
                ('is_everyone', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
