# Generated by Django 4.0.6 on 2023-10-11 08:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0007_tenant_is_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='last_active',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
