# Generated by Django 4.0.6 on 2022-08-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofessionalinfo',
            name='services',
            field=models.ManyToManyField(related_name='services_employee', to='Service.service'),
        ),
    ]
