# Generated by Django 4.0.6 on 2023-12-29 11:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial_squashed_0056_employee_is_image_uploaded_s3'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekendManagements',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monday', models.TextField(default=False)),
                ('tuesday', models.TextField(default=False)),
                ('wednesday', models.TextField(default=False)),
                ('thursday', models.TextField(default=False)),
                ('friday', models.TextField(default=False)),
                ('saturday', models.TextField(default=False)),
                ('sunday', models.TextField(default=False)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_weekdays', to='Employee.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeaveManagements',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('casual_leave', models.IntegerField(default=0, help_text='Number of casual leaves allowed', null=True)),
                ('annual_leave', models.IntegerField(default=0, help_text='Number of annual leaves allowed', null=True)),
                ('medical_leave', models.IntegerField(default=0, help_text='Number of medical leaves allowed', null=True)),
                ('number_of_months', models.TextField(null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_leaves', to='Employee.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
