# Generated by Django 4.0.6 on 2023-12-29 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial_squashed_0056_employee_is_image_uploaded_s3'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casual_leave', models.IntegerField(default=0, help_text='Number of casual leaves allowed', null=True)),
                ('annual_leave', models.IntegerField(default=0, help_text='Number of annual leaves allowed', null=True)),
                ('medical_leave', models.IntegerField(default=0, help_text='Number of medical leaves allowed', null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Employee.employee')),
            ],
        ),
    ]
