# Generated by Django 4.0.6 on 2023-12-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_weekendmanagements_leavemanagements'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_refunds',
            field=models.BooleanField(default=True),
        ),
    ]
