# Generated by Django 4.0.6 on 2022-08-25 05:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_employeeprofessionalinfo_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePermissionSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('allow_calendar_booking', models.BooleanField(default=True)),
                ('access_calendar', models.BooleanField(default=False)),
                ('change_calendar_color', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_permissions_setting', to='Employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeModulePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('access_reports', models.BooleanField(default=False)),
                ('access_sales', models.BooleanField(default=False)),
                ('access_inventory', models.BooleanField(default=False)),
                ('access_expenses', models.BooleanField(default=False)),
                ('access_products', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_module_permission', to='Employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeMarketingPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('access_voucher', models.BooleanField(default=False)),
                ('access_member_discount', models.BooleanField(default=False)),
                ('access_invite_friend', models.BooleanField(default=False)),
                ('access_loyalty_points', models.BooleanField(default=False)),
                ('access_gift_cards', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_marketing_permission', to='Employee.employee')),
            ],
        ),
    ]
