# Generated by Django 4.0.6 on 2023-12-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_alter_leavemanagement_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavemanagement',
            name='number_of_months',
            field=models.TextField(null=True),
        ),
    ]
