# Generated by Django 4.0.6 on 2023-12-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_employee_can_refunds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='can_refund',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='can_refunds',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
