# Generated by Django 4.0.6 on 2022-08-26 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Business', '0009_businessvendor'),
        ('Employee', '0003_employeepermissionsetting_employeemodulepermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=300)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_staff_group', to='Business.business')),
                ('employees', models.ManyToManyField(related_name='staff_group_employees', to='Employee.employee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_staff_group', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffGroupModulePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('access_reports', models.BooleanField(default=True)),
                ('access_sales', models.BooleanField(default=False)),
                ('access_inventory', models.BooleanField(default=False)),
                ('access_expenses', models.BooleanField(default=True)),
                ('access_products', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_group_module_permissions', to='Employee.staffgroup')),
            ],
        ),
    ]
