# Generated by Django 4.0.6 on 2022-08-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_staffgroup_staffgroupmodulepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='employee/employee_images/'),
        ),
    ]
