# Generated by Django 4.0.6 on 2024-01-02 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_employee_can_refund_alter_employee_can_refunds'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('vacation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacation_detail', to='Employee.vacation')),
            ],
        ),
    ]
