# Generated by Django 4.0.6 on 2024-01-02 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0005_vacationdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacationdetails',
            old_name='status',
            new_name='vacation_status',
        ),
    ]
