# Generated by Django 4.0.6 on 2023-12-29 11:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0006_employee_can_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavemanagement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='leavemanagement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leavemanagement',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavemanagement',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavemanagement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='weekendmanagement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='weekendmanagement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='weekendmanagement',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weekendmanagement',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weekendmanagement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='leavemanagement',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='weekendmanagement',
            name='friday',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='weekendmanagement',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='weekendmanagement',
            name='monday',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='weekendmanagement',
            name='saturday',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='weekendmanagement',
            name='sunday',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='weekendmanagement',
            name='thursday',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='weekendmanagement',
            name='tuesday',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='weekendmanagement',
            name='wednesday',
            field=models.TextField(default=False),
        ),
    ]
