# Generated by Django 4.0.6 on 2024-01-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0006_rename_status_vacationdetails_vacation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='vacation_status',
            field=models.TextField(null=True),
        ),
    ]
