# Generated by Django 4.0.6 on 2023-12-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0006_employee_can_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekendmanagement',
            name='friday',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='weekendmanagement',
            name='monday',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='weekendmanagement',
            name='saturday',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='weekendmanagement',
            name='sunday',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='weekendmanagement',
            name='thursday',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='weekendmanagement',
            name='tuesday',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='weekendmanagement',
            name='wednesday',
            field=models.TextField(default=False),
        ),
    ]
