# Generated by Django 4.0.6 on 2023-12-29 11:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0007_alter_weekendmanagement_friday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemanagement',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='weekendmanagement',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
