# Generated by Django 4.0.6 on 2024-01-02 10:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0007_vacation_vacation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekManagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monday', models.BooleanField(default=False, null=True)),
                ('tuesday', models.BooleanField(default=False, null=True)),
                ('wednesday', models.TextField(default=False, null=True)),
                ('thursday', models.TextField(default=False, null=True)),
                ('friday', models.TextField(default=False, null=True)),
                ('saturday', models.TextField(default=False, null=True)),
                ('sunday', models.TextField(default=False, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_weekday', to='Employee.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
