# Generated by Django 4.0.6 on 2024-01-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0008_weekmanagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekmanagement',
            name='friday',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='weekmanagement',
            name='saturday',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='weekmanagement',
            name='sunday',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='weekmanagement',
            name='thursday',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='weekmanagement',
            name='wednesday',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
