# Generated by Django 4.0.6 on 2024-01-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0009_alter_weekmanagement_friday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employedailyschedule',
            name='is_weekend',
            field=models.BooleanField(default=False),
        ),
    ]
