# Generated by Django 4.0.6 on 2022-09-06 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Business', '0016_alter_businessopeninghour_close_time_and_more'),
        ('Employee', '0010_auto_20220901_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionSchemeSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sale_price_before_discount', models.BooleanField(default=True)),
                ('sale_price_including_tax', models.BooleanField(default=True)),
                ('service_price_before_membership_discount', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_commission_setting', to='Business.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_commission_setting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
