# Generated by Django 4.0.6 on 2024-01-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0010_employedailyschedule_is_weekend'),
    ]

    operations = [
        migrations.AddField(
            model_name='employedailyschedule',
            name='is_leo_day',
            field=models.BooleanField(default=False),
        ),
    ]
