# Generated by Django 4.0.6 on 2024-01-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0012_vacation_vacation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavemanagements',
            name='leo_leave',
            field=models.IntegerField(default=0, help_text='Number of medical leaves allowed', null=True),
        ),
    ]
