# Generated by Django 3.2.15 on 2022-09-27 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0013_remove_workingdays_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workingdays',
            name='user',
        ),
    ]
