# Generated by Django 4.0.6 on 2024-01-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0013_leavemanagements_leo_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='employedailyschedule',
            name='title',
            field=models.TextField(default='weekend', null=True),
        ),
    ]
