# Generated by Django 4.0.6 on 2024-01-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0015_alter_employedailyschedule_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('gift_card_value', models.FloatField(default=0, null=True)),
                ('retail_price', models.FloatField(default=0, null=True)),
                ('expire_date', models.DateField(auto_now_add=True, null=True)),
                ('discount_to_show', models.TextField(null=True)),
            ],
        ),
    ]
