# Generated by Django 4.0.6 on 2022-09-27 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0015_auto_20220927_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeprofessionalinfo',
            old_name='firday',
            new_name='friday',
        ),
    ]
