# Generated by Django 3.2.15 on 2022-09-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0016_rename_firday_employeeprofessionalinfo_friday'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofessionalinfo',
            name='level',
            field=models.CharField(choices=[('Average', 'Average'), ('Above_Averge', 'Above Average')], default='Average', max_length=100),
        ),
    ]
