# Generated by Django 4.0.6 on 2024-01-08 07:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0016_giftcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCards',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('gift_card_value', models.FloatField(default=0, null=True)),
                ('retail_price', models.FloatField(default=0, null=True)),
                ('expire_date', models.DateField(auto_now_add=True, null=True)),
                ('discount_to_show', models.TextField(null=True)),
            ],
        ),
    ]
