# Generated by Django 3.2.15 on 2022-09-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0017_employeeprofessionalinfo_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofessionalinfo',
            name='level',
            field=models.CharField(choices=[('Average', 'Average'), ('Above_Averge', 'Above Average')], default='Average', max_length=100, verbose_name='Employee Level'),
        ),
    ]
