# Generated by Django 4.0.6 on 2024-01-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0018_leavemanagements_operational_annual_leave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employedailyschedule',
            name='is_holiday',
            field=models.BooleanField(default=False),
        ),
    ]
