# Generated by Django 3.2.15 on 2022-10-14 07:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0005_alter_service_duration'),
        ('Employee', '0019_asset_assetdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofessionalinfo',
            name='level',
        ),
        migrations.RemoveField(
            model_name='employeeprofessionalinfo',
            name='services',
        ),
        migrations.CreateModel(
            name='EmployeeSelectedService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('level', models.CharField(choices=[('Average', 'Average'), ('Above_Averge', 'Above Average')], default='Average', max_length=100, verbose_name='Employee Service Level')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_selected_service', to='Employee.employee')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_service', to='Service.service')),
            ],
        ),
    ]
