# Generated by Django 4.0.6 on 2024-01-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0020_employedailyschedule_is_display_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employedailyschedule',
            name='is_schedule',
            field=models.BooleanField(default=False),
        ),
    ]
