# Generated by Django 4.0.6 on 2024-01-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0021_employedailyschedule_is_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='employedailyschedule',
            name='is_working_schedule',
            field=models.BooleanField(default=False),
        ),
    ]
