# Generated by Django 4.0.6 on 2024-01-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0022_employedailyschedule_is_working_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='employedailyschedule',
            name='is_holiday_due_to_update',
            field=models.BooleanField(default=False),
        ),
    ]
