# Generated by Django 3.2.15 on 2022-12-07 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0023_auto_20221116_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionschemesetting',
            name='duration',
            field=models.CharField(choices=[('Service', 'Service'), ('Retail', 'Retail'), ('Both', 'Both')], default='Service', max_length=50),
        ),
        migrations.AddField(
            model_name='commissionschemesetting',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_commissioin', to='Employee.employee'),
        ),
        migrations.AddField(
            model_name='commissionschemesetting',
            name='from_value',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='commissionschemesetting',
            name='percentage',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='commissionschemesetting',
            name='to_value',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
