# Generated by Django 3.2.15 on 2022-12-08 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0024_auto_20221207_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commissionschemesetting',
            old_name='duration',
            new_name='category_com',
        ),
    ]
