# Generated by Django 4.0.6 on 2024-01-15 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0025_giftcards_code_giftcards_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giftcards',
            old_name='date',
            new_name='expire_date',
        ),
    ]
