# Generated by Django 3.2.15 on 2022-12-09 05:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0026_employeeprofessionalinfo_maximum_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('from_date', models.DateField(null=True, verbose_name='From Date')),
                ('to_date', models.DateField(null=True, verbose_name='To Date')),
                ('note', models.CharField(default='', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_vacation', to='Employee.employee')),
            ],
        ),
    ]
