# Generated by Django 4.0.6 on 2024-01-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0027_giftcards_end_date_giftcards_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcards',
            name='currency',
            field=models.TextField(null=True),
        ),
    ]
