# Generated by Django 3.2.15 on 2022-12-09 07:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0028_auto_20221209_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissionschemesetting',
            name='category_com',
        ),
        migrations.AddField(
            model_name='commissionschemesetting',
            name='commission_cycle',
            field=models.CharField(choices=[('Every day', 'Every day'), ('Every week', 'Every week'), ('Every 2 week', 'Every 2 week'), ('Every 4 week', 'Every 4 week'), ('Every month', 'Every month'), ('Every quarter', 'Every quarter'), ('Every 6 months', 'Every 6 months'), ('Every year', 'Every year')], default='Service', max_length=50),
        ),
        migrations.CreateModel(
            name='CategoryCommission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('from_value', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('to_value', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('commission_percentage', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('category_comission', models.CharField(choices=[('Service', 'Service'), ('Retail', 'Retail'), ('Both', 'Both')], default='Service', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorycommission_commission', to='Employee.commissionschemesetting')),
            ],
        ),
    ]
