# Generated by Django 3.2.15 on 2022-12-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0029_auto_20221209_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionschemesetting',
            name='commission_cycle',
            field=models.CharField(choices=[('Every day', 'Every day'), ('Every week', 'Every week'), ('Every 2 week', 'Every 2 week'), ('Every 4 week', 'Every 4 week'), ('Every month', 'Every month'), ('Every quarter', 'Every quarter'), ('Every 6 months', 'Every 6 months'), ('Every year', 'Every year')], default='Every day', max_length=50),
        ),
    ]
