# Generated by Django 4.0.6 on 2024-01-16 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0006_alter_refundsetting_is_active'),
        ('Employee', '0029_giftcards_valid_till'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcards',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_card_location', to='Business.businessaddress'),
        ),
    ]
