# Generated by Django 4.0.6 on 2024-01-16 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0030_giftcards_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcards',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='giftcards',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='giftcards',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GiftDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0, null=True)),
                ('retail_price', models.FloatField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('gift_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Employee.giftcards')),
            ],
        ),
    ]
