# Generated by Django 3.2.15 on 2022-12-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0030_alter_commissionschemesetting_commission_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofessionalinfo',
            name='maximum_discount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
