# Generated by Django 4.0.6 on 2024-01-16 06:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0031_giftcards_created_at_giftcards_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcards',
            name='custom_card',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='GiftDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('price', models.FloatField(default=0, null=True)),
                ('retail_price', models.FloatField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('gift_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Employee.giftcards')),
            ],
        ),
    ]
