# Generated by Django 4.0.6 on 2024-01-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0032_giftcards_custom_card_giftdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcards',
            name='price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
