# Generated by Django 4.0.6 on 2024-01-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0033_giftcards_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftdetail',
            name='currency',
            field=models.TextField(null=True),
        ),
    ]
