# Generated by Django 3.2.15 on 2022-12-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0033_auto_20221223_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employedailyschedule',
            name='note',
            field=models.CharField(default='', max_length=300, null=True),
        ),
    ]
