# Generated by Django 3.2.15 on 2022-12-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0034_alter_employedailyschedule_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorycommission',
            name='comission_choice',
            field=models.CharField(choices=[('percentage', 'percentage'), ('currency', 'currency')], default='percentage', max_length=50),
        ),
    ]
