# Generated by Django 3.2.15 on 2022-12-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0035_categorycommission_comission_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorycommission',
            name='to_value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
