# Generated by Django 3.2.15 on 2022-12-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0036_alter_categorycommission_to_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorycommission',
            name='comission_choice',
        ),
        migrations.AddField(
            model_name='categorycommission',
            name='symbol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
