# Generated by Django 4.0.6 on 2024-01-17 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0036_alter_giftdetail_currencies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftdetail',
            name='gift_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gift_card_details', to='Employee.giftcards'),
        ),
    ]
