# Generated by Django 3.2.15 on 2022-12-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0037_auto_20221228_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorycommission',
            name='category_comission',
            field=models.CharField(choices=[('Service', 'Service'), ('Retail', 'Retail'), ('Voucher', 'Voucher')], default='Service', max_length=50),
        ),
    ]
