# Generated by Django 3.2.15 on 2023-01-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0038_alter_categorycommission_category_comission'),
    ]

    operations = [
        migrations.AddField(
            model_name='employedailyschedule',
            name='date',
            field=models.DateField(null=True, verbose_name='From Date'),
        ),
    ]
