# Generated by Django 4.0.6 on 2024-01-18 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0006_alter_refundsetting_is_active'),
        ('Employee', '0038_giftcards_term_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='employedailyschedule',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_weekend_sceduale', to='Business.businessaddress'),
        ),
    ]
