# Generated by Django 3.2.15 on 2023-01-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0039_employedailyschedule_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employedailyschedule',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Date'),
        ),
    ]
