# Generated by Django 4.0.6 on 2024-01-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0039_employedailyschedule_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='employedailyschedule',
            name='created_from_dashboard',
            field=models.TextField(null=True),
        ),
    ]
