# Generated by Django 4.0.6 on 2024-01-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0041_leavemanagements_used_annual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employedailyschedule',
            name='last_state_of_schedule',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='employedailyschedule',
            name='vacation_type',
            field=models.TextField(null=True),
        ),
    ]
