# Generated by Django 3.2.18 on 2023-02-24 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0028_businessaddress_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Employee', '0041_alter_employee_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SallarySlipPayrol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('month', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_employee_sallary_slip', to='Business.business')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_sallary_slip', to='Employee.employee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sallary_slip', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
