# Generated by Django 4.0.6 on 2024-01-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0042_employedailyschedule_last_state_of_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_active_date',
            field=models.DateField(null=True),
        ),
    ]
