# Generated by Django 4.0.6 on 2024-01-29 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0043_employee_is_active_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='is_active_date',
            new_name='in_active_date',
        ),
    ]
