# Generated by Django 4.0.6 on 2024-01-29 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0044_rename_is_active_date_employee_in_active_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftcards',
            name='name',
        ),
    ]
