# Generated by Django 4.0.6 on 2024-01-31 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0045_remove_giftcards_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giftdetail',
            old_name='retail_price',
            new_name='spend_amount',
        ),
        migrations.RemoveField(
            model_name='giftcards',
            name='price',
        ),
        migrations.RemoveField(
            model_name='giftcards',
            name='retail_price',
        ),
        migrations.DeleteModel(
            name='GiftDetails',
        ),
    ]
