# Generated by Django 4.0.6 on 2023-05-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0045_employedailyschedule_vacation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
