# Generated by Django 4.0.6 on 2023-05-24 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0029_businessaddress_is_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Employee', '0046_employee_is_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCommission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('from_value', models.FloatField(default=0)),
                ('to_value', models.FloatField(default=0)),
                ('commission_percentage', models.FloatField(default=0)),
                ('commission_category', models.CharField(choices=[('Service', 'Service'), ('Retail', 'Retail'), ('Voucher', 'Voucher')], default='Service', max_length=50)),
                ('commission_type', models.CharField(choices=[('percentage', 'percentage'), ('currency', 'currency')], default='percentage', max_length=50)),
                ('symbol', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_employee_commissions', to='Business.business')),
                ('category_commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_category_commissions', to='Employee.categorycommission')),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_commissions', to='Employee.commissionschemesetting')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='Employee.employee')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_commissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
