# Generated by Django 4.0.6 on 2024-02-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0046_rename_retail_price_giftdetail_spend_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcards',
            name='is_custom_card',
            field=models.BooleanField(default=False),
        ),
    ]
