# Generated by Django 4.0.6 on 2024-02-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0047_giftcards_is_custom_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcards',
            name='retail_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
