# Generated by Django 4.0.6 on 2023-05-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0047_employeecommission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeecommission',
            old_name='commission_percentage',
            new_name='commission_amount',
        ),
        migrations.RemoveField(
            model_name='employeecommission',
            name='from_value',
        ),
        migrations.RemoveField(
            model_name='employeecommission',
            name='to_value',
        ),
        migrations.AddField(
            model_name='employeecommission',
            name='commission_rate',
            field=models.FloatField(default=0, verbose_name='Commission Current rate, Percentage/Price'),
        ),
        migrations.AddField(
            model_name='employeecommission',
            name='item_id',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='employeecommission',
            name='item_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='employeecommission',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeecommission',
            name='sale_value',
            field=models.FloatField(default=0, verbose_name='Sold Item Current Price'),
        ),
        migrations.AlterField(
            model_name='employeecommission',
            name='symbol',
            field=models.CharField(default='', max_length=50, verbose_name='Percentage/Currency Symbol'),
        ),
    ]
