# Generated by Django 4.0.6 on 2023-05-25 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0048_rename_commission_percentage_employeecommission_commission_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecommission',
            name='category_commission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_category_commissions', to='Employee.categorycommission'),
        ),
        migrations.AlterField(
            model_name='employeecommission',
            name='commission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_commissions', to='Employee.commissionschemesetting'),
        ),
    ]
