# Generated by Django 4.0.6 on 2024-02-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0049_remove_giftcards_retail_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeselectedservice',
            name='level',
            field=models.CharField(choices=[('Average', 'Average'), ('Above_Averge', 'Above Average')], default='Average', max_length=255, verbose_name='Employee Service Level'),
        ),
    ]
