# Generated by Django 4.0.6 on 2023-05-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0049_alter_employeecommission_category_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorycommission',
            name='comission_choice',
            field=models.CharField(choices=[('percentage', 'percentage'), ('currency', 'currency')], default='percentage', max_length=50),
        ),
    ]
