# Generated by Django 4.0.6 on 2024-02-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0050_alter_employeeselectedservice_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcards',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='giftcards',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='giftcards',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='giftdetail',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='giftdetail',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='giftdetail',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
