# Generated by Django 4.0.6 on 2023-05-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0050_categorycommission_comission_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecommission',
            name='commission_amount',
            field=models.FloatField(default=0, verbose_name='Commission Amount get by Single Item Sold'),
        ),
        migrations.AlterField(
            model_name='employeecommission',
            name='commission_rate',
            field=models.FloatField(default=0, verbose_name='Commission Current rate for single sold item, Percentage/Price'),
        ),
        migrations.AlterField(
            model_name='employeecommission',
            name='item_name',
            field=models.CharField(default='', max_length=500, verbose_name='Sold Item Name'),
        ),
        migrations.AlterField(
            model_name='employeecommission',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Sold Items Quantity'),
        ),
        migrations.AlterField(
            model_name='employeecommission',
            name='sale_value',
            field=models.FloatField(default=0, verbose_name='Single Sold Item Current Price'),
        ),
    ]
