# Generated by Django 4.0.6 on 2024-02-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0051_giftcards_is_active_giftcards_is_blocked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcards',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
