# Generated by Django 4.0.6 on 2023-05-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0052_employeecommission_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecommission',
            name='tip',
            field=models.FloatField(default=0),
        ),
    ]
