# Generated by Django 4.0.6 on 2023-06-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0053_employeecommission_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecommission',
            name='sale_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
