# Generated by Django 4.0.6 on 2024-02-29 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0008_delete_refundsetting'),
        ('Employee', '0053_giftcards_retail_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcards',
            name='location_is',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Business.businessaddress'),
        ),
    ]
