# Generated by Django 4.0.6 on 2024-03-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0054_giftcards_location_is'),
    ]

    operations = [
        migrations.AddField(
            model_name='employedailyschedule',
            name='is_brake_time',
            field=models.BooleanField(default=False),
        ),
    ]
