# Generated by Django 4.0.6 on 2023-08-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0054_employeecommission_sale_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorycommission',
            name='commission_percentage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='categorycommission',
            name='from_value',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='commissionschemesetting',
            name='from_value',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='commissionschemesetting',
            name='percentage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='commissionschemesetting',
            name='to_value',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='employeeprofessionalinfo',
            name='maximum_discount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='employeeprofessionalinfo',
            name='salary',
            field=models.FloatField(default=0),
        ),
    ]
