# Generated by Django 4.0.6 on 2024-03-12 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0008_delete_refundsetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Employee', '0056_braketime'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTraining',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Cancel', 'Cancel'), ('Accept', 'Accept'), ('Reject', 'Reject'), ('Pending', 'Pending')], default='Pending', max_length=50)),
                ('skill', models.CharField(choices=[('Hair Cutting ', 'Hair Cutting '), ('Hair Coloring', 'Hair Coloring'), ('Waxing', 'Waxing'), ('Threading', 'Threading'), ('Facial', 'Facial'), ('Makeup', 'Makeup'), ('Skin Care', 'Skin Care')], max_length=50)),
                ('manager_feedback', models.TextField(blank=True, null=True)),
                ('teacher_comment', models.TextField(blank=True, null=True)),
                ('date_requested', models.DateField(blank=True, null=True)),
                ('date_offered', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_employee_training', to='Business.businessaddress')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manger_employee_training', to='Employee.employee')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_employee_training', to='Employee.employee')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_employee_training', to='Employee.employee')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_employee_training', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
