# Generated by Django 3.2.15 on 2022-10-15 13:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employee', '0020_auto_20221014_1252'),
        ('Utility', '0012_auto_20221015_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ManyToManyField(related_name='global_permissions_appointment', to='Utility.GlobalPermissionChoices', verbose_name='Appointment')),
                ('brand', models.ManyToManyField(to='Utility.GlobalPermissionChoices', verbose_name='Brand')),
                ('categories', models.ManyToManyField(related_name='global_permissions_categories', to='Utility.GlobalPermissionChoices', verbose_name='Categories')),
                ('email_staff', models.ManyToManyField(related_name='global_permissions_email_staff', to='Utility.GlobalPermissionChoices', verbose_name='Email to staff')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_permissions', to='Employee.employee')),
                ('membership', models.ManyToManyField(related_name='global_permissions_membership', to='Utility.GlobalPermissionChoices', verbose_name='Client Membership')),
                ('products', models.ManyToManyField(related_name='global_permissions_products', to='Utility.GlobalPermissionChoices', verbose_name='Products')),
                ('promotions', models.ManyToManyField(related_name='global_permissions_promotions', to='Utility.GlobalPermissionChoices', verbose_name='Client Promotions')),
                ('rewards', models.ManyToManyField(related_name='global_permissions_rewards', to='Utility.GlobalPermissionChoices', verbose_name='Client Rewards')),
                ('sale_membership', models.ManyToManyField(related_name='global_permissions_sale_membership', to='Utility.GlobalPermissionChoices', verbose_name='Sale Membership')),
                ('sale_product', models.ManyToManyField(related_name='global_permissions_sale_product', to='Utility.GlobalPermissionChoices', verbose_name='Sale Product')),
                ('sale_promotions', models.ManyToManyField(related_name='global_permissions_sale_promotions', to='Utility.GlobalPermissionChoices', verbose_name='Sale Promotions')),
                ('sale_report_membership', models.ManyToManyField(related_name='global_permissions_sale_report_membership', to='Utility.GlobalPermissionChoices', verbose_name='Sale Report Membership')),
                ('sale_report_product', models.ManyToManyField(related_name='global_permissions_sale_report_product', to='Utility.GlobalPermissionChoices', verbose_name='Sale Report Product')),
                ('sale_report_promotions', models.ManyToManyField(related_name='global_permissions_sale_report_promotions', to='Utility.GlobalPermissionChoices', verbose_name='Sale Report Promotions')),
                ('sale_report_rewards', models.ManyToManyField(related_name='global_permissions_sale_report_rewards', to='Utility.GlobalPermissionChoices', verbose_name='Sale Report Rewards')),
                ('sale_report_subscriptions', models.ManyToManyField(related_name='global_permissions_sale_report_subscriptions', to='Utility.GlobalPermissionChoices', verbose_name='Sale Report Subscriptions')),
                ('sale_report_vouchers', models.ManyToManyField(related_name='global_permissions_sale_report_vouchers', to='Utility.GlobalPermissionChoices', verbose_name='Sale Report Vouchers')),
                ('sale_rewards', models.ManyToManyField(related_name='global_permissions_sale_rewards', to='Utility.GlobalPermissionChoices', verbose_name='Sale Rewards')),
                ('sale_subscriptions', models.ManyToManyField(related_name='global_permissions_sale_subscriptions', to='Utility.GlobalPermissionChoices', verbose_name='Sale Subscriptions')),
                ('sale_vouchers', models.ManyToManyField(related_name='global_permissions_sale_vouchers', to='Utility.GlobalPermissionChoices', verbose_name='Sale Vouchers')),
                ('staff_data', models.ManyToManyField(related_name='global_permissions_staff_data', to='Utility.GlobalPermissionChoices', verbose_name='Staff Data')),
                ('staff_product_sales', models.ManyToManyField(related_name='global_permissions_staff_product_sales', to='Utility.GlobalPermissionChoices', verbose_name='Staff Assets')),
                ('stock', models.ManyToManyField(related_name='global_permissions_stock', to='Utility.GlobalPermissionChoices', verbose_name='Stock')),
                ('stock_report', models.ManyToManyField(related_name='global_permissions_stock_report', to='Utility.GlobalPermissionChoices', verbose_name='Stock Report')),
                ('subscriptions', models.ManyToManyField(related_name='global_permissions_subscriptions', to='Utility.GlobalPermissionChoices', verbose_name='Client Subscriptions')),
                ('vendors', models.ManyToManyField(related_name='global_permissions_vendors', to='Utility.GlobalPermissionChoices', verbose_name='Vendors')),
                ('vouchers', models.ManyToManyField(related_name='global_permissions_vouchers', to='Utility.GlobalPermissionChoices', verbose_name='Client Vouchers')),
            ],
        ),
    ]
