# Generated by Django 4.0.6 on 2024-01-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utility', '0001_initial_squashed_0018_state_unique_id'),
        ('Permissions', '0001_initial_squashed_0003_auto_20230220_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='employepermission',
            name='system_root_access',
            field=models.ManyToManyField(related_name='global_permissions_system_root_access', to='Utility.globalpermissionchoices', verbose_name='System Administration Root Access'),
        ),
    ]
