# Generated by Django 3.2.15 on 2022-10-18 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0020_auto_20221014_1252'),
        ('Permissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employepermission',
            name='staffgroup',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staffGroup_permissions', to='Employee.staffgroup'),
        ),
        migrations.AlterField(
            model_name='employepermission',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_permissions', to='Employee.employee'),
        ),
    ]
