# Generated by Django 3.2.18 on 2023-02-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utility', '0012_auto_20221015_1633'),
        ('Permissions', '0002_auto_20221018_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employepermission',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='employepermission',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='employepermission',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='employepermission',
            name='email_staff',
        ),
        migrations.RemoveField(
            model_name='employepermission',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='employepermission',
            name='products',
        ),
        migrations.RemoveField(
            model_name='employepermission',
            name='promotions',
        ),
        migrations.RemoveField(
            model_name='employepermission',
            name='rewards',
        ),
        migrations.RemoveField(
            model_name='employepermission',
            name='sale_membership',
        ),
        migrations.RemoveField(
            model_name='employepermission',
            name='sale_product',
        ),
        migrations.RemoveField(
            model_name='employepermission',
            name='sale_promotions',
        ),
        migrations.RemoveField(
            model_name='employepermission',
            name='sale_report_membership',
        ),
        migrations.RemoveField(
            model_name='employepermission',
            name='sale_report_product',
        ),
        migrations.RemoveField(
            model_name='employepermission',
            name='sale_report_promotions',
        ),
        migrations.RemoveField(
            model_name='employepermission',
            name='sale_report_rewards',
        ),
        migrations.RemoveField(
            model_name='employepermission',
            name='sale_report_subscriptions',
        ),
        migrations.RemoveField(
            model_name='employepermission',
            name='sale_report_vouchers',
        ),
        migrations.RemoveField(
            model_name='employepermission',
            name='sale_rewards',
        ),
        migrations.RemoveField(
            model_name='employepermission',
            name='sale_subscriptions',
        ),
        migrations.RemoveField(
            model_name='employepermission',
            name='sale_vouchers',
        ),
        migrations.RemoveField(
            model_name='employepermission',
            name='staff_data',
        ),
        migrations.RemoveField(
            model_name='employepermission',
            name='staff_product_sales',
        ),
        migrations.RemoveField(
            model_name='employepermission',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='employepermission',
            name='stock_report',
        ),
        migrations.RemoveField(
            model_name='employepermission',
            name='subscriptions',
        ),
        migrations.RemoveField(
            model_name='employepermission',
            name='vendors',
        ),
        migrations.RemoveField(
            model_name='employepermission',
            name='vouchers',
        ),
        migrations.AddField(
            model_name='employepermission',
            name='account_business_setting',
            field=models.ManyToManyField(related_name='global_permissions_account_business_setting', to='Utility.GlobalPermissionChoices', verbose_name='Account Business Setting'),
        ),
        migrations.AddField(
            model_name='employepermission',
            name='account_finance_setting',
            field=models.ManyToManyField(related_name='global_permissions_account_finance_setting', to='Utility.GlobalPermissionChoices', verbose_name='Account Finance Setting'),
        ),
        migrations.AddField(
            model_name='employepermission',
            name='account_notification_setting',
            field=models.ManyToManyField(related_name='global_permissions_account_notification_setting', to='Utility.GlobalPermissionChoices', verbose_name='Account Service Setting'),
        ),
        migrations.AddField(
            model_name='employepermission',
            name='account_root_access',
            field=models.ManyToManyField(related_name='global_permissions_account_root_access', to='Utility.GlobalPermissionChoices', verbose_name='Account Root Access'),
        ),
        migrations.AddField(
            model_name='employepermission',
            name='account_service_management',
            field=models.ManyToManyField(related_name='global_permissions_account_service_setting', to='Utility.GlobalPermissionChoices', verbose_name='Account Service Setting'),
        ),
        migrations.AddField(
            model_name='employepermission',
            name='calender_appointment',
            field=models.ManyToManyField(related_name='global_permissions_calender_appointment', to='Utility.GlobalPermissionChoices', verbose_name='Calender Appointment'),
        ),
        migrations.AddField(
            model_name='employepermission',
            name='calender_block_time',
            field=models.ManyToManyField(related_name='global_permissions_calender_block_time', to='Utility.GlobalPermissionChoices', verbose_name='Calender Block time'),
        ),
        migrations.AddField(
            model_name='employepermission',
            name='calender_root_access',
            field=models.ManyToManyField(related_name='global_permissions_calender_root_access', to='Utility.GlobalPermissionChoices', verbose_name='Calender Root Access'),
        ),
        migrations.AddField(
            model_name='employepermission',
            name='client_discount',
            field=models.ManyToManyField(related_name='global_permissions_client_discount', to='Utility.GlobalPermissionChoices', verbose_name='Client Discount/Promotions'),
        ),
        migrations.AddField(
            model_name='employepermission',
            name='client_groups',
            field=models.ManyToManyField(related_name='global_permissions_client_groups', to='Utility.GlobalPermissionChoices', verbose_name='Client Groups'),
        ),
        migrations.AddField(
            model_name='employepermission',
            name='client_list',
            field=models.ManyToManyField(related_name='global_permissions_client_list', to='Utility.GlobalPermissionChoices', verbose_name='Client list'),
        ),
        migrations.AddField(
            model_name='employepermission',
            name='client_loyality',
            field=models.ManyToManyField(related_name='global_permissions_client_loyality', to='Utility.GlobalPermissionChoices', verbose_name='Client loyality '),
        ),
        migrations.AddField(
            model_name='employepermission',
            name='client_profile',
            field=models.ManyToManyField(related_name='global_permissions_client_profile', to='Utility.GlobalPermissionChoices', verbose_name='Client Profile'),
        ),
        migrations.AddField(
            model_name='employepermission',
            name='client_reward',
            field=models.ManyToManyField(related_name='global_permissions_client_reward', to='Utility.GlobalPermissionChoices', verbose_name='Client Reward/Promotions'),
        ),
        migrations.AddField(
            model_name='employepermission',
            name='client_root_access',
            field=models.ManyToManyField(related_name='global_permissions_client_root_access', to='Utility.GlobalPermissionChoices', verbose_name='Client Root Access'),
        ),
        migrations.AddField(
            model_name='employepermission',
            name='client_sharing',
            field=models.ManyToManyField(related_name='global_permissions_client_sharing', to='Utility.GlobalPermissionChoices', verbose_name='Client Sharing Settings'),
        ),
        migrations.AddField(
            model_name='employepermission',
            name='employee_attendance',
            field=models.ManyToManyField(related_name='global_permissions_employee_attendance', to='Utility.GlobalPermissionChoices', verbose_name='Employee attendance'),
        ),
        migrations.AddField(
            model_name='employepermission',
            name='employee_commission',
            field=models.ManyToManyField(related_name='global_permissions_employee_commission', to='Utility.GlobalPermissionChoices', verbose_name='Employee Commission'),
        ),
        migrations.AddField(
            model_name='employepermission',
            name='employee_new',
            field=models.ManyToManyField(related_name='global_permissions_employee_new', to='Utility.GlobalPermissionChoices', verbose_name='New Employee'),
        ),
        migrations.AddField(
            model_name='employepermission',
            name='employee_payroll',
            field=models.ManyToManyField(related_name='global_permissions_employee_payroll', to='Utility.GlobalPermissionChoices', verbose_name='Employee Payroll'),
        ),
        migrations.AddField(
            model_name='employepermission',
            name='employee_reports',
            field=models.ManyToManyField(related_name='global_permissions_employee_reports', to='Utility.GlobalPermissionChoices', verbose_name='Employee Reports'),
        ),
        migrations.AddField(
            model_name='employepermission',
            name='employee_root_access',
            field=models.ManyToManyField(related_name='global_permissions_employee_root_access', to='Utility.GlobalPermissionChoices', verbose_name='Employee Root Access'),
        ),
        migrations.AddField(
            model_name='employepermission',
            name='employee_staff_group',
            field=models.ManyToManyField(related_name='global_permissions_employee_staff_group', to='Utility.GlobalPermissionChoices', verbose_name='Employee Staff Group'),
        ),
        migrations.AddField(
            model_name='employepermission',
            name='employee_vacation',
            field=models.ManyToManyField(related_name='global_permissions_employee_vacation', to='Utility.GlobalPermissionChoices', verbose_name='Employee Vacation'),
        ),
        migrations.AddField(
            model_name='employepermission',
            name='employee_work_schedule',
            field=models.ManyToManyField(related_name='global_permissions_employee_work', to='Utility.GlobalPermissionChoices', verbose_name='Employee Work Schedule'),
        ),
        migrations.AddField(
            model_name='employepermission',
            name='inventory_consumption',
            field=models.ManyToManyField(related_name='global_permissions_inventory_consumption', to='Utility.GlobalPermissionChoices', verbose_name='Inventory Consumption'),
        ),
        migrations.AddField(
            model_name='employepermission',
            name='inventory_goods_receipt',
            field=models.ManyToManyField(related_name='global_permissions_inventory_goods_receipt', to='Utility.GlobalPermissionChoices', verbose_name='Inventory Good Receipt'),
        ),
        migrations.AddField(
            model_name='employepermission',
            name='inventory_purchase_order',
            field=models.ManyToManyField(related_name='global_permissions_inventory_purchase_order', to='Utility.GlobalPermissionChoices', verbose_name='Inventory Purchase Order'),
        ),
        migrations.AddField(
            model_name='employepermission',
            name='inventory_report',
            field=models.ManyToManyField(related_name='global_permissions_inventory_report', to='Utility.GlobalPermissionChoices', verbose_name='Inventory Report'),
        ),
        migrations.AddField(
            model_name='employepermission',
            name='inventory_root_access',
            field=models.ManyToManyField(related_name='global_permissions_inventory_root_access', to='Utility.GlobalPermissionChoices', verbose_name='Inventory Root Access'),
        ),
        migrations.AddField(
            model_name='employepermission',
            name='inventory_stock_report',
            field=models.ManyToManyField(related_name='global_permissions_inventory_stock_report', to='Utility.GlobalPermissionChoices', verbose_name='Inventory Stock Report'),
        ),
        migrations.AddField(
            model_name='employepermission',
            name='inventory_stock_transfer',
            field=models.ManyToManyField(related_name='global_permissions_inventory_stock_transfer', to='Utility.GlobalPermissionChoices', verbose_name='Inventory Stock Transfer'),
        ),
        migrations.AddField(
            model_name='employepermission',
            name='mobile_root_access',
            field=models.ManyToManyField(related_name='global_permissions_mobile_root_access', to='Utility.GlobalPermissionChoices', verbose_name='Mobile Root Access'),
        ),
        migrations.AddField(
            model_name='employepermission',
            name='pos_root_access',
            field=models.ManyToManyField(related_name='global_permissions_pos_root_access', to='Utility.GlobalPermissionChoices', verbose_name='POS Root Access'),
        ),
        migrations.AddField(
            model_name='employepermission',
            name='product_root_access',
            field=models.ManyToManyField(related_name='global_permissions_product_root_access', to='Utility.GlobalPermissionChoices', verbose_name='Product Root Access'),
        ),
        migrations.AddField(
            model_name='employepermission',
            name='profile_list',
            field=models.ManyToManyField(related_name='global_permissions_profile_list', to='Utility.GlobalPermissionChoices', verbose_name='Profile List Access'),
        ),
        migrations.AddField(
            model_name='employepermission',
            name='profile_root_access',
            field=models.ManyToManyField(related_name='global_permissions_profile_root_access', to='Utility.GlobalPermissionChoices', verbose_name='Profile Root Access'),
        ),
        migrations.AddField(
            model_name='employepermission',
            name='reports_commission',
            field=models.ManyToManyField(related_name='global_permissions_reports_commission', to='Utility.GlobalPermissionChoices', verbose_name='Report Commission'),
        ),
        migrations.AddField(
            model_name='employepermission',
            name='reports_retail',
            field=models.ManyToManyField(related_name='global_permissions_reports_retail', to='Utility.GlobalPermissionChoices', verbose_name='Report Retail'),
        ),
        migrations.AddField(
            model_name='employepermission',
            name='reports_root_access',
            field=models.ManyToManyField(related_name='global_permissions_reports_root_access', to='Utility.GlobalPermissionChoices', verbose_name='Report Root Access'),
        ),
        migrations.AddField(
            model_name='employepermission',
            name='reports_service',
            field=models.ManyToManyField(related_name='global_permissions_reports_service', to='Utility.GlobalPermissionChoices', verbose_name='Report Service'),
        ),
        migrations.AddField(
            model_name='employepermission',
            name='reports_staff',
            field=models.ManyToManyField(related_name='global_permissions_reports_staff', to='Utility.GlobalPermissionChoices', verbose_name='Report Staff'),
        ),
        migrations.AddField(
            model_name='employepermission',
            name='reports_store',
            field=models.ManyToManyField(related_name='global_permissions_reports_store', to='Utility.GlobalPermissionChoices', verbose_name='Report Store'),
        ),
        migrations.AddField(
            model_name='employepermission',
            name='sales_apply_offer',
            field=models.ManyToManyField(related_name='global_permissions_sale_apply_offer', to='Utility.GlobalPermissionChoices', verbose_name='Sales Apply offer/Discount'),
        ),
        migrations.AddField(
            model_name='employepermission',
            name='sales_root_access',
            field=models.ManyToManyField(related_name='global_permissions_sale_root_access', to='Utility.GlobalPermissionChoices', verbose_name='Sales Root Access'),
        ),
        migrations.AddField(
            model_name='employepermission',
            name='target_control_retail',
            field=models.ManyToManyField(related_name='global_permissions_target_control_retail', to='Utility.GlobalPermissionChoices', verbose_name='Target Control Retail Target'),
        ),
        migrations.AddField(
            model_name='employepermission',
            name='target_control_service',
            field=models.ManyToManyField(related_name='global_permissions_target_control_service', to='Utility.GlobalPermissionChoices', verbose_name='Target Control Service Target'),
        ),
        migrations.AddField(
            model_name='employepermission',
            name='target_control_staff',
            field=models.ManyToManyField(related_name='global_permissions_target_control_staff', to='Utility.GlobalPermissionChoices', verbose_name='Target Control Staff Target'),
        ),
        migrations.AddField(
            model_name='employepermission',
            name='target_control_store',
            field=models.ManyToManyField(related_name='global_permissions_target_control_store', to='Utility.GlobalPermissionChoices', verbose_name='Target Control Store Target'),
        ),
    ]
