# Generated by Django 4.0.6 on 2023-12-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0001_initial_squashed_0056_alter_appointmentservice_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(blank=True, choices=[('booked', 'Booked'), ('started', 'Started'), ('finished', 'Finished'), ('done', 'Done'), ('cancelled', 'Cancelled')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointmentservice',
            name='status',
            field=models.CharField(blank=True, choices=[('booked', 'Booked'), ('started', 'Started'), ('finished', 'Finished'), ('void', 'Void')], max_length=100, null=True),
        ),
    ]
