# Generated by Django 4.0.6 on 2022-09-12 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0011_commissionschemesetting'),
        ('Service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Business', '0017_alter_adminnotificationsetting_sms_notify_for_daily_book_and_more'),
        ('Client', '0009_delete_rewards'),
        ('Appointment', '0002_checkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('duration', models.CharField(choices=[('30 MIN', '30 MIN'), ('45 MIN', '45 MIN'), ('1 HOUR', '1 HOUR')], default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='is_blocked',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='member',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
        migrations.AddField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_appointments', to='Client.client'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='client_type',
            field=models.CharField(blank=True, choices=[('IN HOUSE', 'IN HOUSE'), ('SALOON', 'SALOON')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='business_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_address', to='Business.businessaddress'),
        ),
        migrations.DeleteModel(
            name='Checkout',
        ),
        migrations.AddField(
            model_name='appointmentservice',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_services', to='Appointment.appointment'),
        ),
        migrations.AddField(
            model_name='appointmentservice',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_appointment_services', to='Business.business'),
        ),
        migrations.AddField(
            model_name='appointmentservice',
            name='business_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b_address_appointment_services', to='Business.businessaddress'),
        ),
        migrations.AddField(
            model_name='appointmentservice',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_appointments', to='Employee.employee'),
        ),
        migrations.AddField(
            model_name='appointmentservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serivce_appointments', to='Service.service'),
        ),
        migrations.AddField(
            model_name='appointmentservice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_appointment_services', to=settings.AUTH_USER_MODEL, verbose_name='Creator ( User )'),
        ),
    ]
