# Generated by Django 4.0.6 on 2023-12-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0002_appointment_status_appointmentservice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentservice',
            name='service_end_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='appointmentservice',
            name='service_start_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(blank=True, choices=[('Booked', 'Booked'), ('Started', 'Started'), ('Finished', 'Finished'), ('Done', 'Done'), ('cancelled', 'Cancelled')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentservice',
            name='status',
            field=models.CharField(blank=True, choices=[('Booked', 'Booked'), ('Started', 'Started'), ('Finished', 'Finished'), ('Void', 'Void')], max_length=100, null=True),
        ),
    ]
