# Generated by Django 4.0.6 on 2023-12-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0003_appointmentservice_service_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(blank=True, choices=[('Booked', 'Booked'), ('Started', 'Started'), ('Finished', 'Finished'), ('Done', 'Done'), ('Cancelled', 'Cancelled')], max_length=100, null=True),
        ),
    ]
