# Generated by Django 4.0.6 on 2022-09-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0003_appointmentservice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('Promotions', 'Promotions'), ('Rewards', 'Rewards'), ('Vouchers', 'Vouchers'), ('Memberships', 'Memberships'), ('Subscriptions', 'Subscriptions')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Voucher', 'Voucher'), ('SplitBill', 'SplitBill'), ('MasterCard', 'MasterCard'), ('Visa', 'Visa'), ('Paypal', 'Paypal'), ('GooglePay', 'Google Pay'), ('ApplePay', 'Apple Pay')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='appointmentservice',
            name='tip',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
