# Generated by Django 4.0.6 on 2023-12-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0003_appointmentservice_service_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentservice',
            name='service_end_time',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='appointmentservice',
            name='service_start_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
