# Generated by Django 4.0.6 on 2022-09-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0004_appointment_discount_type_appointment_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentservice',
            name='duration',
            field=models.CharField(choices=[('30 MIN', '30 MIN'), ('60 MIN', '60 MIN'), ('90 MIN', '90 MIN'), ('120 MIN', '120 MIN'), ('150 MIN', '150 MIN'), ('180 MIN', '180 MIN'), ('210 MIN', '210 MIN'), ('240 MIN', '240 MIN')], default='', max_length=100),
        ),
    ]
