# Generated by Django 4.0.6 on 2023-12-13 08:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial_squashed_0074_client_is_image_uploaded_s3'),
        ('Employee', '0001_initial_squashed_0056_employee_is_image_uploaded_s3'),
        ('Service', '0001_initial_squashed_0032_alter_service_initial_deposit_alter_service_price'),
        ('Appointment', '0004_alter_appointment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissedOpportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_missed_opportunities', to='Client.client')),
                ('employee', models.ManyToManyField(related_name='employee_missed_opportunities', to='Employee.employee')),
                ('service', models.ManyToManyField(related_name='service_missed_opportunities', to='Service.service')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
