# Generated by Django 4.0.6 on 2023-12-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0004_alter_appointmentservice_service_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentservice',
            name='service_end_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
