# Generated by Django 4.0.6 on 2023-12-14 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0001_initial_squashed_0032_alter_service_initial_deposit_alter_service_price'),
        ('Employee', '0001_initial_squashed_0056_employee_is_image_uploaded_s3'),
        ('Appointment', '0005_missedopportunity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missedopportunity',
            name='employee',
        ),
        migrations.AddField(
            model_name='missedopportunity',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_missed_opportunities', to='Employee.employee'),
        ),
        migrations.AlterField(
            model_name='missedopportunity',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='missedopportunity',
            name='service',
        ),
        migrations.AddField(
            model_name='missedopportunity',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_missed_opportunities', to='Service.service'),
        ),
        migrations.AlterField(
            model_name='missedopportunity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
