# Generated by Django 3.2.15 on 2022-09-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0005_alter_appointmentservice_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentservice',
            name='appointment_status',
            field=models.CharField(choices=[('Appointment_Booked', 'Appointment Booked'), ('Arrived', 'Arrived'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='Appointment Booked', max_length=100),
        ),
    ]
