# Generated by Django 3.2.15 on 2022-09-23 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0003_service_price'),
        ('Appointment', '0006_appointmentservice_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentservice',
            name='destails',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointmentservice',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentservice',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serivce_appointments', to='Service.service'),
        ),
    ]
