# Generated by Django 4.0.6 on 2023-12-14 06:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial_squashed_0074_client_is_image_uploaded_s3'),
        ('Service', '0001_initial_squashed_0032_alter_service_initial_deposit_alter_service_price'),
        ('Employee', '0001_initial_squashed_0056_employee_is_image_uploaded_s3'),
        ('Appointment', '0006_remove_missedopportunity_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missedopportunity',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='missedopportunity',
            name='service',
        ),
        migrations.AddField(
            model_name='missedopportunity',
            name='client_type',
            field=models.CharField(choices=[('IN HOUSE', 'IN HOUSE'), ('SALOON', 'SALOON')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='missedopportunity',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_missed_opportunities', to='Client.client'),
        ),
        migrations.CreateModel(
            name='OpportunityEmployeeService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField()),
                ('time', models.TimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_missed_opportunities', to='Employee.employee')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_missed_opportunities', to='Service.service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='missedopportunity',
            name='services',
            field=models.ManyToManyField(related_name='missed_opportunities', to='Appointment.opportunityemployeeservice'),
        ),
    ]
