# Generated by Django 4.0.6 on 2022-09-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0007_auto_20220923_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentservice',
            name='duration',
            field=models.CharField(choices=[('30 MIN', '30 Min'), ('60 MIN', '60 Min'), ('90 MIN', '90 Min'), ('120 MIN', '120 Min'), ('150 MIN', '150 Min'), ('180 MIN', '180 Min'), ('210 MIN', '210 Min'), ('240 MIN', '240 Min')], default='', max_length=100),
        ),
    ]
