# Generated by Django 4.0.6 on 2022-09-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0008_alter_appointmentservice_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentservice',
            name='duration',
            field=models.CharField(choices=[('30 Min', '30 Min'), ('60 Min', '60 Min'), ('90 Min', '90 Min'), ('120 Min', '120 Min'), ('150 Min', '150 Min'), ('180 Min', '180 Min'), ('210 Min', '210 Min'), ('240 Min', '240 Min')], default='', max_length=100),
        ),
    ]
