# Generated by Django 3.2.15 on 2022-10-04 12:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0009_alter_appointmentservice_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentNotes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField(default='')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_notes', to='Appointment.appointment')),
            ],
        ),
    ]
