# Generated by Django 4.0.6 on 2023-12-14 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0009_clientmissedopportunity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunityemployeeservice',
            name='client_missed_opportunity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missed_opportunities', to='Appointment.clientmissedopportunity'),
        ),
    ]
