# Generated by Django 4.0.6 on 2023-12-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0010_alter_opportunityemployeeservice_client_missed_opportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmissedopportunity',
            name='dependency',
            field=models.CharField(blank=True, choices=[('Technician', 'Technician'), ('Out of stock', 'Out of stock')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientmissedopportunity',
            name='client_type',
            field=models.CharField(blank=True, choices=[('IN HOUSE', 'IN HOUSE'), ('SALOON', 'SALOON')], max_length=200, null=True),
        ),
    ]
