# Generated by Django 3.2.15 on 2022-10-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0010_appointmentnotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Voucher', 'Voucher'), ('SplitBill', 'SplitBill'), ('MasterCard', 'MasterCard'), ('Visa', 'Visa'), ('Paypal', 'Paypal'), ('GooglePay', 'Google Pay'), ('ApplePay', 'Apple Pay')], default='', max_length=100, null=True),
        ),
    ]
