# Generated by Django 3.2.15 on 2022-10-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0011_alter_appointment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentnotes',
            name='text',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
