# Generated by Django 4.0.6 on 2023-12-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0012_appointment_cancel_note_appointment_cancel_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmissedopportunity',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
