# Generated by Django 3.2.15 on 2022-10-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0012_alter_appointmentnotes_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentservice',
            name='appointment_status',
            field=models.CharField(choices=[('Appointment_Booked', 'Appointment Booked'), ('Arrived', 'Arrived'), ('In Progress', 'In Progress'), ('Done', 'Done'), ('Cancel', 'Cancel')], default='Appointment Booked', max_length=100),
        ),
    ]
