# Generated by Django 4.0.6 on 2023-12-20 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0002_businessaddress_privacy_policy'),
        ('Appointment', '0013_alter_clientmissedopportunity_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmissedopportunity',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_missed_opportunities', to='Business.businessaddress'),
        ),
    ]
