# Generated by Django 3.2.15 on 2022-10-20 05:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0020_auto_20221014_1252'),
        ('Service', '0013_auto_20221019_1035'),
        ('Appointment', '0013_alter_appointmentservice_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentservice',
            name='appointment_status',
            field=models.CharField(choices=[('Appointment_Booked', 'Appointment Booked'), ('Arrived', 'Arrived'), ('In Progress', 'In Progress'), ('Done', 'Done'), ('Paid', 'Paid'), ('Cancel', 'Cancel')], default='Appointment Booked', max_length=100),
        ),
        migrations.CreateModel(
            name='AppointmentCheckout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('payment_method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Voucher', 'Voucher'), ('SplitBill', 'SplitBill'), ('MasterCard', 'MasterCard'), ('Visa', 'Visa'), ('Paypal', 'Paypal'), ('GooglePay', 'Google Pay'), ('ApplePay', 'Apple Pay')], default='', max_length=100, null=True)),
                ('tip', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('gst', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('service_price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('total_price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_checkout', to='Appointment.appointment')),
                ('appointment_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_service_checkout', to='Appointment.appointmentservice')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkout_member_appointments', to='Employee.employee')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkout_service_appointments', to='Service.service')),
            ],
        ),
    ]
