# Generated by Django 4.0.6 on 2023-12-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0014_clientmissedopportunity_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentcheckout',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
