# Generated by Django 3.2.15 on 2022-10-20 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0022_business_is_completed'),
        ('Appointment', '0014_auto_20221020_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentcheckout',
            name='business_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_address_checkout', to='Business.businessaddress'),
        ),
    ]
