# Generated by Django 3.2.15 on 2022-10-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0015_appointmentcheckout_business_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentservice',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
