# Generated by Django 4.0.6 on 2023-12-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0018_appointmentcheckout_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentcheckout',
            name='is_coupon_redeemed',
            field=models.TextField(null=True),
        ),
    ]
