# Generated by Django 3.2.15 on 2022-12-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0019_rename_destails_appointmentservice_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentservice',
            name='duration',
            field=models.CharField(default='', max_length=100),
        ),
    ]
