# Generated by Django 4.0.6 on 2023-12-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0019_appointmentcheckout_is_coupon_redeemed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmissedopportunity',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='opportunityemployeeservice',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
