# Generated by Django 4.0.6 on 2023-12-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0020_alter_clientmissedopportunity_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmissedopportunity',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='opportunityemployeeservice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
