# Generated by Django 3.2.15 on 2023-01-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0020_alter_appointmentservice_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentservice',
            name='appointment_time',
            field=models.TimeField(verbose_name='Appointment Start Time'),
        ),
    ]
