# Generated by Django 4.0.6 on 2024-01-12 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0021_alter_clientmissedopportunity_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentcheckout',
            name='is_refund',
            field=models.CharField(blank=True, choices=[('refund', 'Refund'), ('cancel', 'Cancel')], default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointmentcheckout',
            name='previous_appointment_refund_checkout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_checkout', to='Appointment.appointmentcheckout'),
        ),
    ]
