# Generated by Django 4.0.6 on 2023-12-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0021_alter_clientmissedopportunity_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmissedopportunity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='opportunityemployeeservice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
