# Generated by Django 3.2.15 on 2023-02-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0021_alter_appointmentservice_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentservice',
            name='service_commission',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='appointmentservice',
            name='service_commission_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
