# Generated by Django 4.0.6 on 2024-01-16 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0023_appointmentservice_is_refund_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentcheckout',
            old_name='previous_appointment_refund_checkout',
            new_name='previous_checkout',
        ),
        migrations.RemoveField(
            model_name='appointmentservice',
            name='is_refund',
        ),
        migrations.RemoveField(
            model_name='appointmentservice',
            name='previous_app_service_refunded',
        ),
    ]
