# Generated by Django 3.2.15 on 2023-02-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0023_auto_20230202_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentservice',
            name='client_can_book',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentservice',
            name='slot_availible_for_online',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
