# Generated by Django 4.0.6 on 2024-01-23 12:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0007_alter_businesstheme_menu_option'),
        ('Appointment', '0024_rename_previous_appointment_refund_checkout_appointmentcheckout_previous_checkout_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reversal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(null=True)),
                ('request_status', models.TextField(default='void', null=True)),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Appointment.appointment')),
                ('appointment_services', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Appointment.appointmentservice')),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Business.business')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
