# Generated by Django 4.0.6 on 2024-01-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0024_rename_previous_appointment_refund_checkout_appointmentcheckout_previous_checkout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentservice',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
