# Generated by Django 3.2.15 on 2023-02-06 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0040_alter_employedailyschedule_date'),
        ('Appointment', '0024_auto_20230203_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_appointments_lg', to='Employee.employee'),
        ),
    ]
