# Generated by Django 3.2.18 on 2023-02-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0025_appointment_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='extra_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
