# Generated by Django 3.2.18 on 2023-02-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0026_appointment_extra_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='tip',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
