# Generated by Django 4.0.6 on 2024-01-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0027_reversal_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='reversal',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reversal',
            name='client_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reversal',
            name='client_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reversal',
            name='service_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
