# Generated by Django 4.0.6 on 2024-01-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0028_reversal_appointment_date_reversal_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reversal',
            name='phone_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
