# Generated by Django 3.2.18 on 2023-02-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0028_appointment_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='service_commission',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service_commission_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
