# Generated by Django 3.2.18 on 2023-02-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0029_auto_20230223_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_checkout',
            field=models.BooleanField(default=False),
        ),
    ]
