# Generated by Django 4.0.6 on 2024-01-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0029_reversal_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='reversal',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
