# Generated by Django 3.2.18 on 2023-03-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0030_appointment_is_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentcheckout',
            name='service_commission',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='appointmentcheckout',
            name='service_commission_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
