# Generated by Django 4.0.6 on 2024-01-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0030_reversal_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='reversal',
            name='generated_by',
            field=models.TextField(blank=True, null=True),
        ),
    ]
