# Generated by Django 3.2.18 on 2023-03-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0031_auto_20230301_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='discount_percentage',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='appointmentservice',
            name='discount_percentage',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='appointmentservice',
            name='discount_price',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='appointmentservice',
            name='total_price',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
