# Generated by Django 4.0.6 on 2024-01-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0031_reversal_generated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reversal',
            name='request_status',
            field=models.TextField(default='', null=True),
        ),
    ]
