# Generated by Django 4.0.6 on 2024-01-28 15:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0032_alter_reversal_request_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('appointment', models.ManyToManyField(blank=True, null=True, related_name='appointment_group', to='Appointment.appointment')),
            ],
        ),
    ]
