# Generated by Django 3.2.18 on 2023-03-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0033_appointmentcheckout_gst_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentcheckout',
            name='gst_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
