# Generated by Django 4.0.6 on 2024-01-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0033_appointmentgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentgroup',
            name='group_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
