# Generated by Django 4.0.6 on 2023-04-13 10:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0043_alter_employee_email'),
        ('Appointment', '0034_alter_appointmentcheckout_gst_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentLogs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('log_type', models.CharField(blank=True, choices=[('Create', 'Create'), ('Edit', 'Edit'), ('Reschedule', 'Reschedule'), ('Cancel', 'Cancel')], max_length=50, null=True)),
                ('customer_type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointmentlogs_staffname', to='Employee.employee')),
            ],
        ),
    ]
