# Generated by Django 4.0.6 on 2023-04-14 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0028_businessaddress_description'),
        ('Appointment', '0035_appointmentlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentlogs',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointmentlogs_service_type', to='Appointment.appointment'),
        ),
        migrations.AddField(
            model_name='appointmentlogs',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointmentlogs_location', to='Business.businessaddress'),
        ),
    ]
