# Generated by Django 5.0.2 on 2024-02-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0035_appointment_comments_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentservice',
            name='reason',
        ),
        migrations.AddField(
            model_name='appointmentservice',
            name='service_void_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
