# Generated by Django 4.0.6 on 2023-04-17 10:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0043_alter_employee_email'),
        ('Appointment', '0036_appointmentlogs_appointment_appointmentlogs_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('start_time', models.TimeField()),
                ('duration', models.CharField(default='', max_length=400)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_service_logs', to='Appointment.appointmentservice')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_log_details', to='Appointment.appointmentlogs')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_log_details', to='Employee.employee')),
            ],
        ),
    ]
