# Generated by Django 5.0.2 on 2024-02-10 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0037_rename_comments_appointmentcomments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppointmentComments',
        ),
    ]
