# Generated by Django 4.0.6 on 2023-04-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0037_logdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentlogs',
            name='customer_type',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
