# Generated by Django 4.0.6 on 2023-04-27 10:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0045_employedailyschedule_vacation'),
        ('Business', '0028_businessaddress_description'),
        ('Appointment', '0038_alter_appointmentlogs_customer_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentEmployeeTip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tip', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('gst', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('gst_price', models.FloatField(blank=True, default=0, null=True)),
                ('service_price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('total_price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tips_checkout', to='Appointment.appointment')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_appointment_tips', to='Business.business')),
                ('business_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_address_tips', to='Business.businessaddress')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkout_member_tips', to='Employee.employee')),
            ],
        ),
    ]
