# Generated by Django 4.0.6 on 2024-02-12 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0039_appointment_check_in_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='group_appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_appointment_comment', to='Appointment.appointmentgroup'),
        ),
    ]
