# Generated by Django 4.0.6 on 2024-02-14 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0008_delete_refundsetting'),
        ('Appointment', '0040_comment_group_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reversal',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_reversal', to='Business.businessaddress'),
        ),
    ]
