# Generated by Django 4.0.6 on 2023-05-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0040_appointmentcheckout_is_promotion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentcheckout',
            name='service_commission',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=8, null=True),
        ),
    ]
