# Generated by Django 4.0.6 on 2024-02-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0041_reversal_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentgroup',
            name='group_check_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
