# Generated by Django 4.0.6 on 2023-05-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0041_alter_appointmentcheckout_service_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentcheckout',
            name='gst',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=5, null=True),
        ),
    ]
