# Generated by Django 4.0.6 on 2023-05-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0042_alter_appointmentcheckout_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_promotion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='selected_promotion_id',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AddField(
            model_name='appointment',
            name='selected_promotion_type',
            field=models.CharField(default='', max_length=400),
        ),
    ]
