# Generated by Django 4.0.6 on 2024-02-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0042_appointmentgroup_group_check_in_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_discount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
