# Generated by Django 4.0.6 on 2023-06-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0044_appointmentemployeetip_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentservice',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
