# Generated by Django 4.0.6 on 2024-02-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0045_alter_appointment_appointment_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentgroup',
            name='group_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
