# Generated by Django 4.0.6 on 2023-06-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0045_alter_appointmentservice_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentservice',
            name='discount_percentage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentservice',
            name='discount_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
