# Generated by Django 4.0.6 on 2023-06-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0046_alter_appointmentservice_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentlogs',
            name='log_type',
            field=models.CharField(blank=True, choices=[('Create', 'Create'), ('Edit', 'Edit'), ('Reschedule', 'Reschedule'), ('Cancel', 'Cancel'), ('done', 'Done')], max_length=50, null=True),
        ),
    ]
