# Generated by Django 4.0.6 on 2024-03-04 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0008_delete_refundsetting'),
        ('Appointment', '0046_appointmentgroup_group_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_comment', to='Business.businessaddress'),
        ),
    ]
