# Generated by Django 4.0.6 on 2023-07-31 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Appointment', '0047_alter_appointmentlogs_log_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentlogs',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_appointments_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
