# Generated by Django 4.0.6 on 2024-03-06 12:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0056_braketime'),
        ('Business', '0008_delete_refundsetting'),
        ('Service', '0006_alter_service_service_availible_and_more'),
        ('Appointment', '0047_comment_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeUpAndDownSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('old_price', models.FloatField(blank=True, default=0, null=True)),
                ('new_price', models.FloatField(blank=True, default=0, null=True)),
                ('price_difference', models.FloatField(blank=True, default=0, null=True)),
                ('status', models.CharField(choices=[('UpSale', 'UpSale'), ('DownSale', 'DownSale')], max_length=30)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_up_and_down_sale', to='Employee.employee')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_up_and_down_sale', to='Business.businessaddress')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_up_and_down_sale', to='Service.service')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
