# Generated by Django 4.0.6 on 2023-08-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0048_appointmentlogs_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentemployeetip',
            name='gst',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentemployeetip',
            name='service_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentemployeetip',
            name='tip',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentemployeetip',
            name='total_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
