# Generated by Django 4.0.6 on 2024-03-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0048_employeeupanddownsale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeupanddownsale',
            name='status',
            field=models.CharField(choices=[('Up-Sell', 'Up-Sell'), ('Down-Sell', 'Down-Sell')], max_length=30),
        ),
    ]
