# Generated by Django 4.0.6 on 2023-08-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0050_alter_appointmentcheckout_service_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='discount_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='extra_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='tip',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentcheckout',
            name='tip',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentservice',
            name='tip',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
