# Generated by Django 4.0.6 on 2023-08-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0051_alter_appointment_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='discount_percentage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service_commission',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentservice',
            name='service_commission',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentservice',
            name='total_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
