# Generated by Django 4.0.6 on 2023-08-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0052_alter_appointment_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentcheckout',
            name='gst1',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='appointmentcheckout',
            name='gst_price1',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
