# Generated by Django 4.0.6 on 2023-08-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0053_appointmentcheckout_gst1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentcheckout',
            name='tax_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='appointmentcheckout',
            name='tax_name1',
            field=models.CharField(default='', max_length=250),
        ),
    ]
