# Generated by Django 4.0.6 on 2023-08-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0054_appointmentcheckout_tax_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentservice',
            name='is_redeemed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointmentservice',
            name='redeemed_instance_id',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AddField(
            model_name='appointmentservice',
            name='redeemed_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='appointmentservice',
            name='redeemed_type',
            field=models.CharField(default='', max_length=300),
        ),
    ]
