# Generated by Django 4.0.6 on 2023-09-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0055_appointmentservice_is_redeemed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentservice',
            name='discount_price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
