# Generated by Django 4.0.6 on 2023-12-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0002_alter_holiday_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
