# Generated by Django 4.0.6 on 2023-12-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0004_alter_holiday_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
