# Generated by Django 4.0.6 on 2023-12-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0005_alter_holiday_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
