# Generated by Django 4.0.6 on 2024-01-10 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0018_leavemanagements_operational_annual_leave_and_more'),
        ('HRM', '0007_alter_holiday_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='employee_schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Employee.employedailyschedule'),
            preserve_default=False,
        ),
    ]
