# Generated by Django 4.0.6 on 2023-11-01 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('MultiLanguage', '0001_initial'), ('MultiLanguage', '0002_alter_labels_section'), ('MultiLanguage', '0003_invoicetranslation'), ('MultiLanguage', '0004_invoicetranslation_status_and_more'), ('MultiLanguage', '0005_invoicetranslation_user'), ('MultiLanguage', '0006_translationlabels')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=132, null=True)),
                ('icon', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=132, null=True)),
                ('icon', models.TextField(blank=True, null=True)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='MultiLanguage.language')),
            ],
        ),
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(blank=True, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='language_sections', to='MultiLanguage.section')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.CharField(blank=True, max_length=500, null=True)),
                ('items', models.CharField(blank=True, max_length=500, null=True)),
                ('amount', models.CharField(blank=True, max_length=500, null=True)),
                ('subtotal', models.CharField(blank=True, max_length=500, null=True)),
                ('tips', models.CharField(blank=True, max_length=500, null=True)),
                ('taxes', models.CharField(blank=True, max_length=500, null=True)),
                ('total', models.CharField(blank=True, max_length=500, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=500, null=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Utility.language')),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TranslationLabels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(blank=True, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('english_name', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='MultiLanguage.language')),
            ],
            options={
                'ordering': ['-order'],
            },
        ),
    ]
