# Generated by Django 4.0.6 on 2024-02-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultiLanguage', '0001_initial_squashed_0006_translationlabels'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicetranslation',
            name='change',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
