# Generated by Django 4.0.6 on 2023-07-20 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MultiLanguage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labels',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='language_sections', to='MultiLanguage.section'),
        ),
    ]
