# Generated by Django 4.0.6 on 2023-07-20 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Utility', '0013_turnoverproductrecord'),
        ('Business', '0029_businessaddress_is_default'),
        ('MultiLanguage', '0002_alter_labels_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.CharField(max_length=500)),
                ('items', models.CharField(max_length=500)),
                ('amount', models.CharField(max_length=500)),
                ('subtotal', models.CharField(max_length=500)),
                ('tips', models.CharField(max_length=500)),
                ('taxes', models.CharField(max_length=500)),
                ('total', models.CharField(max_length=500)),
                ('payment_method', models.CharField(max_length=500)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Utility.language')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Business.businessaddress')),
            ],
        ),
    ]
