# Generated by Django 4.0.6 on 2023-07-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultiLanguage', '0003_invoicetranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicetranslation',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoicetranslation',
            name='amount',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='invoicetranslation',
            name='invoice',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='invoicetranslation',
            name='items',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='invoicetranslation',
            name='payment_method',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='invoicetranslation',
            name='subtotal',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='invoicetranslation',
            name='taxes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='invoicetranslation',
            name='tips',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='invoicetranslation',
            name='total',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
