# Generated by Django 4.0.6 on 2023-07-24 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MultiLanguage', '0004_invoicetranslation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicetranslation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
