# Generated by Django 3.2.15 on 2022-09-15 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0017_alter_adminnotificationsetting_sms_notify_for_daily_book_and_more'),
        ('Service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_services', to='Business.business'),
        ),
    ]
