# Generated by Django 4.0.6 on 2024-01-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0001_initial_squashed_0032_alter_service_initial_deposit_alter_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service/service_images/'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_image_uploaded_s3',
            field=models.BooleanField(default=False),
        ),
    ]
