# Generated by Django 4.0.6 on 2024-01-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0002_service_image_service_is_image_uploaded_s3'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicegroup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='servicegroup/service_group_images/'),
        ),
        migrations.AddField(
            model_name='servicegroup',
            name='is_image_uploaded_s3',
            field=models.BooleanField(default=False),
        ),
    ]
