# Generated by Django 4.0.6 on 2024-02-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0003_servicegroup_image_servicegroup_is_image_uploaded_s3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
