# Generated by Django 3.2.15 on 2022-10-04 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0019_asset_assetdocument'),
        ('Business', '0021_businessaddress_banking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Service', '0003_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='employee',
            field=models.ManyToManyField(related_name='employee_services_or_packages', to='Employee.Employee'),
        ),
        migrations.AddField(
            model_name='service',
            name='enable_team_comissions',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Enable Team Member Comission'),
        ),
        migrations.AddField(
            model_name='service',
            name='enable_vouchers',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='is_package',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_services_or_packages', to='Business.businessaddress'),
        ),
        migrations.AddField(
            model_name='service',
            name='parrent_service',
            field=models.ManyToManyField(blank=True, null=True, related_name='parent_package_services', to='Service.Service'),
        ),
        migrations.AddField(
            model_name='service',
            name='treatment_type',
            field=models.CharField(blank=True, choices=[('Hair_Color', 'Hair Color'), ('test2', 'test2')], default='test2', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_services_or_packages', to='Business.business'),
        ),
        migrations.AlterField(
            model_name='service',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_services_or_packages', to=settings.AUTH_USER_MODEL),
        ),
    ]
