# Generated by Django 4.0.6 on 2024-02-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0004_alter_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='client_can_book',
            field=models.CharField(blank=True, choices=[('Anytime', 'Anytime'), ('5_Hours_Before', '5 Hours Before'), ('12_Hours_Before', '12 Hours Before'), ('24_Hours_Before', '24 Hours Before'), ('36_Hours_Before', '36 Hours Before')], default='Anytime', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='controls_time_slot',
            field=models.CharField(blank=True, choices=[('30_Mins', '30 Mins'), ('60_Mins', '60 Mins'), ('90_Mins', '90 Mins'), ('120_Mins', '120 Mins')], default='30_Mins', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='slot_availible_for_online',
            field=models.CharField(blank=True, choices=[('Anytime_In_The_Future', 'Anytime In The Future'), ('No_More_Than_1_Months_In_The_Future', 'No More Than 1 Months In The Future'), ('No_More_Than_2_Months_In_The_Future', 'No More Than 2 Months In The Future'), ('No_More_Than_3_Months_In_The_Future', 'No More Than 3 Months In The Future')], default='Anytime_In_The_Future', max_length=255, null=True),
        ),
    ]
