# Generated by Django 4.0.6 on 2024-02-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0005_alter_service_client_can_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_availible',
            field=models.CharField(blank=True, choices=[('Everyone', 'Everyone'), ('Male', 'Male'), ('Female', 'Female')], default='Everyone', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicegroup',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
