# Generated by Django 3.2.15 on 2022-10-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0005_alter_service_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='client_can_book',
            field=models.CharField(choices=[('Anytime', 'Anytime'), ('5_Hours_Before', '5 Hours Before'), ('12_Hours_Before', '12 Hours Before'), ('24_Hours_Before', '24 Hours Before'), ('36_Hours_Before', '36 Hours Before')], default='Anytime', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='controls_time_slot',
            field=models.CharField(choices=[('Anytime_In_The_Future', 'Anytime In The Future'), ('No_More_Than_1_Months_In_The_Future', 'No More Than 1 Months In The Future'), ('No_More_Than_2_Months_In_The_Future', 'No More Than 2 Months In The Future'), ('No_More_Than_3_Months_In_The_Future', 'No More Than 3 Months In The Future')], default='Anytime_In_The_Future', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='initial_deposit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
