# Generated by Django 3.2.15 on 2022-10-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0009_auto_20221017_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='controls_time_slot',
            field=models.CharField(choices=[('30_Mins', '30 Mins'), ('60_Mins', '60 Mins'), ('90_Mins', '90 Mins'), ('120_Mins', '120 Mins')], default='30_Mins', max_length=100),
        ),
    ]
