# Generated by Django 3.2.15 on 2022-10-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0011_auto_20221017_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='initial_deposit',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
