# Generated by Django 3.2.15 on 2022-10-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0012_alter_service_initial_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
