# Generated by Django 3.2.15 on 2022-10-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0017_alter_service_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(blank=True, choices=[('Waxing', 'Waxing'), ('Tanning', 'Tanning'), ('Massages', 'Massages'), ('Makeup', 'Makeup'), ('Hair_Services', 'Hair Services'), ('Nail_Treatments', 'Nail Treatments'), ('Hand_&_Feet_Treatment', 'Hand & Feet Treatment'), ('Facials_and_Skin_Care_Treatments', 'Hand & Feet Treatment')], max_length=50, null=True),
        ),
    ]
