# Generated by Django 3.2.15 on 2022-11-01 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0022_business_is_completed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Service', '0018_alter_service_service_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_servicesgroup', to='Business.business')),
                ('services', models.ManyToManyField(blank=True, null=True, related_name='servicegroup_services', to='Service.Service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_servicesgroup', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
