# Generated by Django 3.2.15 on 2022-11-08 04:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0019_servicegroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_type',
        ),
        migrations.AddField(
            model_name='service',
            name='service_availible',
            field=models.CharField(blank=True, choices=[('Waxing', 'Waxing'), ('Tanning', 'Tanning'), ('Massages', 'Massages'), ('Makeup', 'Makeup'), ('Hair_Services', 'Hair Services'), ('Nail_Treatments', 'Nail Treatments'), ('Hand_&_Feet_Treatment', 'Hand & Feet Treatment'), ('Facials_and_Skin_Care_Treatments', 'Hand & Feet Treatment')], default='Everyone', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='PriceService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('duration', models.CharField(blank=True, choices=[('30 Min', '30 Min'), ('60 Min', '60 Min'), ('90 Min', '90 Min'), ('120 Min', '120 Min'), ('150 Min', '150 Min'), ('180 Min', '180 Min'), ('210 Min', '210 Min'), ('240 Min', '240 Min')], max_length=50, null=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_priceservice', to='Service.service')),
            ],
        ),
    ]
