# Generated by Django 3.2.15 on 2022-11-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0020_auto_20221108_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_availible',
            field=models.CharField(blank=True, choices=[('Everyone', 'Everyone'), ('Male', 'Male'), ('Female', 'Female')], default='Everyone', max_length=50, null=True),
        ),
    ]
