# Generated by Django 3.2.15 on 2022-12-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0022_alter_priceservice_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicegroup',
            name='allow_client_to_select_team_member',
            field=models.BooleanField(default=False),
        ),
    ]
