# Generated by Django 3.2.15 on 2023-01-07 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Utility', '0012_auto_20221015_1633'),
        ('Service', '0023_servicegroup_allow_client_to_select_team_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceservice',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priceservice_currency', to='Utility.currency'),
        ),
    ]
