# Generated by Django 4.0.6 on 2023-05-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0024_priceservice_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
