# Generated by Django 4.0.6 on 2023-06-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0025_service_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceservice',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
