# Generated by Django 4.0.6 on 2023-07-12 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0028_service_urdu_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='urdu_name',
            new_name='arabic_name',
        ),
    ]
