# Generated by Django 4.0.6 on 2023-07-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0030_service_arabic_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='arabic_id',
            field=models.CharField(default='', editable=False, max_length=999, unique=True),
        ),
    ]
