# Generated by Django 4.0.6 on 2023-08-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0031_servicetranlations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='initial_deposit',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
