# Generated by Django 4.0.6 on 2023-11-01 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('Reports', '0001_initial'), ('Reports', '0002_rename_total_price_discountpromotionsalesreport_original_price'), ('Reports', '0003_alter_discountpromotionsalesreport_gst'), ('Reports', '0004_salereport')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Business', '0001_initial_squashed_0038_alter_businessvendor_email'),
        ('Invoices', '0004_saleinvoice_checkout'),
        ('Client', '0069_alter_loyaltypoints_number_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountPromotionSalesReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('checkout_id', models.CharField(default='', max_length=900)),
                ('checkout_type', models.CharField(choices=[('Sale', 'Sale'), ('Appointment', 'Appointment')], default='Sale', max_length=20)),
                ('promotion_id', models.CharField(default='', max_length=900)),
                ('promotion_type', models.CharField(default='', max_length=900)),
                ('promotion_name', models.CharField(default='', max_length=900)),
                ('quantity', models.PositiveBigIntegerField(default=0)),
                ('gst', models.FloatField(default=0)),
                ('original_price', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('discount_percentage', models.FloatField(default=0)),
                ('discount_price', models.FloatField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_discount_sales', to='Client.client')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_discount_sales', to='Invoices.saleinvoice')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_discount_sales', to='Business.businessaddress')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_discount_sales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SaleReport',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('instance_id', models.CharField(default='', max_length=999)),
                ('sale_type', models.CharField(choices=[('Service', 'Service'), ('Product', 'Product')], default='Service', max_length=999)),
                ('name', models.CharField(default='', max_length=999)),
                ('total_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
