# Generated by Django 4.0.6 on 2023-12-28 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial_squashed_0074_client_is_image_uploaded_s3'),
        ('Business', '0004_rename_refund_days_refundsetting_number_of_days_and_more'),
        ('Promotions', '0027_alter_coupon_usage_limit_alter_coupon_user_limit'),
        ('Invoices', '0001_initial_squashed_0007_remove_saleinvoice_checkout_obj'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Reports', '0001_initial_squashed_0004_salereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('checkout_id', models.TextField(null=True)),
                ('checkout_type', models.TextField(null=True)),
                ('coupon_type', models.TextField(null=True)),
                ('coupon_name', models.TextField(null=True)),
                ('quantity', models.PositiveBigIntegerField(default=0)),
                ('gst', models.FloatField(default=0)),
                ('original_price', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('discount_percentage', models.FloatField(default=0)),
                ('discount_price', models.FloatField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_coupon', to='Client.client')),
                ('coupon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Promotions.coupon')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_coupon_sale', to='Invoices.saleinvoice')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_coupon', to='Business.businessaddress')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_coupon', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
