# Generated by Django 4.0.6 on 2023-07-05 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discountpromotionsalesreport',
            old_name='total_price',
            new_name='original_price',
        ),
    ]
