# Generated by Django 4.0.6 on 2023-08-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0002_rename_total_price_discountpromotionsalesreport_original_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountpromotionsalesreport',
            name='gst',
            field=models.FloatField(default=0),
        ),
    ]
