# Generated by Django 4.0.6 on 2023-12-28 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Promotions', '0027_alter_coupon_usage_limit_alter_coupon_user_limit'),
        ('Reports', '0003_alter_couponreport_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponreport',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_reports', to='Promotions.coupon'),
        ),
    ]
