# Generated by Django 4.0.6 on 2023-10-25 09:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0003_alter_discountpromotionsalesreport_gst'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleReport',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('instance_id', models.CharField(default='', max_length=999)),
                ('sale_type', models.CharField(choices=[('Service', 'Service'), ('Product', 'Product')], default='Service', max_length=999)),
                ('name', models.CharField(default='', max_length=999)),
                ('total_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
