# Generated by Django 3.2.15 on 2022-12-13 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0023_servicegroup_allow_client_to_select_team_member'),
        ('Business', '0022_business_is_completed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Product', '0031_remove_orderstock_location_orderstock_from_location_and_more'),
        ('TragetControl', '0002_storetarget_tierstoretarget'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='January', max_length=100)),
                ('service_target', models.PositiveIntegerField(default=0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_servicetarget', to='Business.business')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_servicetarget', to='Business.businessaddress')),
                ('service_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicegroup_servicetarget', to='Service.servicegroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_servicetarget', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RetailTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='January', max_length=100)),
                ('brand_target', models.PositiveIntegerField(default=0)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_retailtarget', to='Product.brand')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_retailtarget', to='Business.business')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_retailtarget', to='Business.businessaddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_retailtarget', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
