# Generated by Django 3.2.15 on 2022-12-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TragetControl', '0003_retailtarget_servicetarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailtarget',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='retailtarget',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servicetarget',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='servicetarget',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
