# Generated by Django 3.2.15 on 2022-12-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TragetControl', '0004_auto_20221214_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafftarget',
            name='year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
