# Generated by Django 3.2.15 on 2022-12-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TragetControl', '0005_stafftarget_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stafftarget',
            name='year',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
