# Generated by Django 3.2.15 on 2022-12-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TragetControl', '0006_alter_stafftarget_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailtarget',
            name='year',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicetarget',
            name='year',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tierstoretarget',
            name='year',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
