# Generated by Django 4.0.6 on 2023-08-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TragetControl', '0007_auto_20221222_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailtarget',
            name='brand_target',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='servicetarget',
            name='service_target',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stafftarget',
            name='retail_target',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stafftarget',
            name='service_target',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tierstoretarget',
            name='membership_target',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tierstoretarget',
            name='retail_target',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tierstoretarget',
            name='service_target',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tierstoretarget',
            name='voucher_target',
            field=models.FloatField(default=0),
        ),
    ]
