# Generated by Django 4.0.6 on 2022-07-28 07:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=128)),
                ('middle_name', models.CharField(blank=True, max_length=128, null=True)),
                ('last_name', models.CharField(blank=True, max_length=128, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_mobile_verified', models.BooleanField(default=False)),
                ('social_account', models.BooleanField(default=False)),
                ('social_platform', models.CharField(blank=True, choices=[('Google', 'Google'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Apple', 'Apple')], max_length=32, null=True)),
                ('social_id', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('updated_at', models.DateTimeField(verbose_name='Updated Date Time')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenantDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nstyle_user_id', models.CharField(blank=True, default='', max_length=1000, null=True, unique=True)),
                ('is_tenant_admin', models.BooleanField(default=False)),
                ('is_tenant_staff', models.BooleanField(default=False)),
                ('is_tenant_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_detail', to='Authentication.user')),
            ],
        ),
        migrations.CreateModel(
            name='NewsLetterDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_subscribed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletter', to='Authentication.user')),
            ],
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('account_type', models.CharField(choices=[('Everyone', 'Everyone'), ('Business', 'Business')], default='Everyone', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_account_type', to='Authentication.user')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(default='', max_length=10)),
                ('code_for', models.CharField(choices=[('Email', 'Email'), ('Mobile', 'Mobile')], default='Mobile', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_otp', to='Authentication.user')),
            ],
            options={
                'unique_together': {('user', 'code', 'code_for')},
            },
        ),
    ]
