# Generated by Django 4.0.6 on 2022-07-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated Date Time'),
        ),
    ]
