# Generated by Django 3.2.15 on 2023-01-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='account_type',
            field=models.CharField(choices=[('Everyone', 'Everyone'), ('Business', 'Business'), ('Employee', 'Employee')], default='Everyone', max_length=20),
        ),
    ]
