# Generated by Django 4.0.6 on 2023-05-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_alter_accounttype_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_asked_for_data_update',
            field=models.BooleanField(default=False, verbose_name='Is Asked user to update his Default Data ( Location, Client, Employee, Service)? :'),
        ),
    ]
