# Generated by Django 4.0.6 on 2022-08-02 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Profile', '0002_userlanguage'),
        ('Utility', '0002_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('business_name', models.CharField(default='', max_length=300)),
                ('logo', models.ImageField(upload_to='business/logo/')),
                ('banner', models.ImageField(upload_to='business/banner/')),
                ('postal_code', models.CharField(default='', max_length=30)),
                ('team_size', models.CharField(default='', max_length=100)),
                ('timezone', models.CharField(default='', max_length=200)),
                ('how_find_us', models.CharField(default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='business/business_types/images/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessState',
            fields=[
                ('state_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Utility.state')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_state', to='Business.business')),
            ],
            bases=('Utility.state',),
        ),
        migrations.CreateModel(
            name='BusinessCountry',
            fields=[
                ('country_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Utility.country')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_country', to='Business.business')),
            ],
            bases=('Utility.country',),
        ),
        migrations.CreateModel(
            name='BusinessCity',
            fields=[
                ('city_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Utility.city')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_city', to='Business.business')),
            ],
            bases=('Utility.city',),
        ),
        migrations.AddField(
            model_name='business',
            name='business_types',
            field=models.ManyToManyField(related_name='type_businesses', to='Business.businesstype'),
        ),
        migrations.AddField(
            model_name='business',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Utility.currency'),
        ),
        migrations.AddField(
            model_name='business',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_business', to='Profile.profile'),
        ),
        migrations.AddField(
            model_name='business',
            name='software_used',
            field=models.ManyToManyField(related_name='software_businesses', to='Utility.software'),
        ),
        migrations.AddField(
            model_name='business',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_business', to=settings.AUTH_USER_MODEL),
        ),
    ]
