# Generated by Django 4.0.6 on 2023-12-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0001_initial_squashed_0038_alter_businessvendor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaddress',
            name='privacy_policy',
            field=models.TextField(null=True),
        ),
    ]
