# Generated by Django 4.0.6 on 2022-08-09 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Utility', '0002_currency'),
        ('Business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('address', models.TextField(default='')),
                ('latitude', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('longitude', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('postal_code', models.CharField(default='', max_length=30)),
                ('gstin', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('website', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('mobile_number', models.CharField(default='', max_length=30)),
                ('is_mobile_verified', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessOpeningHour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('day', models.CharField(default='', max_length=20)),
                ('start_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('is_closed', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessSocial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('website', models.TextField()),
                ('facebook', models.TextField()),
                ('instagram', models.TextField()),
                ('whatsapp', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='businesscountry',
            name='business',
        ),
        migrations.RemoveField(
            model_name='businesscountry',
            name='country_ptr',
        ),
        migrations.RemoveField(
            model_name='businessstate',
            name='business',
        ),
        migrations.RemoveField(
            model_name='businessstate',
            name='state_ptr',
        ),
        migrations.AddField(
            model_name='business',
            name='time_format',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='business',
            name='week_start',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.DeleteModel(
            name='BusinessCity',
        ),
        migrations.DeleteModel(
            name='BusinessCountry',
        ),
        migrations.DeleteModel(
            name='BusinessState',
        ),
        migrations.AddField(
            model_name='businesssocial',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_socials', to='Business.business'),
        ),
        migrations.AddField(
            model_name='businesssocial',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_socials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessopeninghour',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_hours', to='Business.business'),
        ),
        migrations.AddField(
            model_name='businessopeninghour',
            name='business_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_address_hours', to='Business.businessaddress'),
        ),
        migrations.AddField(
            model_name='businessaddress',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_address', to='Business.business'),
        ),
        migrations.AddField(
            model_name='businessaddress',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_city', to='Utility.city'),
        ),
        migrations.AddField(
            model_name='businessaddress',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_country', to='Utility.country'),
        ),
        migrations.AddField(
            model_name='businessaddress',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_state', to='Utility.state'),
        ),
        migrations.AddField(
            model_name='businessaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to=settings.AUTH_USER_MODEL),
        ),
    ]
