# Generated by Django 4.0.6 on 2022-08-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0002_businessaddress_businessopeninghour_businesssocial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='week_start',
            field=models.CharField(default='Monday', max_length=20),
        ),
    ]
