# Generated by Django 4.0.6 on 2023-12-26 11:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0002_businessaddress_privacy_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('refund_days', models.IntegerField(default=30)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Business.businessaddress')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
