# Generated by Django 4.0.6 on 2022-08-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0003_alter_business_week_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaddress',
            name='address_name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
