# Generated by Django 4.0.6 on 2023-12-27 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0003_refundsetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refundsetting',
            old_name='refund_days',
            new_name='number_of_days',
        ),
        migrations.AlterField(
            model_name='refundsetting',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund_location', to='Business.businessaddress'),
        ),
    ]
