# Generated by Django 4.0.6 on 2022-08-12 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Business', '0004_businessaddress_address_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('primary_color', models.CharField(default='', max_length=20)),
                ('secondary_color', models.CharField(default='', max_length=20)),
                ('menu_option', models.CharField(default='', max_length=300, null=True)),
                ('calendar_option', models.CharField(choices=[('HorizontalView', 'Horizontal View'), ('VerticalView', 'Vertical View')], default='HorizontalView', max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_theme', to='Business.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_theme', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
