# Generated by Django 4.0.6 on 2023-12-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0004_rename_refund_days_refundsetting_number_of_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundsetting',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
