# Generated by Django 4.0.6 on 2023-12-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0005_alter_refundsetting_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundsetting',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
