# Generated by Django 4.0.6 on 2024-01-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0006_alter_refundsetting_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesstheme',
            name='menu_option',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
