# Generated by Django 4.0.6 on 2024-01-23 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0007_alter_businesstheme_menu_option'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RefundSetting',
        ),
    ]
