# Generated by Django 4.0.6 on 2022-08-16 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Business', '0007_bookingsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTax',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tax_type', models.CharField(choices=[('Individual', 'Individual'), ('Group', 'Group'), ('Location', 'Location')], default='Individual', max_length=20)),
                ('name', models.CharField(default='', max_length=100)),
                ('tax_rate', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_tax', to='Business.business')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations_taxs', to='Business.businessaddress')),
                ('parent_tax', models.ManyToManyField(blank=True, null=True, to='Business.businesstax')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tax', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessPaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('method_type', models.CharField(choices=[('Cash', 'Cash'), ('Mastercard', 'Mastercard'), ('Visa', 'Visa'), ('Paypal', 'Paypal'), ('GooglePay', 'Google Pay'), ('ApplePay', 'Apple Pay')], default='Cash', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_available_payment_methods', to='Business.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_available_payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
