# Generated by Django 4.0.6 on 2022-08-18 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Utility', '0007_language_code'),
        ('Business', '0008_businesstax_businesspaymentmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessVendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('vendor_name', models.CharField(default='', max_length=500)),
                ('address', models.TextField(default='')),
                ('latitude', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('longitude', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('postal_code', models.CharField(default='', max_length=30)),
                ('gstin', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('website', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('mobile_number', models.CharField(default='', max_length=30)),
                ('is_mobile_verified', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_vendors', to='Business.business')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_vendors', to='Utility.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_vendors', to='Utility.country')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_vendors', to='Utility.state')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_vendors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
