# Generated by Django 4.0.6 on 2022-08-26 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0009_businessvendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesstax',
            name='parent_tax',
            field=models.ManyToManyField(blank=True, to='Business.businesstax'),
        ),
    ]
