# Generated by Django 4.0.6 on 2022-08-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0010_alter_businesstax_parent_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesstheme',
            name='theme_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
