# Generated by Django 3.2.15 on 2022-09-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0011_businesstheme_theme_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessvendor',
            name='mobile_number',
            field=models.CharField(default=' ', max_length=30),
        ),
    ]
