# Generated by Django 3.2.15 on 2022-09-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0012_alter_businessvendor_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessvendor',
            name='is_email_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='businessvendor',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
