# Generated by Django 4.0.6 on 2022-09-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0015_auto_20220905_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessopeninghour',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessopeninghour',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
