# Generated by Django 3.2.15 on 2022-09-28 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0018_businesstype_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessopeninghour',
            name='business_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_address_hours', to='Business.businessaddress'),
        ),
        migrations.AlterUniqueTogether(
            name='businessopeninghour',
            unique_together={('business', 'business_address', 'day')},
        ),
    ]
