# Generated by Django 4.0.6 on 2022-09-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0019_auto_20220928_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesstype',
            name='slug',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
