# Generated by Django 3.2.15 on 2022-09-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0020_businesstype_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaddress',
            name='banking',
            field=models.CharField(choices=[('Enable', 'Enable'), ('Disable', 'Disable')], default='Disable', max_length=50),
        ),
    ]
