# Generated by Django 3.2.15 on 2022-12-17 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Utility', '0012_auto_20221015_1633'),
        ('Business', '0022_business_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaddress',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_currency', to='Utility.currency'),
        ),
    ]
