# Generated by Django 3.2.15 on 2022-12-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0024_auto_20221220_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaddress',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
    ]
