# Generated by Django 3.2.15 on 2022-12-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0025_businessaddress_is_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessaddress',
            name='service_avaiable',
            field=models.CharField(choices=[('Everyone', 'Everyone'), ('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=100),
        ),
    ]
