# Generated by Django 3.2.15 on 2022-12-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0027_alter_businessaddressmedia_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaddress',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
