# Generated by Django 4.0.6 on 2023-05-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0028_businessaddress_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaddress',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
