# Generated by Django 4.0.6 on 2023-08-10 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Business', '0030_alter_businesstax_tax_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTaxSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tax_setting', models.CharField(choices=[('Combined', 'Combined'), ('Seperately', 'Seperately')], default='', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_tax_setting', to='Business.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tax_setting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
