# Generated by Django 4.0.6 on 2023-08-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0031_businesstaxsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_banner_uploaded_s3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='is_logo_uploaded_s3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessaddressmedia',
            name='is_image_uploaded_s3',
            field=models.BooleanField(default=False),
        ),
    ]
