# Generated by Django 4.0.6 on 2023-09-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0032_business_is_banner_uploaded_s3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessaddress',
            name='service_avaiable',
            field=models.CharField(choices=[('Everyone', 'Everyone'), ('Male', 'Male'), ('Female', 'Female')], default='Everyone', max_length=100),
        ),
    ]
