# Generated by Django 4.0.6 on 2023-10-11 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MultiLanguage', '0006_translationlabels'),
        ('Business', '0033_alter_businessaddress_service_avaiable'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaddress',
            name='primary_translation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MultiLanguage.invoicetranslation'),
        ),
    ]
