# Generated by Django 4.0.6 on 2023-10-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0037_businessprivacy_businesspolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessvendor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
