# Generated by Django 4.0.6 on 2023-12-13 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='segemnt_type',
            field=models.CharField(choices=[('static', 'Static'), ('dynamic', 'Dynamic')], max_length=30),
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=300, unique=True)),
                ('content', models.TextField(default='')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('compingn_type', models.CharField(choices=[('email', 'Email'), ('appnotifaction', 'AppNotifaction'), ('both', 'Both')], max_length=20)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.segment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
