# Generated by Django 4.0.6 on 2023-12-14 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_remove_campaign_end_date_alter_campaign_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='compingn_type',
            new_name='campaign_type',
        ),
        migrations.RenameField(
            model_name='segment',
            old_name='segemnt_type',
            new_name='segment_type',
        ),
    ]
