# Generated by Django 4.0.6 on 2023-12-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0004_rename_compingn_type_campaign_campaign_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_type',
            field=models.CharField(choices=[('email', 'Email'), ('App Notification', 'AppNotification'), ('both', 'Both')], max_length=20),
        ),
    ]
