# Generated by Django 4.0.6 on 2023-12-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0005_campaign_end_date_alter_campaign_campaign_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
