# Generated by Django 4.0.6 on 2023-11-01 07:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('Utility', '0001_initial'), ('Utility', '0002_currency'), ('Utility', '0003_city_unique_code_country_unique_code_and_more'), ('Utility', '0004_country_dial_code'), ('Utility', '0005_country_key'), ('Utility', '0006_city_key_state_key'), ('Utility', '0007_language_code'), ('Utility', '0008_nstylefile'), ('Utility', '0009_exceptionrecord'), ('Utility', '0010_software_image_path'), ('Utility', '0011_auto_20221015_1620'), ('Utility', '0012_auto_20221015_1633'), ('Utility', '0013_turnoverproductrecord'), ('Utility', '0014_exceptionrecord_method_exceptionrecord_path_and_more'), ('Utility', '0015_city_is_flag_uploaded_s3_country_is_flag_uploaded_s3_and_more'), ('Utility', '0016_exceptionrecord_tenant'), ('Utility', '0017_city_country_unique_id_city_state_unique_id_and_more'), ('Utility', '0018_state_unique_id')]

    dependencies = [
        ('Tenants', '0007_tenant_is_ready'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=200)),
                ('flag', models.ImageField(blank=True, null=True, upload_to='Utility/country/')),
                ('code', models.CharField(default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unique_code', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('dial_code', models.CharField(default='', max_length=50)),
                ('key', models.CharField(default='', max_length=20)),
                ('is_flag_uploaded_s3', models.BooleanField(default=False)),
                ('unique_id', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=200)),
                ('flag', models.ImageField(blank=True, null=True, upload_to='Utility/country/')),
                ('code', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_states', to='Utility.country')),
                ('unique_code', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('key', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('is_flag_uploaded_s3', models.BooleanField(default=False)),
                ('country_unique_id', models.CharField(blank=True, max_length=256, null=True)),
                ('unique_id', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=200)),
                ('code', models.CharField(default='', max_length=20)),
                ('symbol', models.TextField(default='')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NstyleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='utility/files/')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalPermissionChoices',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('text', models.CharField(default='', max_length=1000)),
                ('slug', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TurnOverProductRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField()),
                ('i_email', models.CharField(default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Utility/softwares/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_path', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('is_image_uploaded_s3', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ExceptionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('method', models.TextField(blank=True, null=True)),
                ('path', models.TextField(blank=True, null=True)),
                ('status_code', models.TextField(blank=True, null=True)),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_exceptions', to='Tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=200)),
                ('flag', models.ImageField(blank=True, null=True, upload_to='Utility/country/')),
                ('code', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_cities', to='Utility.country')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_cities', to='Utility.state')),
                ('unique_code', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('key', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('is_flag_uploaded_s3', models.BooleanField(default=False)),
                ('country_unique_id', models.CharField(blank=True, max_length=256, null=True)),
                ('state_unique_id', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
