# Generated by Django 4.0.6 on 2022-08-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utility', '0002_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='unique_code',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='unique_code',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='unique_code',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
