# Generated by Django 4.0.6 on 2022-08-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utility', '0003_city_unique_code_country_unique_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='dial_code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
