# Generated by Django 4.0.6 on 2022-08-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utility', '0004_country_dial_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='key',
            field=models.CharField(default='', max_length=20),
        ),
    ]
