# Generated by Django 4.0.6 on 2022-08-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utility', '0005_country_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='key',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='key',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
