# Generated by Django 4.0.6 on 2022-08-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utility', '0006_city_key_state_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='code',
            field=models.CharField(default='', max_length=200),
        ),
    ]
