# Generated by Django 3.2.15 on 2022-09-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utility', '0007_language_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='NstyleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='utility/files/')),
            ],
        ),
    ]
