# Generated by Django 3.2.15 on 2022-10-15 11:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Utility', '0010_software_image_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPermissionChoices',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('text', models.CharField(default='', max_length=100)),
                ('slug', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
