# Generated by Django 3.2.15 on 2022-10-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utility', '0011_auto_20221015_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalpermissionchoices',
            name='slug',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='globalpermissionchoices',
            name='text',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
