# Generated by Django 4.0.6 on 2023-07-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utility', '0013_turnoverproductrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceptionrecord',
            name='method',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceptionrecord',
            name='path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceptionrecord',
            name='status_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
