# Generated by Django 4.0.6 on 2023-09-18 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0007_tenant_is_ready'),
        ('Utility', '0015_city_is_flag_uploaded_s3_country_is_flag_uploaded_s3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceptionrecord',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_exceptions', to='Tenants.tenant'),
        ),
    ]
