# Generated by Django 4.0.6 on 2023-10-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utility', '0017_city_country_unique_id_city_state_unique_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='unique_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
