# Generated by Django 4.0.6 on 2023-05-30 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=132, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, max_length=132, null=True)),
                ('label', models.TextField(blank=True, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='language_labels', to='Translations.language')),
            ],
        ),
    ]
