# Generated by Django 4.0.6 on 2023-11-01 07:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('Sale', '0001_initial'), ('Sale', '0002_auto_20220930_1507'), ('Sale', '0003_delete_service')]

    dependencies = [
        ('Business', '0001_initial_squashed_0038_alter_businessvendor_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Employee', '0011_commissionschemesetting'),
    ]

    operations = [
    ]
