# Generated by Django 3.2.15 on 2022-09-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sale', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service',
        ),
        migrations.AddField(
            model_name='service',
            name='parrent_service',
            field=models.ManyToManyField(blank=True, null=True, related_name='package_services', to='Sale.Service'),
        ),
    ]
