# Generated by Django 3.2.15 on 2022-10-04 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sale', '0002_auto_20220930_1507'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
