# Generated by Django 4.0.6 on 2023-05-22 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Business', '0028_businessaddress_description'),
        ('Client', '0062_alter_loyaltypointlogs_balance'),
        ('Employee', '0045_employedailyschedule_vacation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Sale', '0003_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('client_type', models.CharField(choices=[('Walk_in', 'Walk-in'), ('In_Saloon', 'In-Saloon')], default='', max_length=50)),
                ('payment_type', models.CharField(choices=[('Cash', 'Cash'), ('Voucher', 'Voucher'), ('SplitBill', 'SplitBill'), ('MasterCard', 'MasterCard'), ('Other', 'Other')], default='', max_length=50)),
                ('tip', models.PositiveBigIntegerField(default=0)),
                ('total_service_price', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('total_product_price', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('total_voucher_price', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('total_membership_price', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('service_commission', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('product_commission', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('voucher_commission', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('service_commission_type', models.CharField(default='', max_length=50)),
                ('product_commission_type', models.CharField(default='', max_length=50)),
                ('voucher_commission_type', models.CharField(default='', max_length=50)),
                ('is_promotion', models.BooleanField(default=False)),
                ('selected_promotion_id', models.CharField(default='', max_length=800)),
                ('selected_promotion_type', models.CharField(default='', max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Client.client')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Business.businessaddress')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Employee.employee')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
