# Generated by Django 4.0.6 on 2023-05-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sale', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='appointment',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='appointment_service',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='business_address',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='gst',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='gst_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='service',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='service_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='member',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
