# Generated by Django 4.0.6 on 2024-01-24 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0042_employedailyschedule_last_state_of_schedule_and_more'),
        ('Promotions', '0027_alter_coupon_usage_limit_alter_coupon_user_limit'),
        ('Business', '0008_delete_refundsetting'),
        ('Product', '0003_productstock_refund_quantity'),
        ('Client', '0002_client_client_tag_client_client_type'),
        ('SaleRecords', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salerecords',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='salerecords',
            name='coupon_discounted_price',
        ),
        migrations.RemoveField(
            model_name='salerecords',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='salerecords',
            name='is_coupon_redeemed',
        ),
        migrations.RemoveField(
            model_name='salerecords',
            name='redeem_option',
        ),
        migrations.RemoveField(
            model_name='salerecords',
            name='total_discount',
        ),
        migrations.RemoveField(
            model_name='salerecords',
            name='voucher_redeem_percentage',
        ),
        migrations.AddField(
            model_name='redeemeditems',
            name='discount',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='redeemeditems',
            name='percentage',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='redeemeditems',
            name='redeem_option',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='salerecordappliedcoupons',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Promotions.coupon'),
        ),
        migrations.AddField(
            model_name='salerecordappliedcoupons',
            name='coupon_discounted_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='salerecords',
            name='selected_promotion_type',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='redeemeditems',
            name='is_redeemed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='salerecordappliedcoupons',
            name='is_coupon_redeemed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='salerecords',
            name='business_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_records_business_address', to='Business.businessaddress'),
        ),
        migrations.AlterField(
            model_name='salerecords',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_records_client', to='Client.client'),
        ),
        migrations.AlterField(
            model_name='salerecords',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_records_member', to='Employee.employee'),
        ),
        migrations.AlterField(
            model_name='salerecordservices',
            name='sale_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_services_records', to='SaleRecords.salerecords'),
        ),
        migrations.AlterField(
            model_name='salerecordsproducts',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.product'),
        ),
        migrations.AlterField(
            model_name='salerecordtip',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_record_employee_tips', to='Employee.employee'),
        ),
        migrations.AlterField(
            model_name='salerecordtip',
            name='tip_amount',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='saletax',
            name='sale_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_tax_records', to='SaleRecords.salerecords'),
        ),
        migrations.AlterField(
            model_name='saletax',
            name='tax_percentage',
            field=models.FloatField(default=0),
        ),
    ]
