# Generated by Django 4.0.6 on 2024-01-24 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0003_alter_saleinvoice_checkout_type'),
        ('Business', '0008_delete_refundsetting'),
        ('SaleRecords', '0003_alter_paymentmethods_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salerecords',
            name='business_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_records_business_address', to='Business.businessaddress'),
        ),
        migrations.AlterField(
            model_name='salerecords',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Invoices.saleinvoice'),
        ),
    ]
