# Generated by Django 4.0.6 on 2024-01-24 13:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0003_alter_saleinvoice_checkout_type'),
        ('Client', '0002_client_client_tag_client_client_type'),
        ('Product', '0003_productstock_refund_quantity'),
        ('Service', '0003_servicegroup_image_servicegroup_is_image_uploaded_s3'),
        ('Appointment', '0030_reversal_url'),
        ('Business', '0008_delete_refundsetting'),
        ('Employee', '0042_employedailyschedule_last_state_of_schedule_and_more'),
        ('Finance', '0008_alter_refundcoupon_related_refund'),
        ('SaleRecords', '0006_alter_salerecords_refunds_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redeemeditems',
            old_name='sale_order',
            new_name='sale_record',
        ),
        migrations.RenameField(
            model_name='salerecordappliedcoupons',
            old_name='sale_records',
            new_name='sale_record',
        ),
        migrations.RenameField(
            model_name='saletax',
            old_name='sale_order',
            new_name='sale_record',
        ),
        migrations.RemoveField(
            model_name='paymentmethods',
            name='sale_records',
        ),
        migrations.RemoveField(
            model_name='salerecords',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='salerecordtip',
            name='member',
        ),
        migrations.AddField(
            model_name='paymentmethods',
            name='sale_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_payment_methods_records', to='SaleRecords.salerecords'),
        ),
        migrations.AddField(
            model_name='salerecordsappointmentservices',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_appointment_services_employee', to='Employee.employee'),
        ),
        migrations.AddField(
            model_name='salerecordservices',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Employee.employee'),
        ),
        migrations.AddField(
            model_name='salerecordsproducts',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Employee.employee'),
        ),
        migrations.AddField(
            model_name='salerecordtip',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_record_employee_tips', to='Employee.employee'),
        ),
        migrations.AlterField(
            model_name='salerecords',
            name='business_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_records_business_address', to='Business.businessaddress'),
        ),
        migrations.AlterField(
            model_name='salerecords',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_records_client', to='Client.client'),
        ),
        migrations.AlterField(
            model_name='salerecords',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Invoices.saleinvoice'),
        ),
        migrations.AlterField(
            model_name='salerecords',
            name='refunds_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='Finance.refund'),
        ),
        migrations.AlterField(
            model_name='salerecordsappointmentservices',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appointment.appointment'),
        ),
        migrations.AlterField(
            model_name='salerecordsappointmentservices',
            name='sale_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_appointment_services_records', to='SaleRecords.salerecords'),
        ),
        migrations.AlterField(
            model_name='salerecordsappointmentservices',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Service.service'),
        ),
        migrations.AlterField(
            model_name='salerecordservices',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Service.service'),
        ),
        migrations.AlterField(
            model_name='salerecordsproducts',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.product'),
        ),
        migrations.AlterField(
            model_name='saletax',
            name='business_tax_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Business.businesstax'),
        ),
        migrations.CreateModel(
            name='SaleRecordVouchers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField(default=0)),
                ('qty', models.PositiveSmallIntegerField(default=0)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_vouchers_employee', to='Employee.employee')),
                ('sale_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_vouchers_records', to='SaleRecords.salerecords')),
                ('vouchers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Client.vouchers')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaleRecordMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField(default=0)),
                ('qty', models.PositiveSmallIntegerField(default=0)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_membership_employee', to='Employee.employee')),
                ('membership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Client.membership')),
                ('sale_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_membership_records', to='SaleRecords.salerecords')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
