# Generated by Django 4.0.6 on 2024-01-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0007_rename_sale_order_redeemeditems_sale_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethods',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash Payment'), ('master', 'Master Payment'), ('visa', 'Visa Payment'), ('paypal', 'PayPal Payment'), ('gift', 'Gift Payment')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salerecordmembership',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salerecordmembership',
            name='qty',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='salerecords',
            name='client_type',
            field=models.CharField(choices=[('Walk_in', 'Walk In'), ('In_Saloon', 'In Saloon')], max_length=50),
        ),
        migrations.AlterField(
            model_name='salerecords',
            name='sub_total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salerecordsappointmentservices',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='salerecordsappointmentservices',
            name='is_favourite',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='salerecordsappointmentservices',
            name='qty',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='salerecordservices',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salerecordservices',
            name='qty',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='salerecordsproducts',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salerecordsproducts',
            name='qty',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='salerecordtip',
            name='tip_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salerecordvouchers',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salerecordvouchers',
            name='qty',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='saletax',
            name='tax_name',
            field=models.CharField(max_length=999),
        ),
        migrations.AlterField(
            model_name='saletax',
            name='tax_percentage',
            field=models.FloatField(),
        ),
    ]
