# Generated by Django 4.0.6 on 2024-01-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0008_alter_paymentmethods_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salerecords',
            name='is_promotion',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='salerecords',
            name='selected_promotion_id',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='salerecords',
            name='selected_promotion_type',
            field=models.CharField(max_length=400),
        ),
    ]
