# Generated by Django 4.0.6 on 2024-01-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0010_alter_redeemeditems_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saletax',
            name='tax_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='saletax',
            name='tax_percentage',
            field=models.FloatField(default=0),
        ),
    ]
