# Generated by Django 4.0.6 on 2024-01-25 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0011_saletax_tax_value_alter_saletax_tax_percentage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RedeemedItems',
        ),
    ]
