# Generated by Django 4.0.6 on 2024-01-26 11:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0003_alter_saleinvoice_checkout_type'),
        ('Finance', '0009_alter_refundproduct_product_and_more'),
        ('Client', '0004_rename_file_name_clientimages_name'),
        ('Employee', '0042_employedailyschedule_last_state_of_schedule_and_more'),
        ('SaleRecords', '0012_delete_redeemeditems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salerecordappliedcoupons',
            old_name='is_coupon_redeemed',
            new_name='is_redeemed',
        ),
        migrations.RemoveField(
            model_name='salerecordmembership',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='salerecords',
            name='is_promotion',
        ),
        migrations.RemoveField(
            model_name='salerecords',
            name='selected_promotion_id',
        ),
        migrations.RemoveField(
            model_name='salerecords',
            name='selected_promotion_type',
        ),
        migrations.RemoveField(
            model_name='salerecordvouchers',
            name='employee',
        ),
        migrations.AddField(
            model_name='salerecords',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_records_member', to='Employee.employee'),
        ),
        migrations.AddField(
            model_name='salerecords',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_record_promotions', to='Client.promotion'),
        ),
        migrations.AddField(
            model_name='salerecords',
            name='total_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='salerecords',
            name='total_tax',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='salerecords',
            name='total_tip',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='salerecordsappointmentservices',
            name='discounted_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='salerecordservices',
            name='discounted_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='salerecordsproducts',
            name='discounted_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salerecords',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_record_invoice', to='Invoices.saleinvoice'),
        ),
        migrations.AlterField(
            model_name='salerecords',
            name='refunds_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_record_refunds', to='Finance.refund'),
        ),
        migrations.AlterField(
            model_name='salerecordservices',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='AppliedVouchers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_redeemed', models.BooleanField(default=True)),
                ('sale_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_applied_vouchers_records', to='SaleRecords.salerecords')),
                ('voucher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Client.vouchers')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppliedMemberships',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_redeemed', models.BooleanField(default=False)),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Client.membership')),
                ('sale_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_applied_memberships_records', to='SaleRecords.salerecords')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
