# Generated by Django 4.0.6 on 2024-01-26 12:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0042_employedailyschedule_last_state_of_schedule_and_more'),
        ('SaleRecords', '0013_rename_is_coupon_redeemed_salerecordappliedcoupons_is_redeemed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedvouchers',
            name='is_redeemed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PurchasedGiftCards',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField(default=0)),
                ('gift_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_gift_cards_records', to='Employee.giftcards')),
                ('sale_record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_gift_cards_records', to='SaleRecords.salerecords')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppliedGiftCards',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_redeemed', models.BooleanField(default=False)),
                ('gift_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_applied_gift_cards_records', to='Employee.giftcards')),
                ('sale_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_applied_gift_cards_records', to='SaleRecords.salerecords')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
