# Generated by Django 4.0.6 on 2024-01-27 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0032_alter_reversal_request_status'),
        ('SaleRecords', '0014_alter_appliedvouchers_is_redeemed_purchasedgiftcards_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethods',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash Payment'), ('mastercard', 'Master Card Payment'), ('visa', 'Visa Payment'), ('paypal', 'PayPal Payment'), ('gift', 'Gift Payment')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salerecordsappointmentservices',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Appointment.appointment'),
        ),
    ]
