# Generated by Django 4.0.6 on 2024-01-27 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0032_alter_reversal_request_status'),
        ('SaleRecords', '0015_alter_paymentmethods_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salerecordsappointmentservices',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_appointments_records', to='Appointment.appointment'),
        ),
    ]
