# Generated by Django 4.0.6 on 2024-01-27 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0016_alter_salerecordsappointmentservices_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salerecordsappointmentservices',
            old_name='appointment',
            new_name='appointment_id',
        ),
    ]
