# Generated by Django 4.0.6 on 2024-01-27 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0017_rename_appointment_salerecordsappointmentservices_appointment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salerecordsappointmentservices',
            old_name='appointment_id',
            new_name='appointment',
        ),
    ]
