# Generated by Django 4.0.6 on 2024-01-27 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0018_rename_appointment_id_salerecordsappointmentservices_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedgiftcards',
            name='sale_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applied_gift_cards_records', to='SaleRecords.salerecords'),
        ),
        migrations.AlterField(
            model_name='appliedmemberships',
            name='sale_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applied_memberships_records', to='SaleRecords.salerecords'),
        ),
        migrations.AlterField(
            model_name='appliedvouchers',
            name='sale_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applied_vouchers_records', to='SaleRecords.salerecords'),
        ),
        migrations.AlterField(
            model_name='paymentmethods',
            name='sale_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_methods_records', to='SaleRecords.salerecords'),
        ),
        migrations.AlterField(
            model_name='purchasedgiftcards',
            name='sale_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_cards_records', to='SaleRecords.salerecords'),
        ),
        migrations.AlterField(
            model_name='salerecordappliedcoupons',
            name='sale_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applied_coupons_records', to='SaleRecords.salerecords'),
        ),
        migrations.AlterField(
            model_name='salerecordmembership',
            name='sale_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership_records', to='SaleRecords.salerecords'),
        ),
        migrations.AlterField(
            model_name='salerecordsappointmentservices',
            name='sale_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_services', to='SaleRecords.salerecords'),
        ),
        migrations.AlterField(
            model_name='salerecordservices',
            name='sale_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services_records', to='SaleRecords.salerecords'),
        ),
        migrations.AlterField(
            model_name='salerecordsproducts',
            name='sale_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_records', to='SaleRecords.salerecords'),
        ),
        migrations.AlterField(
            model_name='salerecordtip',
            name='sale_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tip_records', to='SaleRecords.salerecords'),
        ),
        migrations.AlterField(
            model_name='salerecordvouchers',
            name='sale_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers_records', to='SaleRecords.salerecords'),
        ),
        migrations.AlterField(
            model_name='saletax',
            name='sale_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_records', to='SaleRecords.salerecords'),
        ),
    ]
