# Generated by Django 4.0.6 on 2024-01-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0019_alter_appliedgiftcards_sale_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salerecords',
            name='total_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salerecords',
            name='total_tax',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salerecords',
            name='total_tip',
            field=models.FloatField(),
        ),
    ]
