# Generated by Django 4.0.6 on 2024-01-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0021_remove_salerecords_promotion_appliedpromotion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saletax',
            old_name='tax_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='paymentmethods',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash Payment'), ('Mastercard', 'Master Card Payment'), ('Visa', 'Visa Payment'), ('Paypal', 'PayPal Payment')], max_length=50, null=True),
        ),
    ]
