# Generated by Django 4.0.6 on 2024-01-29 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0022_rename_tax_name_saletax_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salerecords',
            old_name='business_address',
            new_name='location',
        ),
    ]
