# Generated by Django 4.0.6 on 2024-01-30 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0026_alter_salerecords_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salerecords',
            name='invoice',
        ),
    ]
