# Generated by Django 4.0.6 on 2024-01-30 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0005_remove_saleinvoice_payment_method'),
        ('Client', '0008_alter_vouchers_end_date'),
        ('SaleRecords', '0028_remove_salerecords_refunds_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerecords',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_record_invoice', to='Invoices.saleinvoice'),
        ),
        migrations.AlterField(
            model_name='salerecords',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_records_client', to='Client.client'),
        ),
    ]
