# Generated by Django 4.0.6 on 2024-01-30 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0030_remove_salerecords_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salerecords',
            name='invoice',
        ),
    ]
