# Generated by Django 4.0.6 on 2024-01-31 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0031_remove_salerecords_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salerecordsappointmentservices',
            old_name='qty',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='salerecordservices',
            old_name='qty',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='salerecordsproducts',
            old_name='qty',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='salerecordvouchers',
            old_name='qty',
            new_name='quantity',
        ),
    ]
