# Generated by Django 4.0.6 on 2024-01-31 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0032_rename_qty_salerecordsappointmentservices_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salerecordtip',
            old_name='tip_amount',
            new_name='tip',
        ),
    ]
