# Generated by Django 4.0.6 on 2024-01-31 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0033_rename_tip_amount_salerecordtip_tip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salerecordmembership',
            old_name='qty',
            new_name='quantity',
        ),
    ]
