# Generated by Django 4.0.6 on 2024-01-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0034_rename_qty_salerecordmembership_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedgiftcards',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
