# Generated by Django 4.0.6 on 2024-01-31 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0035_purchasedgiftcards_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedgiftcards',
            name='quantity',
            field=models.SmallIntegerField(default=0),
        ),
    ]
