# Generated by Django 4.0.6 on 2024-01-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0036_alter_purchasedgiftcards_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedgiftcards',
            name='spend_amount',
            field=models.FloatField(default=0),
        ),
    ]
