# Generated by Django 4.0.6 on 2024-01-31 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0037_purchasedgiftcards_spend_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedgiftcards',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salerecordmembership',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salerecordvouchers',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
