# Generated by Django 4.0.6 on 2024-02-01 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0038_purchasedgiftcards_expiry_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasedgiftcards',
            old_name='expiry_date',
            new_name='expiry',
        ),
        migrations.RenameField(
            model_name='salerecordmembership',
            old_name='expiry_date',
            new_name='expiry',
        ),
        migrations.RenameField(
            model_name='salerecordvouchers',
            old_name='expiry_date',
            new_name='expiry',
        ),
    ]
