# Generated by Django 4.0.6 on 2024-02-02 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0039_rename_expiry_date_purchasedgiftcards_expiry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salerecordmembership',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='salerecordmembership',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='salerecordvouchers',
            name='end_date',
        ),
    ]
