# Generated by Django 4.0.6 on 2024-02-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0040_remove_salerecordmembership_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerecordvouchers',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
