# Generated by Django 4.0.6 on 2024-02-02 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0046_rename_retail_price_giftdetail_spend_amount_and_more'),
        ('SaleRecords', '0041_salerecordvouchers_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliedpromotion',
            name='promotion',
        ),
        migrations.RemoveField(
            model_name='salerecordvouchers',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='salerecordvouchers',
            name='start_date',
        ),
        migrations.AddField(
            model_name='appliedpromotion',
            name='promotion_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='appliedpromotion',
            name='promotion_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salerecordvouchers',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_vouchers_employee', to='Employee.employee'),
        ),
    ]
