# Generated by Django 4.0.6 on 2024-02-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0042_remove_appliedpromotion_promotion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerecordmembership',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salerecordmembership',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salerecordvouchers',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salerecordvouchers',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
