# Generated by Django 4.0.6 on 2024-02-02 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0043_salerecordmembership_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliedpromotion',
            old_name='promotion_id',
            new_name='promotion',
        ),
    ]
