# Generated by Django 4.0.6 on 2024-02-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0044_rename_promotion_id_appliedpromotion_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedgiftcards',
            name='partial_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
