# Generated by Django 4.0.6 on 2024-02-02 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0045_appliedgiftcards_partial_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliedgiftcards',
            name='is_redeemed',
        ),
        migrations.AddField(
            model_name='appliedgiftcards',
            name='purchased_gift_card_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puchased_gift_card', to='SaleRecords.purchasedgiftcards'),
        ),
    ]
