# Generated by Django 4.0.6 on 2024-02-02 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0046_remove_appliedgiftcards_is_redeemed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliedgiftcards',
            name='gift_card',
        ),
        migrations.AlterField(
            model_name='appliedmemberships',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SaleRecords.salerecordmembership'),
        ),
        migrations.AlterField(
            model_name='appliedvouchers',
            name='voucher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SaleRecords.salerecordvouchers'),
        ),
    ]
