# Generated by Django 4.0.6 on 2024-02-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0047_remove_appliedgiftcards_gift_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedgiftcards',
            name='sale_code',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
