# Generated by Django 4.0.6 on 2024-02-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0048_purchasedgiftcards_sale_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedgiftcards',
            name='sale_code',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
