# Generated by Django 4.0.6 on 2024-02-05 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0050_redeemedloyaltypoints'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salerecordsappointmentservices',
            old_name='discounted_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='salerecordsappointmentservices',
            old_name='end_time',
            new_name='service_end_time',
        ),
        migrations.RenameField(
            model_name='salerecordsappointmentservices',
            old_name='start_time',
            new_name='service_start_time',
        ),
        migrations.RemoveField(
            model_name='salerecordsappointmentservices',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='salerecordsappointmentservices',
            name='reason',
        ),
    ]
