# Generated by Django 4.0.6 on 2024-02-05 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0051_rename_discounted_price_salerecordsappointmentservices_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salerecordsappointmentservices',
            old_name='appointment_status',
            new_name='service_status',
        ),
    ]
