# Generated by Django 4.0.6 on 2024-02-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0052_rename_appointment_status_salerecordsappointmentservices_service_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salerecordsappointmentservices',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
