# Generated by Django 4.0.6 on 2024-02-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0053_alter_salerecordsappointmentservices_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salerecordappliedcoupons',
            name='coupon_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
