# Generated by Django 4.0.6 on 2024-02-06 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0056_alter_salerecords_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saletax',
            old_name='tax_percentage',
            new_name='tax_rate',
        ),
        migrations.RenameField(
            model_name='saletax',
            old_name='tax_value',
            new_name='value',
        ),
    ]
