# Generated by Django 4.0.6 on 2024-02-06 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0057_rename_tax_percentage_saletax_tax_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saletax',
            old_name='tax_rate',
            new_name='tax_percentage',
        ),
        migrations.RenameField(
            model_name='saletax',
            old_name='value',
            new_name='tax_value',
        ),
    ]
