# Generated by Django 4.0.6 on 2024-02-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0058_rename_tax_rate_saletax_tax_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saletax',
            name='tax_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
