# Generated by Django 4.0.6 on 2024-02-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0062_salerecords_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salerecords',
            name='checkout_type',
            field=models.CharField(choices=[('Appointment', 'Appointment Checkout'), ('Sale', 'Sale Checkout')], max_length=50),
        ),
    ]
