# Generated by Django 4.0.6 on 2024-02-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0063_alter_salerecords_checkout_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salerecords',
            name='checkout_type',
            field=models.CharField(choices=[('appointment_checkout', 'Appointment Checkout'), ('sale_checkout', 'Sale Checkout')], max_length=50),
        ),
        migrations.AlterField(
            model_name='salerecords',
            name='status',
            field=models.CharField(choices=[('Refund', 'Is Refund'), ('cancelled', 'Cancelled'), ('paid', 'Paid'), ('un_paid', 'Un Paid')], default='un_paid', max_length=50),
        ),
    ]
