# Generated by Django 4.0.6 on 2024-02-15 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0068_alter_salerecords_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redeemedloyaltypoints',
            old_name='clinet_loyalty_point',
            new_name='client_loyalty_point',
        ),
    ]
