# Generated by Django 4.0.6 on 2024-02-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0070_salerecordsappointmentservices_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethods',
            name='payment_method',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
