# Generated by Django 4.0.6 on 2024-02-20 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_productstock_refund_quantity'),
        ('Service', '0006_alter_service_service_availible_and_more'),
        ('SaleRecords', '0071_alter_paymentmethods_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salerecordservices',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_sale_record', to='Service.service'),
        ),
        migrations.AlterField(
            model_name='salerecordsproducts',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_sale_records', to='Product.product'),
        ),
    ]
