# Generated by Django 4.0.6 on 2024-02-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0073_salerecordsappointmentservices_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedmemberships',
            name='discount_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appliedvouchers',
            name='discount_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salerecordappliedcoupons',
            name='discount_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salerecords',
            name='discount_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
