# Generated by Django 4.0.6 on 2024-02-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0074_appliedmemberships_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salerecords',
            name='checkout_type',
            field=models.CharField(choices=[('Appointment', 'Appointment Checkout'), ('Sale', 'Sale Checkout'), ('Refund', 'Refund'), ('Group Appointment', 'Group Appointment')], max_length=50),
        ),
    ]
