# Generated by Django 4.0.6 on 2024-02-21 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0009_delete_comments'),
        ('SaleRecords', '0075_alter_salerecords_checkout_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedmemberships',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_memberships_client', to='Client.client'),
        ),
        migrations.AddField(
            model_name='appliedvouchers',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_vouchers_client', to='Client.client'),
        ),
        migrations.AddField(
            model_name='redeemedloyaltypoints',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_loyalty_points_client', to='Client.client'),
        ),
        migrations.AddField(
            model_name='salerecordappliedcoupons',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_coupons_client', to='Client.client'),
        ),
    ]
