# Generated by Django 4.0.6 on 2024-02-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0076_appliedmemberships_client_appliedvouchers_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerecordsappointmentservices',
            name='discounted_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
