# Generated by Django 4.0.6 on 2024-02-26 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0009_delete_comments'),
        ('SaleRecords', '0077_salerecordsappointmentservices_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedgiftcards',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_gift_cards_client', to='Client.client'),
        ),
    ]
