# Generated by Django 4.0.6 on 2024-02-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0078_appliedgiftcards_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerecords',
            name='is_refund',
            field=models.BooleanField(default=False),
        ),
    ]
