# Generated by Django 4.0.6 on 2024-02-28 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0016_refundcoupon_checkout_id'),
        ('SaleRecords', '0079_salerecords_is_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerecordappliedcoupons',
            name='refund_coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Finance.refundcoupon'),
        ),
    ]
