# Generated by Django 4.0.6 on 2024-03-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0082_salerecordappliedcoupons_refund_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerecordmembership',
            name='installment_months',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
