# Generated by Django 4.0.6 on 2024-03-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0083_salerecordmembership_installment_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerecordmembership',
            name='next_insallment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
