# Generated by Django 4.0.6 on 2024-03-05 08:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0084_salerecordmembership_next_insallment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salerecordmembership',
            old_name='next_insallment_date',
            new_name='next_installment_date',
        ),
        migrations.AddField(
            model_name='salerecordmembership',
            name='payable_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salerecordmembership',
            name='remaining_installments',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MembershipInstallments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_installment', models.FloatField(blank=True, null=True)),
                ('memberhsip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installment_memberships', to='SaleRecords.salerecordmembership')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
