# Generated by Django 4.0.6 on 2024-03-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0085_rename_next_insallment_date_salerecordmembership_next_installment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redeemedloyaltypoints',
            name='redeemed_points',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
