# Generated by Django 4.0.6 on 2024-03-08 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0010_membership_is_installment'),
        ('SaleRecords', '0087_rename_memberhsip_membershipinstallments_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedpromotion',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_promotion_client', to='Client.client'),
        ),
    ]
