# Generated by Django 4.0.6 on 2024-03-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0089_remove_appliedpromotion_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerecordmembership',
            name='installment_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
