# Generated by Django 4.0.6 on 2024-03-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0090_salerecordmembership_installment_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerecordmembership',
            name='is_installment',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
