# Generated by Django 4.0.6 on 2024-03-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaleRecords', '0091_salerecordmembership_is_installment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salerecordmembership',
            name='is_installment',
            field=models.BooleanField(default=False),
        ),
    ]
