# Generated by Django 3.2.15 on 2022-10-21 12:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employee', '0020_auto_20221014_1252'),
        ('Product', '0022_alter_product_product_size'),
        ('Business', '0022_business_is_completed'),
        ('Client', '0025_alter_subscription_select_amount'),
        ('Service', '0015_alter_service_service_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('client_type', models.CharField(choices=[('Walk_in', 'Walk-in'), ('In_Saloon', 'In-Saloon')], max_length=50)),
                ('payment_type', models.CharField(choices=[('Cash', 'Cash'), ('Voucher', 'Voucher')], max_length=50)),
                ('current_price', models.PositiveBigIntegerField(default=0)),
                ('tip', models.PositiveBigIntegerField(default=0)),
                ('gst', models.PositiveBigIntegerField(default=0)),
                ('total_price', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Incompleted', 'Incompleted'), ('Expired', 'Expired'), ('Active', 'Active')], default='', max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_orders', to='Client.client')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_orders', to='Business.businessaddress')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_orders', to='Employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='VoucherOrder',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Order.order')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_orders', to='Client.vouchers')),
            ],
            bases=('Order.order',),
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Order.order')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to='Service.service')),
            ],
            bases=('Order.order',),
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_orders', to='Product.product')),
            ],
            bases=('Order.order',),
        ),
        migrations.CreateModel(
            name='MemberShipOrder',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Order.order')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_orders', to='Client.membership')),
            ],
            bases=('Order.order',),
        ),
    ]
