# Generated by Django 4.0.6 on 2023-12-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial_squashed_0038_voucherorder_max_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='coupon_discounted_price',
            field=models.FloatField(null=True),
        ),
    ]
