# Generated by Django 3.2.15 on 2022-10-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='duration',
            field=models.CharField(choices=[('30_Min', '30 Min'), ('60_Min', '60 Min'), ('90_Min', '90 Min'), ('120_Min', '120 Min'), ('150_Min', '150 Min'), ('180_Min', '180 Min'), ('210_Min', '210 Min')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_type',
            field=models.CharField(choices=[('Walk_in', 'Walk-in'), ('In_Saloon', 'In-Saloon')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Voucher', 'Voucher')], default='', max_length=50),
        ),
    ]
