# Generated by Django 3.2.15 on 2022-10-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_alter_order_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Incompleted', 'Incompleted'), ('Expired', 'Expired'), ('Active', 'Active')], default='Active', max_length=100),
        ),
    ]
