# Generated by Django 4.0.6 on 2024-01-12 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_checkout_is_coupon_redeemed'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='is_refund',
            field=models.BooleanField(blank=True, choices=[('refund', 'Refund'), ('cancel', 'Cancel')], default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='previous_sale_checkout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunded_sale_checkout', to='Order.checkout'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_refund',
            field=models.CharField(blank=True, choices=[('refund', 'Refund'), ('cancel', 'Cancel')], default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='previous_order_refunded',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_refunded', to='Order.order'),
        ),
    ]
