# Generated by Django 4.0.6 on 2024-01-16 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_checkout_is_refund_checkout_previous_sale_checkout_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='previous_sale_checkout',
            new_name='previous_checkout',
        ),
        migrations.RemoveField(
            model_name='order',
            name='previous_order_refunded',
        ),
    ]
