# Generated by Django 3.2.15 on 2022-10-31 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0006_auto_20221027_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sold_quantity',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
