# Generated by Django 3.2.15 on 2022-11-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0008_auto_20221107_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
