# Generated by Django 3.2.15 on 2022-11-16 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0032_auto_20221114_1155'),
        ('Order', '0010_alter_checkout_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_orders', to='Client.client'),
        ),
    ]
