# Generated by Django 3.2.15 on 2022-12-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0011_alter_order_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='tip',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
