# Generated by Django 3.2.15 on 2023-01-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0012_checkout_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_commission',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='service_commission',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='voucher_commission',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
