# Generated by Django 3.2.15 on 2023-01-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0013_auto_20230126_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_commission',
        ),
        migrations.RemoveField(
            model_name='order',
            name='service_commission',
        ),
        migrations.RemoveField(
            model_name='order',
            name='voucher_commission',
        ),
        migrations.AddField(
            model_name='checkout',
            name='product_commission',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checkout',
            name='service_commission',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checkout',
            name='voucher_commission',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
