# Generated by Django 3.2.15 on 2023-01-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0014_auto_20230126_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='product_commission_type',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checkout',
            name='service_commission_type',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checkout',
            name='voucher_commission_type',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
