# Generated by Django 3.2.15 on 2023-01-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0015_auto_20230130_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='product_commission',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='product_commission_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='service_commission',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='service_commission_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='voucher_commission',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='voucher_commission_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
