# Generated by Django 3.2.15 on 2023-02-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0016_auto_20230130_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='total_membership_price',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='total_product_price',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='total_service_price',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='total_voucher_price',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
