# Generated by Django 3.2.18 on 2023-02-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0017_auto_20230209_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
