# Generated by Django 3.2.18 on 2023-03-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0018_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
    ]
