# Generated by Django 3.2.18 on 2023-03-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0020_auto_20230302_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='is_promotion',
            field=models.BooleanField(default=False),
        ),
    ]
