# Generated by Django 4.0.6 on 2023-05-03 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0045_employedailyschedule_vacation'),
        ('Order', '0021_checkout_is_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_checkout_orders', to='Employee.employee'),
        ),
    ]
