# Generated by Django 4.0.6 on 2023-05-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0022_alter_checkout_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='selected_promotion_id',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AddField(
            model_name='checkout',
            name='selected_promotion_type',
            field=models.CharField(default='', max_length=400),
        ),
    ]
