# Generated by Django 4.0.6 on 2023-05-16 06:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0045_product_product_size'),
        ('Order', '0024_redeemedmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redeemedmembership',
            name='checkout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkout_redeemed_memberships', to='Order.checkout'),
        ),
        migrations.AlterField(
            model_name='redeemedmembership',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_redeemed_memberships', to='Order.order'),
        ),
        migrations.CreateModel(
            name='RedeemMembershipItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.product')),
                ('redeemed_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redeem_items', to='Order.redeemedmembership')),
            ],
        ),
    ]
