# Generated by Django 4.0.6 on 2023-05-16 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0045_product_product_size'),
        ('Service', '0024_priceservice_currency'),
        ('Order', '0025_alter_redeemedmembership_checkout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeemmembershipitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_services', to='Service.service'),
        ),
        migrations.AlterField(
            model_name='redeemmembershipitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_products', to='Product.product'),
        ),
    ]
