# Generated by Django 4.0.6 on 2023-05-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0026_redeemmembershipitem_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_redeemed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='redeemed_instance_id',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AddField(
            model_name='order',
            name='redeemed_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='redeemed_type',
            field=models.CharField(default='', max_length=300),
        ),
    ]
