# Generated by Django 4.0.6 on 2023-06-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0027_order_is_redeemed_order_redeemed_instance_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='tax_amount',
            field=models.FloatField(default=0, verbose_name='Tax total amount'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='tax_applied',
            field=models.FloatField(default=0, verbose_name='Tax Applied in Percentage'),
        ),
    ]
