# Generated by Django 4.0.6 on 2023-06-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0028_checkout_tax_amount_checkout_tax_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount_price',
            field=models.FloatField(default=0),
        ),
    ]
