# Generated by Django 4.0.6 on 2023-06-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0029_alter_order_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount_percentage',
            field=models.FloatField(default=0),
        ),
    ]
