# Generated by Django 4.0.6 on 2023-08-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0030_alter_order_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='product_commission',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='service_commission',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='tip',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='total_membership_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='total_product_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='total_service_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='total_voucher_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='voucher_commission',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='current_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='gst',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='tip',
            field=models.FloatField(default=0),
        ),
    ]
