# Generated by Django 4.0.6 on 2023-08-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0031_alter_checkout_product_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='tax_amount1',
            field=models.FloatField(default=0, verbose_name='Second Tax total amount'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='tax_applied1',
            field=models.FloatField(default=0, verbose_name='Second Tax Applied in Percentage'),
        ),
    ]
