# Generated by Django 4.0.6 on 2023-08-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0032_checkout_tax_amount1_checkout_tax_applied1'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='tax_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='checkout',
            name='tax_name1',
            field=models.CharField(default='', max_length=250),
        ),
    ]
