# Generated by Django 4.0.6 on 2023-08-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0033_checkout_tax_name_checkout_tax_name1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount_price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
