# Generated by Django 4.0.6 on 2023-09-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0035_order_total_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='total_discount',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_percentage',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
