# Generated by Django 4.0.6 on 2023-09-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0036_checkout_total_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='redeem_option',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='voucher_redeem_percentage',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
